import { Brain, RotateCcw } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { Empty } from "./Learn";

export default function Practice() {
  const { isAuthenticated, loading } = useAuth();
  const questions = trpc.gk.practice.useQuery({ limit: 8 }, { enabled: isAuthenticated });
  const saveAttempt = trpc.gk.submitPractice.useMutation();
  const [answers, setAnswers] = useState<Record<string, string>>({});
  if (loading) return <div className="brutal-card p-8 font-bold">Checking your study space…</div>;
  if (!isAuthenticated) return <div className="mx-auto max-w-2xl py-12 text-center"><div className="brutal-card bg-lemon p-8"><Brain className="mx-auto size-10"/><p className="eyebrow mt-5">Protected practice</p><h1 className="page-title mt-4 text-5xl">PRACTICE WITH<br/>A PURPOSE.</h1><p className="mx-auto mt-5 max-w-lg font-medium leading-7">Sign in to answer source-linked questions and keep an honest record of your quiz attempts.</p><button onClick={()=>startLogin()} className="brutal-button mt-7 px-5 py-3">Sign in to practice</button></div></div>;
  const answered = Object.keys(answers).length;
  const score = (questions.data ?? []).filter(question => answers[question.id] === question.correctOption).length;
  if (questions.isLoading) return <div className="brutal-card p-8 font-bold">Loading a real source question set…</div>;
  if (!questions.data?.length) return <Empty text="No complete verified MCQs are available for this study set yet."/>;
  const save = () => saveAttempt.mutate({ questions: questions.data.map(question => ({ mcqId: question.id, selectedOption: answers[question.id] })) });
  return <div className="space-y-7"><header className="grid gap-5 border-b-[3px] border-black pb-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow">02 / Source practice</p><h1 className="page-title mt-3">PICK. THINK.<br /><span className="text-[#ed4f77]">LOCK IT IN.</span></h1><p className="mt-4 max-w-xl font-medium leading-7 text-muted-foreground">These are complete MCQs from the imported source. Answers are visible only after you choose.</p></div><div className="border-2 border-black bg-lemon p-4 shadow-[4px_4px_0_#111]"><p className="mono text-[10px]">CURRENT SCORE</p><p className="mt-1 text-3xl font-bold tracking-[-.07em]">{score} / {questions.data.length}</p></div></header><div className="space-y-4">{questions.data.map((question,index)=>{const selected=answers[question.id]; return <article key={question.id} className="brutal-card p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><span className="mono bg-mint px-2 py-1 text-[10px] font-bold">QUESTION {String(index+1).padStart(2,"0")}</span><span className="mono text-[10px]">SOURCE PAGE {question.sourcePage ?? "—"}</span></div><h2 className="bangla mt-5 text-xl font-bold leading-9">{question.question}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{question.options.map(option=>{const state=selected ? option.isCorrect ? "bg-mint" : selected===option.optionKey ? "bg-pink" : "bg-card" : "bg-card hover:bg-lemon"; return <button key={option.id} disabled={Boolean(selected)} onClick={()=>setAnswers(current=>({...current,[question.id]:option.optionKey}))} className={`bangla border-2 border-black p-4 text-left font-medium shadow-[3px_3px_0_#111] disabled:cursor-default ${state}`}><b className="mr-2">{option.optionKey}.</b>{option.optionText}</button>})}</div>{selected && <p className={`mt-5 font-bold ${selected===question.correctOption ? "text-emerald-700" : "text-[#d83c66]"}`}>{selected===question.correctOption ? "Correct — keep the momentum." : `Correct answer: ${question.correctOption}`}</p>}</article>})}</div><div className="flex flex-wrap items-center gap-4 border-t-2 border-black pt-6"><button onClick={()=>{setAnswers({});questions.refetch();}} className="brutal-button brutal-button-light px-4 py-3"><RotateCcw className="size-4"/> New set</button>{isAuthenticated ? <button disabled={answered!==questions.data.length||saveAttempt.isPending||saveAttempt.isSuccess} onClick={save} className="brutal-button px-4 py-3">{saveAttempt.isSuccess?"Score saved": "Save my score"}</button> : <button onClick={()=>startLogin()} className="brutal-button px-4 py-3">Sign in to save</button>}<span className="mono text-[11px]">{answered} OF {questions.data.length} ANSWERED</span><Brain className="ml-auto size-7"/></div></div>;
}
