import { ArrowRight, BookOpenCheck, Flame, LockKeyhole, Target } from "lucide-react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

export default function Progress() {
  const { isAuthenticated, loading } = useAuth();
  const overview = trpc.progress.overview.useQuery(undefined,{enabled:isAuthenticated});
  if (loading) return <div className="brutal-card p-8 font-bold">Checking your study space…</div>;
  if (!isAuthenticated) return <div className="mx-auto max-w-2xl py-12 text-center"><div className="brutal-card bg-pink p-8"><LockKeyhole className="mx-auto size-10"/><p className="eyebrow mt-5">Your private study layer</p><h1 className="page-title mt-4 text-5xl">KEEP YOUR<br/>MOMENTUM.</h1><p className="mx-auto mt-5 max-w-lg font-medium leading-7">Sign in to save real chapter study, flashcard reviews, and quiz attempts. Dontonyo never fills this page with made-up progress.</p><button onClick={()=>startLogin()} className="brutal-button mt-7 px-5 py-3">Sign in to begin <ArrowRight className="size-4"/></button></div></div>;
  const content=overview.data?.content??[]; const attempts=overview.data?.attempts??[]; const completed=content.filter(x=>x.status==="completed").length; const answered=content.reduce((n,x)=>n+x.correctCount+x.incorrectCount,0)+attempts.reduce((n,x)=>n+x.totalQuestions,0); const correct=content.reduce((n,x)=>n+x.correctCount,0)+attempts.reduce((n,x)=>n+x.correctAnswers,0); const accuracy=answered?Math.round(correct/answered*100):0; const days=overview.data?.daily.filter(x=>x.isComplete).length??0;
  return <div className="space-y-8"><header><p className="eyebrow">03 / Your study trail</p><h1 className="page-title mt-3">KEEP THE<br/><span className="text-[#ed4f77]">GOOD STUFF.</span></h1><p className="mt-4 max-w-xl font-medium leading-7 text-muted-foreground">A clean record of the work you actually complete — nothing invented, nothing noisy.</p></header><div className="grid gap-4 sm:grid-cols-3"><Metric icon={BookOpenCheck} label="completed" value={completed} color="bg-mint"/><Metric icon={Target} label="accuracy" value={`${accuracy}%`} color="bg-lemon"/><Metric icon={Flame} label="completed days" value={days} color="bg-pink"/></div><div className="brutal-card p-6"><p className="eyebrow">Next move</p><h2 className="section-title mt-2">{answered?"Keep your review loop moving.":"Your first answer starts the record."}</h2><p className="mt-4 max-w-2xl font-medium leading-7 text-muted-foreground">{answered?"Your saved results are private to your account. Return to practice for another source-linked question set.":"There is no activity to show yet. Browse a chapter or start a small practice set when you are ready."}</p><Link href="/practice" className="brutal-button mt-6 px-4 py-3">Open practice <ArrowRight className="size-4"/></Link></div></div>;
}
function Metric({icon:Icon,label,value,color}:{icon:typeof Target;label:string;value:string|number;color:string}){return <div className={`brutal-card-sm ${color} p-5`}><Icon className="size-5"/><p className="mt-8 text-4xl font-bold tracking-[-.08em]">{value}</p><p className="mono mt-2 text-[10px] uppercase">{label}</p></div>}
