import { ArrowRight, BookOpenCheck, Brain, CalendarDays, Layers3, LockKeyhole, Target } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

export default function Progress() {
  const { isAuthenticated, loading } = useAuth();
  const overview = trpc.study.progress.useQuery(undefined, { enabled: isAuthenticated });
  if (loading || overview.isLoading) return <div className="brutal-card p-8 font-bold">Checking your study trail…</div>;
  if (!isAuthenticated) return <div className="mx-auto max-w-2xl py-12 text-center"><div className="brutal-card bg-pink p-8"><LockKeyhole className="mx-auto size-10"/><p className="eyebrow mt-5">Your private study layer</p><h1 className="page-title mt-4 text-5xl">KEEP YOUR<br/>MOMENTUM.</h1><p className="mx-auto mt-5 max-w-lg font-medium leading-7">Create an account to save study passes, flashcard decisions, and real quiz results. Dontonyo never fills this page with invented activity.</p><Link href="/auth" className="brutal-button mt-7 px-5 py-3">Create or sign in <ArrowRight className="size-4"/></Link></div></div>;

  const data = overview.data ?? { topics: [], attempts: [], reviews: [], sessions: [], mistakes: [] };
  const answered = data.attempts.reduce((total, attempt) => total + attempt.totalQuestions, 0);
  const correct = data.attempts.reduce((total, attempt) => total + attempt.correctAnswers, 0);
  const accuracy = answered ? Math.round(correct / answered * 100) : 0;
  const completedTopics = data.topics.filter(topic => topic.status === "completed").length;
  const completedSessions = data.sessions.filter(session => session.completedAt).length;
  const mistakes = data.mistakes.length;
  const dueReviews = data.reviews.filter(review => new Date(review.dueAt).getTime() <= Date.now()).length;
  const activityDates = [...data.attempts.map(attempt => attempt.completedAt.slice(0, 10)), ...data.reviews.filter(review => review.lastReviewedAt).map(review => review.lastReviewedAt!.slice(0, 10)), ...data.sessions.filter(session => session.completedAt).map(session => session.completedAt!.slice(0, 10))];
  const activeDays = new Set(activityDates).size;
  const recentRun = consecutiveDayRun(activityDates);
  const practiceSignal = !data.attempts.length ? "No practice baseline yet" : data.attempts.length < 3 ? "Early practice baseline" : `Built from ${data.attempts.length} saved sets`;
  const latestAttempt = data.attempts[0];

  return <div className="space-y-8"><header className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow">Your real study trail</p><h1 className="page-title mt-3">KEEP THE<br/><span className="text-[#ed4f77]">GOOD STUFF.</span></h1><p className="mt-4 max-w-xl font-medium leading-7 text-muted-foreground">This is a record of what you actually studied, rated, and answered—not a motivational counter with fake numbers.</p></div><Link href="/dashboard" className="brutal-button brutal-button-light px-4 py-3">Open study dashboard <ArrowRight className="size-4"/></Link></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Target} label="practice accuracy" value={answered ? `${accuracy}%` : "—"} color="bg-lemon"/><Metric icon={Brain} label="saved answers" value={answered} color="bg-mint"/><Metric icon={BookOpenCheck} label="study sessions" value={completedSessions} color="bg-lilac"/><Metric icon={CalendarDays} label="recent run" value={`${recentRun} day${recentRun === 1 ? "" : "s"}`} color="bg-pink"/></section><section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="brutal-card bg-sky p-6 sm:p-8"><p className="eyebrow">Your next review</p><h2 className="section-title mt-3">{dueReviews ? `${dueReviews} CARD${dueReviews === 1 ? "" : "S"} READY NOW.` : "NO CARDS DUE RIGHT NOW."}</h2><p className="mt-4 max-w-xl font-medium leading-7">{dueReviews ? "Open the review queue before starting a fresh set. Short recall sessions are more useful than rereading everything." : "Your rated cards are scheduled ahead. If you want a fresh recall pass, open the source-card queue."}</p><Link href="/learn/flashcards" className="brutal-button mt-7 px-4 py-3">Review flashcards <Layers3 className="size-4"/></Link></div><div className="brutal-card-sm bg-card p-6"><p className="eyebrow">Practice signal</p><p className="mt-6 text-xl font-bold">{practiceSignal}</p><p className="mt-3 text-sm font-medium leading-6">{mistakes ? `${mistakes} saved response${mistakes === 1 ? " needs" : "s need"} another look. Use a new focused set to revisit those knowledge gaps.` : latestAttempt ? "No incorrect responses are stored across your saved attempts." : "Your first completed set will establish a real baseline."}</p><Link href="/practice" className="brutal-button mt-6 px-4 py-3">Practice now <ArrowRight className="size-4"/></Link></div></section>{!answered && !completedTopics && !data.reviews.length && !data.sessions.length ? <section className="brutal-card bg-mint p-6 sm:p-8"><p className="eyebrow">A blank record is honest</p><h2 className="section-title mt-3">START ONE<br/>SMALL SESSION.</h2><p className="mt-4 max-w-xl font-medium leading-7">Pick one topic, work through its source blocks, reveal the recall cues, then save the study pass when you can explain it.</p><Link href="/learn" className="brutal-button mt-7 px-4 py-3">Browse study topics <ArrowRight className="size-4"/></Link></section> : null}</div>;
}

function Metric({ icon: Icon, label, value, color }: { icon: typeof Target; label: string; value: string | number; color: string }) { return <div className={`brutal-card-sm ${color} p-5`}><Icon className="size-5"/><p className="mt-8 text-4xl font-bold tracking-[-.08em]">{value}</p><p className="mono mt-2 text-[10px] uppercase">{label}</p></div>; }

function consecutiveDayRun(values: string[]) { const days = Array.from(new Set(values)).sort((a, b) => b.localeCompare(a)); if (!days.length) return 0; let count = 1; for (let index = 1; index < days.length; index += 1) { const previous = new Date(`${days[index - 1]}T00:00:00Z`).getTime(); const current = new Date(`${days[index]}T00:00:00Z`).getTime(); if (previous - current === 86_400_000) count += 1; else break; } return count; }
