import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0534-0538";
const outputDir = path.join(root, "supabase", "batch-0534-0538");
export const BATCH_PAGES = [534, 535, 536, 537, 538];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0534-0538-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));
const refs = {
  indiaConstitution: "https://www.constitutionofindia.net/articles/394-commencement/",
  sikkim: "https://www.sikkim.gov.in/departments/sikkim-legislative-assembly",
  salam: "https://www.nobelprize.org/prizes/physics/1979/salam/biographical/",
  malalaFacts: "https://www.nobelprize.org/prizes/peace/2014/yousafzai/facts/",
  malalaBio: "https://www.nobelprize.org/prizes/peace/2014/yousafzai/biographical/",
};
const ctx = page => page <= 536
  ? { chapter: "india", chapterTitle: "ভারত", topic: page === 534 ? "india-reference-addenda" : page === 535 ? "india-past-exam-mcqs-du-bcs" : "india-past-exam-mcqs-other", topicTitle: page === 534 ? "ভারত — বিভিন্ন প্রসঙ্গ" : page === 535 ? "ভারত সম্পর্কিত বিগত বছরের প্রশ্ন — ঢাবি ও বিসিএস" : "ভারত সম্পর্কিত বিগত বছরের প্রশ্ন — অন্যান্য পরীক্ষা" }
  : { chapter: "pakistan", chapterTitle: "পাকিস্তান", topic: page === 537 ? "pakistan-overview-reference" : "pakistan-personalities-past-exam", topicTitle: page === 537 ? "পাকিস্তান — প্রদেশ, ইতিহাস ও তথ্যতরঙ্গ" : "পাকিস্তান — বিখ্যাত ব্যক্তিত্ব ও বিগত বছরের প্রশ্ন" };
const fact = (page, title, fact_text, status = "source_attributed", confidence = "medium", sources = []) => ({ source_page: page, title, fact_text, status, confidence, sources, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${fact_text}`) });
const note = (page, title, content, confidence = "medium") => ({ source_page: page, title, content, status: "source_attributed", confidence, sources: [], ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${content}`) });
const mcq = (page, number, question, options, correct, source, confidence = "high") => ({ source_page: page, number, question, options, correct, source, confidence, status: "source_attributed", sources: [], ...ctx(page), canonical_hash: hash(`mcq|${page}|${number}|${question}`) });

const facts = [
  fact(534, "হিমালয়ের অবস্থান (source statement)", "হিমালয় পর্বতমালা ভারত ও নেপালে অবস্থিত।", "source_attributed", "high"),
  fact(534, "পাটনার অবস্থান (source statement)", "পাটনা ভারতের বিহারে অবস্থিত।", "source_attributed", "high"),
  fact(534, "ভারতের জাতীয় বৃক্ষ (source statement)", "ভারতের জাতীয় বৃক্ষের নাম বট।", "source_attributed", "high"),
  fact(534, "আনন্দ ভবন (source statement)", "আনন্দ ভবন এলাহাবাদে অবস্থিত।", "source_attributed", "medium"),
  fact(534, "পোর্ট ব্লেয়ার (source statement)", "আন্দামান ও নিকোবর দ্বীপপুঞ্জের রাজধানী পোর্ট ব্লেয়ার।", "source_attributed", "high"),
  fact(534, "দেরাদুনের অবস্থান (source-printed conflicting statement)", "উৎসে দেরাদুন শহরকে ভারতের উত্তরপ্রদেশ রাজ্যে অবস্থিত বলা হয়েছে।", "conflicting", "medium"),
  fact(534, "অরুণাচল নিয়ে চীনের দাবি (source statement)", "উৎসে অরুণাচলকে ভারতের এমন প্রদেশ বলা হয়েছে যার একাংশকে চীন দাবি করে।", "source_attributed", "high"),
  fact(534, "সিয়াচেন (source statement)", "উৎসে বিতর্কিত সিয়াচেন জায়গাটিকে ভারত-পাকিস্তান সীমায় এবং সিয়াচেন হিমবাহকে কাশ্মীর (ভারত-পাকিস্তান) এলাকায় বলা হয়েছে।", "source_attributed", "high"),
  fact(534, "পশ্চিমবঙ্গের রাজধানী (source statement)", "পশ্চিমবঙ্গের রাজধানী কলকাতা।", "source_attributed", "high"),
  fact(534, "বিধানসভা (source statement)", "উৎসে ভারতের রাজ্যগুলোর আইনসভাকে বিধানসভা বলা হয়েছে।", "source_attributed", "high"),
  fact(534, "জাতীয় কোকিল (source statement)", "সরোজিনী নাইডু 'জাতীয় কোকিল' বা Nightingale of India নামে খ্যাত।", "source_attributed", "medium"),
  fact(534, "Grand Old Man of India (source statement)", "দাদাভাই নওরোজিকে Grand Old Man of India বলা হয়।", "source_attributed", "high"),
  fact(534, "ভারতের সংবিধানের কার্যকারিতা", "ভারতের সংবিধান ২৬ জানুয়ারি ১৯৫০ সালে কার্যকর হয়; ভারত প্রজাতন্ত্র দিবসও ২৬ জানুয়ারি।", "verified", "high", [refs.indiaConstitution]),
  fact(535, "সিকিমের ভারতভুক্তি", "ভারত কর্তৃক সিকিম সংযুক্ত হয় ১৯৭৫ সালে।", "verified", "high", [refs.sikkim]),
  fact(537, "পাকিস্তানের জন্ম (source statement)", "ব্রিটিশ ভারত বিভক্তির মাধ্যমে ১৪ আগস্ট ১৯৪৭ সালে পাকিস্তান রাষ্ট্রের জন্ম হয়।", "source_attributed", "high"),
  fact(537, "আল্লামা ইকবালের প্রস্তাব (source statement)", "উৎসে আল্লামা ইকবাল ১৯৩১ সালে উত্তর-পশ্চিম ভারতের মুসলিম-প্রধান অঞ্চল নিয়ে পৃথক রাষ্ট্রের প্রস্তাব দেন।", "source_attributed", "medium"),
  fact(537, "পাকিস্তানের প্রথম সাধারণ নির্বাচন (source statement)", "পাকিস্তানের সর্বপ্রথম সাধারণ নির্বাচন ১৯৭০ সালে অনুষ্ঠিত হয়।", "source_attributed", "high"),
  fact(537, "পাকিস্তানের প্রথম প্রধানমন্ত্রী (source statement)", "পাকিস্তানের প্রথম প্রধানমন্ত্রী লিয়াকত আলী খান।", "source_attributed", "high"),
  fact(537, "পাকিস্তানের প্রথম প্রেসিডেন্ট (source statement)", "পাকিস্তানের প্রথম প্রেসিডেন্ট ইস্কান্দার মির্জা।", "source_attributed", "high"),
  fact(537, "পাকিস্তানের প্রথম পারমাণবিক বিস্ফোরণ (source statement)", "উৎসে পাকিস্তানের প্রথম পারমাণবিক বিস্ফোরণের বছর ১৯৯৮ বলা হয়েছে।", "source_attributed", "high"),
  fact(537, "আবদুস সালামের নোবেল", "আবদুস সালাম ১৯৭৯ সালে পদার্থবিজ্ঞানে নোবেল পুরস্কার পান।", "verified", "high", [refs.salam]),
  fact(537, "In the Line of Fire (source statement)", "In the Line of Fire বইটির লেখক পারভেজ মোশাররফ।", "source_attributed", "high"),
  fact(538, "মোহাম্মদ আলী জিন্নাহ (source statement)", "উৎসে মোহাম্মদ আলী জিন্নাহকে পাকিস্তানের প্রতিষ্ঠাতা, জাতির জনক ও প্রথম গভর্নর জেনারেল বলা হয়েছে; উপাধি কায়েদে আজম।", "source_attributed", "medium"),
  fact(538, "আল্লামা ইকবাল (source statement)", "উৎসে আল্লামা ইকবালকে মুসলিম কবি, দার্শনিক, রাজনীতিবিদ এবং পাকিস্তানের আধ্যাত্মিকতার জনক বলা হয়েছে।", "source_attributed", "medium"),
  fact(538, "বেনজির ভুট্টো (source statement)", "উৎসে বেনজির ভুট্টোকে পাকিস্তানের প্রধানমন্ত্রী, জুলফিকার আলী ভুট্টোর কন্যা এবং মুসলিম বিশ্বের প্রথম নারী প্রধানমন্ত্রী বলা হয়েছে।", "source_attributed", "high"),
  fact(538, "Malala shooting and Nobel", "মালালা ইউসুফজাই ২০১২ সালে তালেবানের গুলিতে আহত হন এবং ২০১৪ সালে নোবেল শান্তি পুরস্কার পান।", "verified", "high", [refs.malalaFacts]),
  fact(538, "Malala youngest laureate", "মালালা ইউসুফজাই ১৭ বছর বয়সে নোবেল শান্তি পুরস্কার পেয়ে সবচেয়ে কমবয়সী পুরস্কারপ্রাপক হন।", "verified", "high", [refs.malalaBio]),
  fact(538, "I Am Malala (source statement)", "উৎসে মালালা ইউসুফজাইয়ের আত্মজীবনীমূলক বিখ্যাত গ্রন্থ I Am Malala বলা হয়েছে।", "source_attributed", "high"),
];

const notes = [
  note(534, "ভারত — পর্যালোচিত বিভিন্ন প্রসঙ্গ", "উৎসে স্পষ্ট পাঠ | হিমালয় ভারত-নেপালে; পাটনা বিহারে; জাতীয় বৃক্ষ বট; আনন্দ ভবন এলাহাবাদে; পোর্ট ব্লেয়ার আন্দামান ও নিকোবরের রাজধানী; কলকাতা পশ্চিমবঙ্গের রাজধানী; রাজ্য আইনসভা বিধানসভা।\nসতর্কতা | দেরাদুনকে উত্তরপ্রদেশে বলা উৎস-বিবৃতি বর্তমান প্রশাসনিক বাস্তবতার সঙ্গে সাংঘর্ষিক; অরুণাচল ও সিয়াচেন ভূখণ্ডসংক্রান্ত উৎস-বক্তব্য সময়-সংবেদী।\nঅমীমাংসিত | উপরের তালিকার ঝাপসা/গার্বলড লাইন থেকে কোনো স্বাধীন fact তৈরি করা হয়নি।", "medium"),
  note(537, "পাকিস্তানের প্রদেশ ও রাজধানী — source table", "উৎসে প্রদত্ত অঞ্চল/রাজধানী | সিন্ধু—করাচি; বেলুচিস্তান—কোয়েটা; পাঞ্জাব—লাহোর; খায়বার পাখতুনখোয়া—পেশোয়ার; গিলগিত-বালতিস্তান—গিলগিত (সর্বশেষ প্রদেশ)।\nসতর্কতা | অঞ্চল/প্রদেশের মর্যাদা ও প্রশাসনিক বর্ণনা সময়-সংবেদী উৎস-তথ্য।", "medium"),
  note(537, "এক নজরে পাকিস্তান রাষ্ট্র — source timeline", "উৎসে প্রদত্ত ক্রম | স্বাধীনতা ১৪ আগস্ট ১৯৪৭; সংবিধান ১৯৫৬; মৌলিক গণতন্ত্র ১৯৬২; ইসলামী প্রজাতন্ত্র ২৩ মার্চ ১৯৫৬; শরীয়া আইন ১৯৭৯ [visually corrected]; প্রথম পারমাণবিক বিস্ফোরণ ১৯৯৮।\nসতর্কতা | রাজনৈতিক/সাংবিধানিক timeline source-attributed ও time-sensitive।", "medium"),
  note(538, "পাকিস্তানের বিখ্যাত ব্যক্তিত্ব — source panels", "ব্যক্তি | উৎসে প্রদত্ত তথ্য\nমোহাম্মদ আলী জিন্নাহ | প্রতিষ্ঠাতা, জাতির জনক, প্রথম গভর্নর জেনারেল, কায়েদে আজম; 'বি-জাতি তত্ত্ব' ১৯৩৯ [low-confidence source reading]\nআল্লামা ইকবাল | কবি, দার্শনিক, রাজনীতিবিদ; উল্লেখযোগ্য কাব্যগ্রন্থের উৎস বানান অপরিবর্তিত রাখা হয়েছে\nবেনজির ভুট্টো | প্রধানমন্ত্রী; Daughter of the East; Daughter of Destiny\nমালালা ইউসুফজাই | নারীশিক্ষা-আন্দোলন, ২০১২ গুলিবিদ্ধ, ২০১৪ Nobel Peace Prize, I Am Malala\nসতর্কতা | রাজনৈতিক title/date এবং source transliterations অপরিবর্তিতভাবে source-attributed।", "medium"),
];

const mcqs = [
  mcq(535,"01","সম্প্রতি ভারতে স্থাপিত সর্দার বল্লাভাই প্যাটেলের ভাস্করের রাষ্ট্রীয় নাম কী?",["স্ট্যাচু অব ইউনিটি","স্ট্যাচু অব ফ্রিডম","স্ট্যাচু অব লিবার্টি","স্ট্যাচু অব ডেমোক্রেসি"],"ক","DU ঘ ১৮-১৯","medium"),
  mcq(535,"02","ভারতীয় কাশ্মীরের কোন অংশে সংখ্যাগরিষ্ঠ?",["লাদাখ","জম্মু","শ্রীনগর","আকসাই চিন"],"ক","DU ঘ ১২-১৩","low"),
  mcq(535,"03","ভারতের বর্তমান জোট সরকারের প্রাতিষ্ঠানিক নাম-",["ভারতীয় কংগ্রেস","জাতীয় গণতান্ত্রিক জোট","ভারতীয় জনতা পার্টি","একবদ্ধ প্রগতিশীল জোট"],"গ","DU ঘ ০৫-০৬"),
  mcq(535,"04","ভারতের কোন অঞ্চলের সাতটি প্রদেশকে একত্রে 'সেভেন সিস্টার্স' বলা হয়?",["উত্তরাঞ্চল","উত্তর-পূবাঞ্চল","উত্তর-পূর্বাঞ্চল","পূর্ববঙ্গ"],"গ","DU ঘ ০৩-০৪","medium"),
  mcq(535,"05","ঐতিহাসিক 'বাবরি মসজিদ' কোথায় অবস্থিত?",["দিল্লি","বেনারস","অযোধ্যা","লখনৌ"],"গ","DU ঘ ০০-০১"),
  mcq(535,"06","ভারতের বর্তমান সংসদে কোন রাজনৈতিক দলের সবচেয়ে বেশি সদস্য রয়েছে?",["জাতীয় কংগ্রেস","সিপিএম","জনতাদল","বিজেপি"],"ঘ","DU ঘ ৯৬-৯৭","low"),
  mcq(535,"07","ভারতের জাতীয় পাখি-",["রাজহংস","ময়ূর","ঈগল","গরু"],"খ","DU ঘ ১৪-১৫"),
  mcq(535,"08","'দেশ ভাল হয় যদি দেশের বিশ্ববিদ্যালয়গুলো ভাল হয়' বলেছিলেন-",["আব্রাহাম লিংকন","নিউটন","বট্রুট রাসেল","নেহেরু"],"ঘ","DU ঘ ১০-১১","low"),
  mcq(535,"09","তেলেঙ্গানা কোন রাজ্যের অংশ ছিল?",["অন্ধ্র প্রদেশ","তামিলনাডু","কট্টিক","উড়িষ্যা"],"ক","DU ঘ ১৪-১৫","low"),
  mcq(535,"10","ভারত প্রজাতন্ত্র ঘোষণা হয়-",["১৯৪৭ সালে","১৯৫০ সালে","১৯৫১ সালে","১৯৫২ সালে"],"খ","DU ঘ ০০-০১"),
  mcq(535,"11","সিয়াচেন হিমবাহ কোন দুইটি দেশের মধ্যে অবস্থিত?",["ভারত ও চিন","নেপাল ও চিন","পাকিস্তান ও চিন","ভারত ও পাকিস্তান"],"ঘ","46 BCS"),
  mcq(535,"12","ভারত কর্তৃক সিকিম সংযুক্ত হয়-",["১৯৭০","১৯৭২","১৯৭৫","১৯৭৭"],"গ","45 BCS"),
  mcq(535,"13","চিন-ভারত যুদ্ধ কত সালে সংঘটিত হয়?",["১৯৫৯","১৯৬০","১৯৬২","১৯৬৩"],"গ","45 BCS"),
  mcq(535,"14","ভারতের কোন দিনটি সিভিল সার্ভিস দিবস হিসেবে পালিত হয়?",["২১ এপ্রিল","২ অক্টোবর","২৬ জানুয়ারি","১০ মে"],"ক","42 BCS"),
  mcq(535,"15","ব্রিটিশ ভারতের রাজধানী কলকাতা থেকে দিল্লীতে স্থানান্তরিত হয় কত সালে?",["১৯১২ সালে","১৯১৩ সালে","১৯১৪ সালে","১৯১৫ সালে"],"ক","41 BCS"),
  mcq(535,"16","কালাপানি কোন দুই রাষ্ট্রের মধ্যে অবস্থিত ভূখণ্ড?",["ভারত ও নেপাল","পাকিস্তান ও চীন","ভুটান ও ভারত","বাংলাদেশ ও ভারত"],"ক","37 BCS","medium"),
  mcq(536,"17","রাজীব গান্ধীকে হত্যার জন্য বোমা বহনকারী আত্মঘাতী মহিলার নাম কী?",["নন্দিনী","নাথু","খানু","আনু"],"গ","14 BCS","low"),
  mcq(536,"18","ভারতের 'সেভেন সিস্টার্স' রাজ্যসমূহের অন্তর্ভুক্ত নয়-",["কেরালা","মনিপুর","ত্রিপুরা","মিজোরাম"],"ক","26 BCS"),
  mcq(536,"19","ভারতের কোন রাজ্যের রাজধানী ইম্ফল?",["মিজোরাম","অরুণাচল","মণিপুর","মেঘালয়"],"গ","26 BCS"),
  mcq(536,"20","ব্ল্যাক ক্যাট কোন দেশের কমান্ডো বাহিনী?",["নেপাল","ভারত","মায়ানমার","ইরান"],"খ","বাতিলকৃত 24 BCS / রবি-ব্যবস্থাপনা ০৭-০৮"),
  mcq(536,"21","ভারতের প্রথম লোকসভা গঠিত হয় কখন?",["১৯৪৭ সালে","১৯৪৯ সালে","১৯৫০ সালে","১৯৫২ সালে"],"ঘ","দুর্নীতি দমন পরিষদ ০৪"),
  mcq(536,"22","পৃথিবীর দ্বিতীয় বৃহত্তম জনবহুল দেশ-",["চীন","রাশিয়া","মার্কিন যুক্তরাষ্ট্র","ভারত"],"ঘ","প্রাথমিক বিদ্যালয় প্রধান শিক্ষক ১২","medium"),
  mcq(536,"23","জাতির জনক হিসেবে পরিচিত, কিন্তু কখনো রাষ্ট্রীয় পদে অধিষ্ঠিত হননি-",["বঙ্গবন্ধু শেখ মুজিবুর রহমান","মোহাম্মদ আলী জিন্নাহ","নেলসন ম্যান্ডেলা","মহাত্মা গান্ধী"],"ঘ","প্রতীক্ষ মন্ত্রণালয় ৯১"),
  mcq(536,"24","মহাত্মা গান্ধী দক্ষিণ আফ্রিকার কোন পত্রিকাটি সম্পাদনা করেছিলেন?",["ইন্ডিয়ান অপিনিয়ন","দি হেরাল্ড","দি টাইমস","দি কন্‌সারভেটর"],"ক","উপজেলা সমাজসেবা অফিসার ০৬","medium"),
  mcq(536,"25","মহাত্মা গান্ধীর রাজনৈতিক নেতৃত্বের উত্থান ঘটেছে যে দেশে-",["বার্মা","ব্রাজিল","ভারত","দক্ষিণ আফ্রিকা"],"ঘ","রবি-ইসলামী ইতিহাস ০৭-০৮"),
  mcq(536,"28","ঐতিহাসিক বাবরি মসজিদ ভারতের কোন প্রদেশের অন্তর্গত ছিল?",["অন্ধ্র","হরিয়ানা","রাজস্থান","উত্তর প্রদেশ"],"ঘ","দুদক উপপরিচালক পরিচিতক ১০"),
  mcq(536,"29","মাদার তেরেসা পথের অবসরপ্রাপ্ত শিশুদের জন্য কোথায় প্রথম আশ্রম খুলেন?",["কলকাতা","কাবুল","বৈরুত","বাগদাদ"],"ক","DC ০৩-০৪"),
  mcq(536,"30","Who used to be called a Living Saint?",["Pope John Paul","Desmond Tutu","Mother Teresa","Florence Nightingale"],"গ","Basic Bank Officer ০২"),
  mcq(536,"31","সাউথ এশিয়ান বিশ্ববিদ্যালয় কোথায় অবস্থিত?",["বাংলাদেশ","ভারত","নেপাল","ভুটান"],"খ","হাজী দানেশ ১৩-১৪"),
  mcq(536,"32","ভারতের কোন রাজ্যের রাজধানী ইম্ফল?",["মিজোরাম","অরুণাচল","মণিপুর","মেঘালয়"],"গ","26 BCS"),
  mcq(538,"01","মুসলিম বিশ্বের প্রথম নারী প্রধানমন্ত্রী কে ছিলেন?",["বেগম খালেদা জিয়া","বেনজির ভুট্টো","মেহবুতি সুকরপুত্রী","শিরিন এবাদি"],"খ","DU ০১-০৫","medium"),
  mcq(538,"02","'In the line of Fire' বইটির লেখক কে?",["পারভেজ মোশাররফ","হিলারী ক্লিনটন","মাহাথির মোহাম্মদ","এদের কেউ নন"],"ক","DU ০৩-০৭"),
  mcq(538,"03","মুসলিম বিশ্বের প্রথম মহিলা প্রধানমন্ত্রী কে?",["হাসান আশরাফী","বেনজির ভুট্টো","খালেদা জিয়া","ফাতেমা জিন্নাহ"],"খ","পাঁচ নিবারণ অফিসার ০৪","medium"),
  mcq(538,"04","Daughter of the East বলা হয় কাকে?",["ইন্দিরা গান্ধী","অং সান সুচি","বনলনা বোকে","বেনজির ভুট্টো"],"ঘ","রবি ০৭-০৮, পরিবার পরিকল্পনা অধিদপ্তর ১২","medium"),
  mcq(538,"05","জেনারেল পারভেজ মোশাররফ কবে ক্ষমতায় আসেন?",["১৯৯৮","১৯৯৯","২০০০","২০০১"],"খ","সেনাপ্রধান মন্ত্রণালয়ের প্রশাসনিক কর্মকর্তা ০৭"),
  mcq(538,"06","'ডটার অব দ্যা ইস্ট' বইটি লিখেছেন-",["গোল্ডা মেয়ার","বেনজির ভুট্টো","ইন্দিরা গান্ধী","শ্রীমন্ত কুমার"],"খ","DU ০৮-০৯","medium"),
];

const tags = [
  ["india", "India", "domain", "Source-derived India reference material."], ["pakistan", "Pakistan", "domain", "Source-derived Pakistan reference material."], ["biography", "Biography", "content_type", "Source-derived biography."], ["reference-table", "Reference table", "content_type", "Structured source reference table."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with a printed source label and answer key."], ["answer-key", "Answer key", "content_type", "Correct option from the printed source answer key."], ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Claim directly corroborated by cited external evidence."], ["conflicting", "Conflicting source claim", "quality", "Source wording preserved while evidence records a discrepancy."], ["time-sensitive", "Time-sensitive reference", "quality", "Political, territorial, constitutional, administrative, or demographic material."], ["low-confidence", "Low-confidence source reading", "quality", "Source scan or reading is incomplete or uncertain."], ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed exam label."], ["bcs", "BCS", "exam_source", "Bangladesh Civil Service printed exam label."], ["other-recruitment", "Other examination", "exam_source", "Other university, bank, or recruitment examination label."],
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : source.includes("BCS") ? ["Bangladesh Civil Service", null, "competitive", "bcs"] : ["Other university and recruitment examination", null, "competitive", "other-recruitment"];
const quality = record => record.status === "verified" ? "externally-verified" : record.status === "conflicting" ? "conflicting" : "source-attributed";
const recordId = (kind, key) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(key)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const chapters = [[64, "পাকিস্তান", "pakistan", "Source-preserved Pakistan history, reference material, biographies, and past-exam questions.", 537]];
  const topics = [["india", "ভারত — বিভিন্ন প্রসঙ্গ", "india-reference-addenda", 534, 6], ["india", "ভারত সম্পর্কিত বিগত বছরের প্রশ্ন — ঢাবি ও বিসিএস", "india-past-exam-mcqs-du-bcs", 535, 7], ["india", "ভারত সম্পর্কিত বিগত বছরের প্রশ্ন — অন্যান্য পরীক্ষা", "india-past-exam-mcqs-other", 536, 8], ["pakistan", "পাকিস্তান — প্রদেশ, ইতিহাস ও তথ্যতরঙ্গ", "pakistan-overview-reference", 537, 1], ["pakistan", "পাকিস্তান — বিখ্যাত ব্যক্তিত্ব ও বিগত বছরের প্রশ্ন", "pakistan-personalities-past-exam", 538, 2]];
  const checks = [...facts.map(record => ({ kind: "fact", claim: record.fact_text, ...record })), ...notes.map(record => ({ kind: "note", claim: record.content, ...record })), ...mcqs.map(record => ({ kind: "mcq", claim: `${record.question} — printed answer: ${record.correct}`, ...record }))];
  const audit = { batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION, source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })), generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length, verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: checks.filter(row => row.status === "conflicting").length, source_attributed: checks.filter(row => row.status === "source_attributed").length }, source_anomalies: ["Physical PDF pages 534–538 retain book footers 477–481.", "Page 534 retains Dehradun-in-Uttar-Pradesh as an explicitly conflicting source statement and does not transform blurred lines into facts.", "Pages 535, 536, and 538 retain only MCQs whose question and all four visually reviewed options are available; page 536 questions 26 and 27 are withheld because an option is unreadable.", "Page 535 answer key Q12 is corrected to গ from the reviewed visual key, rather than the OCR artifact's conflicting খ.", "Page 536 answer key Q31 is corrected to খ from the reviewed visual key, rather than the artifact's conflicting ঘ.", "Page 537 preserves reviewed 1931 Iqbal and 1979 Sharia readings; its two unresolved lines are not converted to facts.", "Page 538 preserves uncertain source spellings and the low-confidence 'বি-জাতি তত্ত্ব' line without normalizing it."], quality_gates: ["Exactly physical pages 534–538 are imported.", "All 25 ordered visual-review tiles were reviewed.", "Facts, notes, MCQs, options, answer keys, and exam metadata remain relationally distinct.", "Upserts are idempotent by canonical hash, source page, and stable derived-record keys."] };
  const chapterSql = `INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${values(chapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved material with explicit verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 534: 477, 535: 478, 536: 479, 537: 480, 538: 481 };
  const pagesSql = pages.map(page => { const context = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, accepted_content_tags: page.review.accepted_content_tags, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: "/home/ubuntu/dontonyo/reports/batch-0534-0538_visual_review.md", external_verification_report: "/home/ubuntu/dontonyo/reports/batch-0534-0538_external_verification.md", page_number_mismatch: "Physical PDF page and printed source footer are separately preserved." }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},${q([535,536,538].includes(page.source_page) ? "mcq" : "educational")}::page_kind,${q(page.review.verified_transcript)},${q(context.chapterTitle)},${q(context.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered tile review, source-preserved anomalies, and explicit verification statuses.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page,row.chapter,row.topic,row.title,row.fact_text,row.status,row.confidence,row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct external corroboration is recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'The printed source wording is preserved and a discrepancy is recorded in the verification ledger.' ELSE 'Source-attributed material is retained with visual review and no silent factual update.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page,row.chapter,row.topic,row.title,row.content,row.confidence,row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name,institution,type,normalized] = exam(row.source); const keys = ["ক","খ","গ","ঘ"]; const optionSql = row.options.map((option, index) => `INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index + 1},${keys[index] === row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalized)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalized)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},'Printed answer key retained as source-attributed material; all source options and examination label were visually validated.',${row.source_page},'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${optionSql} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalized)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row => `(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(row => [row.chapter,quality(row),"time-sensitive",...(row.confidence === "low" ? ["low-confidence"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0534-0538-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(row => [row.chapter,"reference-table","source-attributed","time-sensitive"].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0534-0538-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${mcqs.map(row => [row.chapter,"past-exam-mcq","answer-key",exam(row.source)[3],"source-attributed",...(row.confidence === "low" ? ["low-confidence"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0534-0538-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
  const verificationSql = checks.map(row => `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${recordId(row.kind,row.canonical_hash)},${q(row.claim)},NULL,${q(row.status)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(row.status === "verified" ? "Direct external corroboration is listed in the batch verification ledger." : row.status === "conflicting" ? "Source wording is preserved while the verification ledger records a discrepancy." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${recordId(row.kind,row.canonical_hash)} AND v.claim_text=${q(row.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0534-0538:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 534 AND 538 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0534-0538:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0534-0538:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 534 AND 538 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0534-0538:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0534-0538:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page IN (535,536,538) AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0534-0538:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked India/Pakistan GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 534 AND 538 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 534 AND 538 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page IN (535,536,538) AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0534_0538.mjs. Source pages 534–538 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page => page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pagesSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) { const { sql, audit } = await buildBatch(); await fs.mkdir(outputDir, { recursive: true }); await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql); await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2)); await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql})); console.log(JSON.stringify({outputDir,...audit},null,2)); }
