import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0549-0553";
const outputDir = path.join(root, "supabase", "batch-0549-0553");
export const BATCH_PAGES = [549, 550, 551, 552, 553];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0549-0553-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));

const refs = {
  indonesia: "https://history.state.gov/historicaldocuments/frus1955-57v22/d157",
  malaysia: "https://2001-2009.state.gov/outofdate/bgn/m/26156.htm",
  unrwa: "https://www.unrwa.org/what-mandate-unrwa-0",
  palestineUN: "https://www.un.org/unispal/document/auto-insert-187149/",
};

const ctx = page => {
  if (page === 549) return { chapter: "myanmar-rohingya-reference", chapterTitle: "মিয়ানমার ও রোহিঙ্গা সমস্যা", topic: "myanmar-rohingya-past-questions", topicTitle: "মিয়ানমার ও রোহিঙ্গা — বিগত প্রশ্ন", domain: "myanmar" };
  if ([550, 551].includes(page)) return { chapter: "southeast-asia-country-profiles", chapterTitle: "দক্ষিণ-পূর্ব এশিয়ার দেশসমূহ", topic: "indonesia-reference", topicTitle: "ইন্দোনেশিয়া", domain: "indonesia" };
  if (page === 552) return { chapter: "southeast-asia-country-profiles", chapterTitle: "দক্ষিণ-পূর্ব এশিয়ার দেশসমূহ", topic: "malaysia-reference", topicTitle: "মালয়েশিয়া", domain: "malaysia" };
  return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "palestine-unrwa-reference", topicTitle: "ফিলিস্তীন ও UNRWA", domain: "palestine" };
};
const fact = (page, title, body, status = "source_attributed", confidence = "medium", sources = [], domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, fact_text: body, status, confidence, sources, domain, timeSensitive, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${body}`) });
const note = (page, title, body, confidence = "medium", domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, content: body, status: "source_attributed", confidence, sources: [], domain, timeSensitive, ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${body}`) });
const mcq = (page, number, question, options, correct, source, confidence = "high", domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, number, question, options, correct, source, confidence, status: "source_attributed", sources: [], domain, timeSensitive, ...ctx(page), canonical_hash: hash(`mcq|${page}|${number}|${question}`) });

const facts = [
  fact(550, "ইন্দোনেশিয়ার ১৯৪৫ স্বাধীনতা-বক্তব্যের উৎস-সতর্কতা", "উৎসে ইন্দোনেশিয়া ১৯৪৫ সালে নেদারল্যান্ডস থেকে স্বাধীনতা লাভ করে বলা হয়েছে; U.S. Office of the Historian ১৭ আগস্ট ১৯৪৫-এর ঘোষণা এবং ২৭ ডিসেম্বর ১৯৪৯-এর চূড়ান্ত অর্জনের মধ্যে পার্থক্য করে।", "conflicting", "high", [refs.indonesia], "indonesia", true),
  fact(550, "সুকার্নো সম্পর্কে উৎস-বক্তব্য", "উৎসে ড. আহমদ সুকার্নোকে ইন্দোনেশিয়ার স্বাধীনতা সংগ্রামের নেতা ও প্রথম প্রেসিডেন্ট বলা হয়েছে।", "source_attributed", "high", [], "indonesia", true),
  fact(550, "সুহার্তো সম্পর্কে উৎস-বক্তব্য", "উৎসে ১৯৬৬ সালে জেনারেল সুহার্তো সুকার্নোকে ক্ষমতাচ্যুত করে ক্ষমতা দখল করেন বলে উল্লেখ আছে।", "source_attributed", "medium", [], "indonesia", true),
  fact(550, "বোর্নিও ও কালিমানতান (source statement)", "উৎসে বোর্নিওকে এশিয়ার বৃহত্তম দ্বীপ এবং দ্বীপটির ইন্দোনেশীয় অংশকে কালিমানতান বলা হয়েছে।", "source_attributed", "medium", [], "indonesia"),
  fact(550, "বালি সম্পর্কে উৎস-বক্তব্য", "উৎসে বালিকে ইন্দোনেশিয়ার পর্যটনের জন্য বিখ্যাত দ্বীপ বলা হয়েছে।", "source_attributed", "high", [], "indonesia"),
  fact(550, "গারুদা সম্পর্কে উৎস-বক্তব্য", "উৎসে ইন্দোনেশিয়ার বিমান সংস্থার নাম গারুদা বলা হয়েছে।", "source_attributed", "high", [], "indonesia", true),
  fact(550, "পশ্চিম তিমুর সম্পর্কে উৎস-বক্তব্য", "উৎসে পশ্চিম তিমুরকে ইন্দোনেশিয়ার একটি অঙ্গরাজ্য/অংশ হিসেবে উল্লেখ করা হয়েছে।", "source_attributed", "medium", [], "indonesia", true),
  fact(551, "জাভা ও জাকার্তা (source statement)", "উৎসের দ্বীপ-তালিকায় জাভা দ্বীপে ইন্দোনেশিয়ার রাজধানী জাকার্তা অবস্থিত বলা হয়েছে।", "source_attributed", "high", [], "indonesia", true),
  fact(551, "বোর্নিও সম্পর্কে উৎস-তালিকা", "উৎসের দ্বীপ-তালিকায় বোর্নিওকে এশিয়ার বৃহত্তম ও বিশ্বের তৃতীয় বৃহত্তম দ্বীপ এবং ইন্দোনেশীয় অংশকে কালিমানতান বলা হয়েছে।", "source_attributed", "high", [], "indonesia"),
  fact(551, "তিমুর-লেস্তে (source statement)", "উৎসের মানচিত্র ও তালিকায় তিমুর-লেস্তেকে একটি স্বাধীন দেশ বলা হয়েছে।", "source_attributed", "high", [], "timor-leste", true),
  fact(552, "মালয়েশিয়ার ১৯৫৭ স্বাধীনতা-বক্তব্যের উৎস-সতর্কতা", "উৎসে মালয়েশিয়া ১৯৫৭ সালে ব্রিটিশ শাসন থেকে স্বাধীনতা লাভ করে বলা হয়েছে; State Department উৎসে ১৯৫৭ সালে মালয়া স্বাধীন এবং ১৯৬৩ সালে মালয়েশিয়া গঠনের পার্থক্য উল্লেখ আছে।", "conflicting", "high", [refs.malaysia], "malaysia", true),
  fact(552, "মালয়েশিয়ার সাংবিধানিক রাজতন্ত্র", "মালয়েশিয়া একটি সাংবিধানিক রাজতন্ত্র; উৎসে রাষ্ট্রপ্রধান ও সরকারপ্রধানের পৃথক ভূমিকার কথাও আছে।", "verified", "high", [refs.malaysia], "malaysia", true),
  fact(552, "টেংকু আবদুল রাহমান (source statement)", "উৎসে টেংকু আবদুল রাহমানকে মালয়েশিয়ার স্বাধীনতার জনক ও প্রথম প্রধানমন্ত্রী বলা হয়েছে।", "source_attributed", "high", [], "malaysia", true),
  fact(552, "পেট্রোনাস টুইন টাওয়ার (source statement)", "উৎসে পেট্রোনাস টুইন টাওয়ারকে মালয়েশিয়ার সর্বোচ্চ ভবন বলা হয়েছে।", "source_attributed", "high", [], "malaysia", true),
  fact(552, "মাহাথির মোহাম্মদ (source statement)", "উৎসে ড. মাহাথির মোহাম্মদকে আধুনিক মালয়েশিয়ার স্থপতি ও প্রধানমন্ত্রী বলা হয়েছে।", "source_attributed", "medium", [], "malaysia", true),
  fact(552, "MM2H (source statement)", "উৎসে Malaysia My Second Home (MM2H) প্রোগ্রাম চালুর সঙ্গে ড. মাহাথির মোহাম্মদের নাম যুক্ত করা হয়েছে।", "source_attributed", "medium", [], "malaysia", true),
  fact(553, "State of Palestine proclamation (1988)", "জাতিসংঘের নথিতে ১৫ নভেম্বর ১৯৮৮ সালের Palestinian National Council-এর State of Palestine proclamation স্বীকৃতির উল্লেখ আছে।", "verified", "high", [refs.palestineUN], "palestine", true),
  fact(553, "প্যালেস্টাইনের UN non-member observer State status (2012)", "জাতিসংঘ সাধারণ পরিষদের resolution 67/19, ২৯ নভেম্বর ২০১২, প্যালেস্টাইনকে non-member observer State status প্রদান করে।", "verified", "high", [refs.palestineUN], "palestine", true),
  fact(553, "UNRWA-এর ম্যান্ডেট ও গঠন", "UNRWA ৮ ডিসেম্বর ১৯৪৯ সালের General Assembly resolution 302 (IV)-এ প্রতিষ্ঠিত হয় এবং Palestine refugees-দের সহায়তা ও সুরক্ষা দেওয়ার ম্যান্ডেট ধারণ করে।", "verified", "high", [refs.unrwa], "unrwa", true),
  fact(553, "WAFA সম্পর্কে উৎস-বক্তব্য", "উৎসে ফিলিস্তিনের জাতীয় বার্তা সংস্থার নাম WAFA বলা হয়েছে।", "source_attributed", "high", [], "palestine", true),
];

const notes = [
  note(549, "মিয়ানমার ও রোহিঙ্গা — বিগত প্রশ্ন", "উৎসে University of Dhaka, BCS, এবং অন্যান্য পরীক্ষার মিয়ানমার/রোহিঙ্গা বিষয়ক প্রশ্ন আছে।\nসতর্কতা | চারটি প্রশ্ন (Q1, Q5, Q6, Q7) অস্পষ্ট বিকল্প, ভুল/বিরোধী premise বা উৎস-সময়ের রাজনৈতিক wording-এর কারণে withheld করা হয়েছে।", "medium", "myanmar", true),
  note(550, "ইন্দোনেশিয়া — উৎস-সময়ভিত্তিক রেফারেন্স", "উৎসে ইন্দোনেশিয়ার স্বাধীনতা, সুকার্নো, সুহার্তো, Aceh, বোর্নিও/কালিমানতান, বালি, গারুদা ও পশ্চিম তিমুরের তথ্য আছে।\nসতর্কতা | ১৯৪৫ দাবিটি ঘোষণা ও পরবর্তী চূড়ান্ত স্বীকৃতির পার্থক্য ছাড়া উপস্থাপিত; অস্পষ্ট Aceh/Free Aceh, Megawati, nickname ও Borobudur লাইন স্বাধীন fact হিসেবে আমদানি করা হয়নি।", "medium", "indonesia", true),
  note(551, "ইন্দোনেশিয়ার দ্বীপসমূহ — উৎস-ম্যাপ ও টেবিল", "উৎসে সুমাত্রা, জাভা, বোর্নিও, বালি, পশ্চিম তিমুর ও পশ্চিম পাপুয়া নিয়ে একটি মানচিত্র ও টেবিল আছে।\nসতর্কতা | সুমাত্রা সারির অংশ, পশ্চিম তিমুরের parenthetical শব্দ, এবং একটি MCQ বিকল্প অস্পষ্ট; কেবল পরিষ্কার সারাংশ এবং একটি পূর্ণ MCQ গ্রহণ করা হয়েছে।", "medium", "indonesia", true),
  note(552, "মালয়েশিয়া — উৎস-সময়ভিত্তিক রেফারেন্স", "উৎসে মালয়েশিয়ার ১৯৫৭ স্বাধীনতা, সাংবিধানিক রাজতন্ত্র, টেংকু আবদুল রাহমান, পেট্রোনাস টুইন টাওয়ার, মাহাথির মোহাম্মদ এবং MM2H-এর তথ্য আছে।\nসতর্কতা | ১৯৫৭ লাইনটি মালয়া ও মালয়েশিয়ার ঐতিহাসিক পার্থক্য ছাড়া লেখা, এবং office-holder/building-rank/programme-সংক্রান্ত তথ্য source-attributed ও time-sensitive হিসেবে রাখা হয়েছে।", "medium", "malaysia", true),
  note(553, "ফিলিস্তীন ও UNRWA — উৎস-সময়ভিত্তিক রেফারেন্স", "উৎসে পশ্চিম তীর, গাজা, পূর্ব জেরুজালেম, রামাল্লা, ১৯৪৮/১৯৮৮/২০১২, PLO, WAFA, Fatah/Force 17 এবং UNRWA-সংক্রান্ত রাজনৈতিক ও প্রাতিষ্ঠানিক বক্তব্য আছে।\nসতর্কতা | রাজনৈতিক, ধর্মীয়, territorial ও security claims কেবল source-attributed অবস্থায় রাখা হয়েছে; অসম্পূর্ণ East Jerusalem parenthesis এবং ‘ফিলিস্তিন কোটেশন’ line withheld। Resolution 67/19 এবং UNRWA-এর ১৯৪৯ গঠন আলাদা সরাসরি উৎসে যাচাই করা হয়েছে।", "medium", "palestine", true),
];

const mcqs = [
  mcq(549, "02", "রোহিঙ্গা জনগোষ্ঠী মিয়ানমারের কোন রাজ্যে বাস করে?", ["রাখাইন", "শান", "কচিন", "চিন"], "ক", "DU `18-19", "high", "myanmar", true),
  mcq(549, "03", "অং সান সুচির রাজনৈতিক দল-", ["ন্যাশনাল ডেমোক্রেটিক লীগ", "লীগ অব ন্যাশনাল ডেমোক্রেটস", "ন্যাশনাল লীগ ফর ডেমোক্রেসি", "ন্যাশনাল লীগ অব ডেমোক্রেটস"], "গ", "DU `09-10", "medium", "myanmar", true),
  mcq(549, "04", "রোহিঙ্গা কারা?", ["মায়ানমারের একটি জাতিগোষ্ঠী", "পূর্ব মায়ানমারের বসবাসকারী জনগণ", "থাইল্যান্ডের একটি জাতিগোষ্ঠী", "কোনটি নয়"], "ক", "DU `02-03", "high", "rohingya", true),
  mcq(549, "08", "কোন দেশের জাতীয় সংসদ দ্বি-কক্ষে বিভক্ত?", ["মিয়ানমার", "চীন", "সিঙ্গাপুর", "ব্রুনাই"], "ক", "39 BCS", "medium", "myanmar", true),
  mcq(549, "09", "ন্যাশনাল লীগ ফর ডেমোক্রেসি কোন দেশের রাজনৈতিক দল?", ["মালয়েশিয়া", "মিয়ানমার", "ভারত", "থাইল্যান্ড"], "খ", "39 BCS", "high", "myanmar", true),
  mcq(549, "10", "মিয়ানমার বাংলাদেশের কোন দিকে অবস্থিত?", ["দক্ষিণ-পূর্ব", "উত্তর-পূর্ব", "পূর্ব", "পশ্চিম"], "ক", "প্রা.বি. প্রধান শিক্ষক-12", "high", "myanmar"),
  mcq(549, "11", "কুখ্যাত ‘ইনসেন’ কারাগার কোথায়?", ["ইরাক", "বাগদাদ", "আফগানিস্তান", "মিয়ানমার"], "ঘ", "রবি `A` 14-15", "medium", "myanmar", true),
  mcq(551, "03", "বালি কোথায় অবস্থিত?", ["মালয়েশিয়া", "ইরান", "ইন্দোনেশিয়া", "আফগানিস্তান"], "গ", "DU `98-03", "high", "indonesia"),
  mcq(552, "01", "মালয়েশিয়ার সাবেক প্রধানমন্ত্রী ড. মাহাথির মোহাম্মদ ক্ষমতায় ছিলেন-", ["২২ বছর", "২৫ বছর", "২০ বছর", "১৫ বছর"], "ক", "DU `03-06; 27 BCS", "medium", "malaysia", true),
  mcq(552, "02", "Mahathir Mohammad was the _____ Prime Minister of Malaysia.", ["3rd", "5th", "4th", "6th"], "গ", "Bangladesh Krishi Bank Officer-10", "high", "malaysia", true),
  mcq(552, "03", "কৃষিপণ্যে সবচেয়ে বেশি পামওয়েল উৎপাদনকারী দেশ কোনটি?", ["ভারত", "চীন", "মালয়েশিয়া", "যুক্তরাজ্য"], "গ", "প্রা.পি. সরকারি শিক্ষক-04", "high", "malaysia", true),
  mcq(552, "04", "মালয়েশিয়া কোন দেশের উপনিবেশ ছিল?", ["ব্রিটেন", "পর্তুগাল", "ফ্রান্স", "যুক্তরাষ্ট্র"], "ক", "DU `03-08", "high", "malaysia", true),
];

const tags = [
  ["southeast-asia", "Southeast Asia", "domain", "Source-derived Southeast Asian reference."], ["myanmar", "Myanmar", "domain", "Myanmar source material."], ["rohingya", "Rohingya", "domain", "Rohingya source material."], ["indonesia", "Indonesia", "domain", "Indonesia source material."], ["malaysia", "Malaysia", "domain", "Malaysia source material."], ["timor-leste", "Timor-Leste", "domain", "Timor-Leste source material."], ["palestine", "Palestine", "domain", "Palestine source material."], ["unrwa", "UNRWA", "domain", "UNRWA source material."], ["west-asia", "West Asia", "domain", "Source-derived Middle East reference."],
  ["reference-note", "Structured source note", "content_type", "Structured source reference with explicit caveats."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with a printed source key."], ["answer-key", "Answer key", "content_type", "Correct option from the printed key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Directly corroborated by cited official evidence."], ["conflicting-source", "Historically qualified source claim", "quality", "The printed source compresses or conflicts with a verified historical distinction."], ["time-sensitive", "Time-sensitive reference", "quality", "Political, institutional, territorial, or rank-related source material."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed exam label."], ["bcs", "Bangladesh Civil Service", "exam_source", "Bangladesh Civil Service printed exam label."], ["rajshahi-university", "University of Rajshahi", "exam_source", "University of Rajshahi printed exam label."], ["bangladesh-krishi-bank", "Bangladesh Krishi Bank", "exam_source", "Bangladesh Krishi Bank printed recruitment label."], ["primary-school-teacher", "Primary school teacher examination", "exam_source", "Primary school teacher printed recruitment label."],
];
const exam = source => {
  if (source.includes("DU")) return ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"];
  if (source.includes("BCS")) return ["Bangladesh Civil Service", null, "competitive", "bcs"];
  if (source.includes("রবি")) return ["University of Rajshahi", "University of Rajshahi", "admission", "rajshahi-university"];
  if (source.includes("Krishi")) return ["Bangladesh Krishi Bank", "Bangladesh Krishi Bank", "competitive", "bangladesh-krishi-bank"];
  return ["Primary school teacher examination", null, "competitive", "primary-school-teacher"];
};
const quality = row => row.status === "verified" ? "externally-verified" : row.status === "conflicting" ? "conflicting-source" : "source-attributed";
const entityRef = (kind, h) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(h)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const newChapters = [[69, "মধ্যপ্রাচ্যের দেশসমূহ", "middle-east-country-profiles", "Source-preserved Palestine and UNRWA material with explicit political and historical caveats.", 553]];
  const topics = [
    ["myanmar-rohingya-reference", "মিয়ানমার ও রোহিঙ্গা — বিগত প্রশ্ন", "myanmar-rohingya-past-questions", 549, 3],
    ["southeast-asia-country-profiles", "ইন্দোনেশিয়া", "indonesia-reference", 550, 2],
    ["southeast-asia-country-profiles", "মালয়েশিয়া", "malaysia-reference", 552, 3],
    ["middle-east-country-profiles", "ফিলিস্তীন ও UNRWA", "palestine-unrwa-reference", 553, 1],
  ];
  const checks = [...facts.map(row => ({ kind: "fact", claim: row.fact_text, ...row })), ...notes.map(row => ({ kind: "note", claim: row.content, ...row })), ...mcqs.map(row => ({ kind: "mcq", claim: `${row.question} — printed answer: ${row.correct}`, ...row }))];
  const audit = { batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION, source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })), generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length, verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: checks.filter(row => row.status === "conflicting").length, source_attributed: checks.filter(row => row.status === "source_attributed").length }, source_anomalies: ["All five pages rendered at 300 DPI and completed gpt-5-mini transcription plus independent image-grounded review.", "All 35 ordered overlapping dense-image tiles were reviewed.", "Page 549 Q1/Q5/Q6/Q7 and page 551 Q1/Q2/Q4/Q5 are withheld because source options, premise, or time-sensitive wording were not import-safe.", "The book’s Indonesia 1945 and Malaysia 1957 wording is retained with explicit verified chronology caveats rather than silently corrected.", "Page 553 contains politically sensitive Palestine material; it is source-attributed except for discrete UN/UNRWA claims with direct official sources."], quality_gates: ["Exactly physical pages 549–553 are imported.", "Every imported MCQ has four visually reviewed source options and one printed key.", "No blurry or reconstructed MCQ options are imported.", "Tags use only approved categories and country/domain labels use category domain.", "Upserts are idempotent by canonical hash and stable derived-record keys."] };
  const chapterSql = `INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${values(newChapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with explicit review and verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 549: 492, 550: 493, 551: 494, 552: 495, 553: 496 };
  const pageSql = pages.map(page => { const c = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: "/home/ubuntu/dontonyo-work/batch-0549-0553/visual_review_549_553.md", external_verification_report: "/home/ubuntu/dontonyo-work/batch-0549-0553/external_verification.md", classification_report: "/home/ubuntu/dontonyo-work/batch-0549-0553/classification_decisions.md" }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},${q([549, 551, 552].includes(page.source_page) ? "mcq" : "educational")}::page_kind,${q(page.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered source-tile review, withholding rules, and explicit verification status.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.status, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct official corroboration is recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'The printed source is retained with a directly cited historical-chronology caveat.' ELSE 'Source-attributed material retained after ordered image review; it is not silently updated as a current assertion.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name,institution,examType,normalizedName] = exam(row.source); const keys=["ক","খ","গ","ঘ"]; const options=row.options.map((option,index)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index+1},${keys[index]===row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); const explanation = row.source_page===552 && row.number==="03" ? "Printed past-exam key retained as source-attributed material. Production rankings change over time; do not interpret this historical answer as a current ranking." : "Printed answer key retained as source-attributed material; all options and the examination label were visually validated."; return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(examType)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalizedName)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalizedName)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},${q(explanation)},${row.source_page},'বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${options} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalizedName)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const factTags = facts.map(row => [row.domain === "palestine" || row.domain === "unrwa" ? "west-asia" : "southeast-asia", row.domain, quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0549-0553-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const noteTags = notes.map(row => [row.domain === "palestine" ? "west-asia" : "southeast-asia", row.domain, "reference-note", "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0549-0553-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const mcqTags = mcqs.map(row => [row.domain === "myanmar" || row.domain === "rohingya" ? row.domain : "southeast-asia", row.domain, "past-exam-mcq", "answer-key", exam(row.source)[3], "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0549-0553-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row=>`(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${factTags}\n${noteTags}\n${mcqTags}`;
  const verificationSql = checks.map(row => `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${entityRef(row.kind,row.canonical_hash)},${q(row.claim)},NULL,${q(row.status)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(row.status === "verified" ? "Direct official corroboration is listed in the batch verification ledger." : row.status === "conflicting" ? "The printed source has a direct historical-chronology caveat; the wording is retained without silent correction." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${entityRef(row.kind,row.canonical_hash)} AND v.claim_text=${q(row.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0549-0553:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 549 AND 553 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0549-0553:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0549-0553:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 549 AND 553 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0549-0553:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0549-0553:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page IN (549,551,552) AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0549-0553:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 549 AND 553 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 549 AND 553 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page IN (549,551,552) AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0549_0553.mjs. Source pages 549–553 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page=>page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { const {sql,audit}=await buildBatch(); await fs.mkdir(outputDir,{recursive:true}); await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql); await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2)); await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql})); console.log(JSON.stringify({outputDir,...audit},null,2)); }
