import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0524-0528";
const outputDir = path.join(root, "supabase", "batch-0524-0528");
export const BATCH_PAGES = [524, 525, 526, 527, 528];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0524-0528-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = v => `'${String(v ?? "").replaceAll("'", "''")}'`;
const json = v => `${q(JSON.stringify(v))}::jsonb`;
const hash = v => crypto.createHash("sha256").update(v, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(p => path.join(workDir, "pages", `page_${String(p).padStart(4,"0")}.json`));
const refs = { unIndia:["https://www.un.org/en/desa/india-overtake-china-world-most-populous-country-april-2023-united-nations-projects"], borneo:["https://borneoproject.org/borneo-2/"] };
const ctx = p => p <= 525 ? {chapter:"geographical-aliases",topic:p===525?"geographical-aliases-past-exam-mcqs":"gateway-geographical-aliases",chapterTitle:"ভৌগোলিক উপনাম",topicTitle:p===525?"এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন":"প্রবেশদ্বার, প্রাচ্যের, মুক্তা, নিষিদ্ধ ও অন্যান্য"} : {chapter:"asia-continent",topic:p===526?"asia-region-countries":p===527?"asia-country-reference":"asia-geography-southasia",chapterTitle:"এশিয়া মহাদেশ",topicTitle:p===526?"এশিয়া মহাদেশের অঞ্চল ভিত্তিক দেশ":p===527?"তথ্য তরঙ্গে এশিয়া মহাদেশের দেশ":"ভৌগোলিক প্রেক্ষাপটে এশিয়া ও দক্ষিণ এশিয়া"};
const fact = (p,title,text,status="source_attributed",confidence="medium",sources=[]) => ({source_page:p,title,fact_text:text,status,confidence,sources,...ctx(p),canonical_hash:hash(`fact|${p}|${title}|${text}`)});
const note = (p,title,content,confidence="medium") => ({source_page:p,title,content,status:"source_attributed",confidence,sources:[],...ctx(p),canonical_hash:hash(`note|${p}|${title}|${content}`)});
const facts = [
  fact(527,"এশিয়া বৃহত্তম মহাদেশ","পৃথিবীর বৃহত্তম মহাদেশ- এশিয়া।","source_attributed","high"),
  fact(527,"এশিয়ার স্বাধীন রাষ্ট্র সংখ্যা (source statement)","মোট স্বাধীন রাষ্ট্র- ৪৪টি (সর্বশেষ তিমুর-লিসতে)।","source_attributed","low"),
  fact(527,"এশিয়ার জাতিসংঘভুক্ত রাষ্ট্র সংখ্যা (source statement)","মোট জাতিসংঘভুক্ত রাষ্ট্র- ৪৪ টি (সর্বশেষ তিমুর-লিসতে)।","source_attributed","low"),
  fact(527,"এশিয়ার বৃহত্তম দেশ আয়তনে","আয়তনে এশিয়ার বৃহত্তম দেশ- চীন।","source_attributed","high"),
  fact(527,"এশিয়ার বৃহত্তম দেশ জনসংখ্যায়","জনসংখ্যায় এশিয়ার বৃহত্তম দেশ- ভারত।","verified","high",refs.unIndia),
  fact(527,"এশিয়ার ক্ষুদ্রতম দেশ (source statement)","আয়তন ও জনসংখ্যায় এশিয়ার ক্ষুদ্রতম দেশ- মালদ্বীপ।","source_attributed","medium"),
  fact(527,"এশিয়ার বৃহত্তম দ্বীপ (source statement)","বৃহত্তম দ্বীপ- বর্নিও (দ্বীপটির ইন্দোনেশীয় অংশের নাম- কালিমান্তান)।","source_attributed","medium"),
  fact(527,"বর্নিওর রাজনৈতিক বিভাজন","বর্নিও দ্বীপটি রাজনৈতিকভাবে মালয়েশিয়া, ব্রুনেই এবং ইন্দোনেশিয়ার অন্তর্ভুক্ত; ইন্দোনেশীয় অংশের নাম কালিমানতান।","verified","high",refs.borneo),
  fact(527,"এশিয়ার বৃহত্তম সাগর (source statement)","বৃহত্তম সাগর- দক্ষিণ চীন সাগর।","source_attributed","high"),
  fact(527,"এশিয়ার বৃহত্তম উপদ্বীপ (source statement)","বৃহত্তম উপদ্বীপ- আরব উপদ্বীপ।","source_attributed","high"),
  fact(527,"এশিয়ার বৃহত্তম হ্রদ (source statement)","বৃহত্তম হ্রদ- কাস্পিয়ান।","source_attributed","medium"),
  fact(527,"এশিয়ার উচ্চতম পর্বতশৃঙ্গ","উচ্চতম পর্বতশৃঙ্গ- মাউন্ট এভারেস্ট (চীন- নেপাল সীমান্তে)।","source_attributed","high"),
  fact(527,"এশিয়ার উচ্চতম পর্বতশ্রেণী","উচ্চতম পর্বত শ্রেণী- হিমালয়।","source_attributed","high"),
  fact(527,"এশিয়ার বৃহত্তম মরুভূমি (source statement)","বৃহত্তম মরুভূমি- গোবি মরুভূমি (মঙ্গোলিয়া)।","source_attributed","medium"),
  fact(527,"এশিয়ার দীর্ঘতম নদী (source reading)","দীর্ঘতম নদী- ইয়াংসিকিয়াং, চীন।","source_attributed","low"),
  fact(527,"এশিয়ার সর্বোচ্চ বিন্দু","সর্বোচ্চ বিন্দু- মাউন্ট এভারেস্ট।","source_attributed","high"),
  fact(527,"বৃহত্তম মুসলিম রাষ্ট্র আয়তনে (source statement)","এশিয়ার আয়তনে বৃহত্তম মুসলিম রাষ্ট্র- কাজাখস্তান।","source_attributed","low"),
  fact(527,"বৃহত্তম মুসলিম রাষ্ট্র জনসংখ্যায় (source statement)","এশিয়ার বৃহত্তম মুসলিম রাষ্ট্র (জনসংখ্যায়)- ইন্দোনেশিয়া।","source_attributed","high"),
  fact(527,"এশিয়ার বৃহত্তম ফেডারেল রাষ্ট্র (source statement)","এশিয়ার বৃহত্তম ফেডারেল রাষ্ট্র- ভারত।","source_attributed","high"),
  fact(527,"এশিয়ার বৌদ্ধ রাষ্ট্র (source statement)","সাংবিধানিক ভাবে এশিয়ার বৌদ্ধ রাষ্ট্র- শ্রীলঙ্কা।","source_attributed","medium"),
  fact(527,"এশিয়ার খ্রীষ্টান রাষ্ট্র (source statement)","সাংবিধানিক ভাবে এশিয়ার খ্রীষ্টান রাষ্ট্র- ফিলিপাইন।","source_attributed","medium"),
  fact(527,"এশিয়ার ইউরোপীয় প্রাচীনতম উপনিবেশ (source statement)","এশিয়ার ইউরোপের প্রাচীনতম উপনিবেশ- মাকাও।","source_attributed","low"),
  fact(528,"সর্বাধিক দ্বীপ রাষ্ট্র (source statement)","সর্বাধিক দ্বীপ রাষ্ট্র- ইন্দোনেশিয়া।","source_attributed","medium"),
  fact(528,"প্রবাল দ্বীপ রাষ্ট্র (source statement)","প্রবাল দ্বীপ রাষ্ট্র বলে খ্যাত- মালদ্বীপ।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার সারা-বছরের বৃষ্টিপাত (source statement)","দক্ষিণ এশিয়ার যে দেশে সারা বছর বৃষ্টিপাত হয়- শ্রীলংকা।","source_attributed","medium"),
  fact(528,"এশিয়া মাইনর (source statement)","এশিয়া মাইনর- ভূমধ্যসাগরের পূর্ব উপকূল।","source_attributed","medium"),
  fact(528,"পৃথিবীর ছাদ (source reading)","পৃথিবীর ছাদ বলা হয়- পামীর মালভূমিকে (দৈর্ঘ্যতম মালভূমি)।","source_attributed","low"),
  fact(528,"তিব্বত মালভূমির অবস্থান (source statement)","হিমালয় ও কুনলুন পর্বতের মধ্যে অবস্থিত- তিব্বত মালভূমি।","source_attributed","medium"),
  fact(528,"ইরানের জলবায়ু (source statement)","শীতল মরু জলবায়ুর অন্তর্গত মধ্যপ্রাচ্যের দেশ- ইরান।","source_attributed","medium"),
  fact(528,"মঙ্গোলিয়ার পর্বতবেষ্টিত অবস্থান (source reading)","দুর্গমাচ্যের যে দেশের চারিদিকে পর্বত বেষ্টিত- মঙ্গোলিয়া।","source_attributed","low"),
  fact(528,"মঙ্গোলিয়ার যাযাবর অধিবাসী (source reading)","দুর্গমাচ্যের যে দেশের অধিকাংশ অধিবাসী যাযাবর- মঙ্গোলিয়া।","source_attributed","low"),
  fact(528,"জাপানের প্রাকৃতিক বৈশিষ্ট্য (source statement)","ভূমিকম্প এবং অগ্নুৎপাত যে দেশের প্রধান প্রাকৃতিক বৈশিষ্ট্য- জাপান।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার বৃহত্তম দেশ আয়তনে (source statement)","আয়তনে বড় দেশ- ভারত (বিশ্ব ৭ম)।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার ক্ষুদ্রতম দেশ আয়তনে (source statement)","আয়তনে ছোট দেশ- মালদ্বীপ।","source_attributed","high"),
  fact(528,"দক্ষিণ এশিয়ার বৃহত্তম মুসলিম দেশ আয়তনে (source statement)","আয়তনে (মুসলিম) বড় দেশ- পাকিস্তান।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার ক্ষুদ্রতম মুসলিম দেশ আয়তনে (source statement)","আয়তনে (মুসলিম) ছোট দেশ- মালদ্বীপ।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার বৃহত্তম দেশ জনসংখ্যায় (source statement)","দক্ষিণ এশিয়ার সবচেয়ে বড় (জনসংখ্যায়) দেশ- ভারত।","source_attributed","high"),
  fact(528,"দক্ষিণ এশিয়ার ক্ষুদ্রতম দেশ জনসংখ্যায় (source statement)","দক্ষিণ এশিয়ার সবচেয়ে ছোট (জনসংখ্যায়) দেশ- মালদ্বীপ।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার প্রথম স্বাধীন (source statement)","দক্ষিণ এশিয়ার প্রথম স্বাধীন- আফগানিস্তান।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার সর্বশেষ স্বাধীন (source statement)","দক্ষিণ এশিয়ার সর্বশেষ স্বাধীন- বাংলাদেশ।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার ধর্ম নিরপেক্ষ রাষ্ট্র (source statement)","দক্ষিণ এশিয়ার ধর্ম নিরপেক্ষ রাষ্ট্র- নেপাল, ভারত।","source_attributed","medium"),
  fact(528,"দক্ষিণ এশিয়ার ফেডারেল রাষ্ট্র (source statement)","দক্ষিণ এশিয়ার ফেডারেল রাষ্ট্র- ভারত।","source_attributed","high"),
  fact(528,"দক্ষিণ এশিয়ার রাজতান্ত্রিক দেশ (source reading)","দক্ষিণ এশিয়ার শাসনতান্ত্রিক রাজতান্ত্রিক দেশ- ভুটান।","source_attributed","low"),
  fact(528,"দক্ষিণ এশিয়ার ইসলামী প্রজাতান্ত্রিক দেশ (source statement)","দক্ষিণ এশিয়ার ইসলামী প্রজাতান্ত্রিক দেশ- পাকিস্তান, আফগানিস্তান।","source_attributed","low"),
  fact(528,"দক্ষিণ এশিয়ার সাংবিধানিক বৌদ্ধ রাষ্ট্র (source statement)","দক্ষিণ এশিয়ার একমাত্র সাংবিধানিক বৌদ্ধ রাষ্ট্র- শ্রীলংকা।","source_attributed","low"),
];
const notes = [
  note(524,"ভৌগোলিক উপনাম — প্রবেশদ্বার, প্রাচ্যের, মুক্তা ও অন্যান্য","বিভাগ | ভৌগোলিক উপনাম | Geographical Alias | দেশ/স্থান\nপ্রবেশদ্বার | ইউরোপের প্রবেশদ্বার | Gateway to Europe | লন্ডন, রটডাম, শিবকন [unclear]\nপ্রবেশদ্বার | ভারতের প্রবেশদ্বার | Gateway of India | মুম্বাই\nপ্রবেশদ্বার | পাকিস্তানের প্রবেশদ্বার | Gateway of Pakistan | করাচী\nপ্রবেশদ্বার | মধ্য ও পূর্ব ইউরোপের প্রবেশদ্বার | Gateway to Central and Eastern Europe | ভিয়েনা\nপ্রাচ্যের | প্রাচ্যের গ্রেট ব্রিটেন | Great Britain of the East | জাপান\nপ্রাচ্যের | প্রাচ্যের ম্যানচেস্টার | Manchester of the East | ওসাকা\nপ্রাচ্যের | প্রাচ্যের ভেনিস | Venice of the East | বরিশাল, ব্যাংকক, ভোকা [unclear]\nপ্রাচ্যের | উত্তরের ভেনিস | Venice of the North | স্টকহোম\nমুক্তা | মুক্তার দেশ | Country of Pearl | কিউবা\nমুক্তা | মুক্তার দ্বীপ | Island of Pearl | বাহরাইন\nমুক্তা | আফ্রিকার মুক্তা | Pearl of Africa | উগান্ডা*\nনোট | *উগান্ডাকে Pearl of Africa নামে অভিহিত করেন- ব্রিটিশ প্রধানমন্ত্রী উইনস্টন চার্চিল। | | \nনিষিদ্ধ | নিষিদ্ধ দেশ | Forbidden Country | তিব্বত\nনিষিদ্ধ | নিষিদ্ধ শহর | Forbidden City | লাসা (তিব্বত)\nঅন্যান্য | শান্তির নীড় | Abode of Peace | বাগদাদ\nঅন্যান্য | চীনের নীল নদ | The Nile of China | ইয়াসিকিয়াং [unclear]\nঅন্যান্য | বড় আপেল | Big Apple | নিউইয়র্ক\nঅন্যান্য | দক্ষিণের রানি | Queen of the South | সিডনি\nঅন্যান্য | সমুদ্রের বধূ/রানি | Bride/Queen of the sea | গ্রেট ব্রিটেন [unclear]\nঅন্যান্য | সো. ই. এর শস্যভাণ্ডার | Granary of Soviet Union | ইউক্রেন\nঅন্যান্য | পশুপালনের দেশ | Livestock rearing Country | তুর্কিস্তান [unclear]","medium"),
  note(526,"এশিয়া মহাদেশের অঞ্চলভিত্তিক দেশ (source table)","অঞ্চল | উৎসে প্রদত্ত সংখ্যা | দেশসমূহ\nদক্ষিণ এশিয়া | ৮ টি | বাংলাদেশ, ভারত, শ্রীলংকা, মালদ্বীপ, ভূটান, পাকিস্তান, আফগানিস্তান, নেপাল\nদক্ষিণ-পূর্ব এশিয়া | ১১ টি | মালয়েশিয়া, থাইল্যান্ড, ভিয়েতনাম, ফিলিপাইন, ইন্দোনেশিয়া, লাওস, তিমুর-লিস্তে, ব্রুনাই, কম্বোডিয়া, সিঙ্গাপুর, মিয়ানমার\nদক্ষিণ-পশ্চিম এশিয়া | ১৬ টি | ইরাক, ইরান, সৌদি আরব, সিরিয়া, ইসরাইল, জর্ডান, লেবানন, কুয়েত, ইয়েমেন, কাতার, বাহরাইন, স. আ. আমিরাত, ওমান, তুরস্ক, সাইপ্রাস, ফিলিস্তিন\nসোর্স নোট | ফিলিস্তিনের স্বাধীনতা না থাকলেও ফিলিস্তিন মধ্যপ্রাচ্যের অংশ | \nদূর প্রাচ্য | ৬ টি | চীন, তাইওয়ান, উত্তর কোরিয়া, দক্ষিণ কোরিয়া, মঙ্গোলিয়া, জাপান\nমধ্য এশিয়া | ৫ টি | কাজাখস্তান, কিরগিজিস্তান, তুর্কমেনিস্তান, তাজিকিস্তান, উজবেকিস্তান\nউৎস শিরোনাম | এশিয়া মহাদেশের অঞ্চল ভিত্তিক ৪৪ টি স্বাধীন দেশ | Time-sensitive source-era count","medium"),
  note(527,"বর্নিও (source caption)","বর্নিও এশিয়ার বৃহত্তম ও পৃথিবীর তৃতীয় বৃহত্তম দ্বীপ। অনেকেই বর্নিওকে ইন্দোনেশিয়ার দ্বীপ মনে করে থাকে। বর্নিও দ্বীপটি রাজনৈতিকভাবে তিনটি দেশের অন্তর্ভুক্ত; দেশগুলো হলো- মালয়েশিয়া, ব্রুনেই এবং ইন্দোনেশিয়া। বর্নিও দ্বীপটির ইন্দোনেশীয় অংশের নাম কালিমানতান।\nতথ্যসূত্র: ResearchGate.","medium"),
];
const mcq = (n,question,options,correct,source,confidence="high") => ({source_page:525,number:n,question,options,correct,source,confidence,status:"source_attributed",sources:[],...ctx(525),canonical_hash:hash(`mcq|525|${n}|${question}`)});
const mcqs = [
  mcq("01","বরিশালের রূপে মুগ্ধ হয়ে কোন কবি এই নগরকে 'বাংলার ভেনিস' আখ্যা দিয়েছিলেন?",["রবীন্দ্রনাথ ঠাকুর","কাজী নজরুল ইসলাম","জসীমউদ্দীন","জীবনানন্দ দাশ"],"খ","DU খ ২০-২১"),
  mcq("02","কোন শহরটি 'বিগ অ্যাপল' নামে পরিচিত?",["প্যারিস","নিউইয়র্ক","লন্ডন","সিঙ্গাপুর"],"খ","DU খ ১৬-১৭, খ ৯৮-৯৯"),
  mcq("03","জাপানের অন্য নামটি হচ্ছে-",["কারে (source reading uncertain)","নিপ্পন","কিজেতো","সামুরাই"],"খ","DU খ ০১-০২","low"),
  mcq("04","কোন দেশটিকে 'সোভিয়েত ইউনিয়নের শ্যাভাভার' বলা হত?",["পূর্ব জার্মানি","ইউক্রেন","পোল্যান্ড","লাটভিয়া"],"খ","DU খ ০২-০৩","medium"),
  mcq("05","কোনটি চির শান্তির শহর নামে পরিচিত?",["রোম","ভেনিস","এথেন্স","অসলো"],"ক","23 BCS/ সহকারী আবহাওয়াবিদ-04"),
  mcq("06","কোনটি নিকট সূর্যের দেশ নামে পরিচিত?",["হামারেকেস্ট (source reading uncertain)","কুইবেক","তিবত","নরওয়ে"],"ঘ","23 BCS/ রবি লোকপ্রশাসন ০৩-০১","low"),
  mcq("07","বিশ্বের কোন শহর 'নিশ্চিত শহর' নামে পরিচিত?",["লাসা","উলানবাটার","পিয়িংইং (source reading uncertain)","কাবুল"],"ক","15 BCS","low"),
  mcq("08","পবিত্র ভূমি কোনটিকে বলা হয়?",["জেদ্দা","জেরুজালেম","প্যালেস্টাইন","তায়েফ"],"খ","11 BCS"),
  mcq("09","ইউরোপের ককপিট বলা হয় কোন দেশকে?",["বেলজিয়াম","ফ্রান্স","জার্মানি","ফিনল্যান্ড"],"ক","28 BCS"),
  mcq("10","প্রাচ্যের ভেনিস কোনটি?",["সিঙ্গাপুর","চিটাগাং","ব্যাংকক","ওসাকা"],"গ","কমপ্লেক্স্‌হান ব্যাংক সহকারী অফিসার, ০৮","medium"),
  mcq("11","উত্তরের ভেনিস বলা হয়-",["কুইবেক","স্যাক্রমেন্টো (source reading uncertain)","রোম","অসলো"],"খ","জাহাবি-ইতিহাস বিভাগ, ০৯-১০","low"),
  mcq("12","কোন দেশকে ধীবরের দেশ বলা হয়?",["বাংলাদেশ","জাপান","মালয়েশিয়া","নরওয়ে"],"ঘ","মাধ্যমিক বিদ্যালয়ের সহকারী শিক্ষক, ০০","medium"),
  mcq("13","সকাল বেলার শান্তি বলা হয় কোনটিকে?",["ফিনল্যান্ডকে","কোরিয়াকে","থাইল্যান্ডকে","ইতালিকে"],"খ","জবি-২, ১১-১২","low"),
  mcq("14","'সমুদ্রের ঝড়' - এই ভৌগলিক উপনামটি কোন দেশের?",["কিউবা","গ্রেট ব্রিটেন","শ্রীলঙ্কা","জাপান"],"খ","সাব রেজিস্টার, ০৩","low"),
];
const exam = s => s.includes("DU") ? ["University of Dhaka","University of Dhaka","admission","dhaka-university"] : s.includes("BCS") ? ["Bangladesh Civil Service",null,"competitive","bcs"] : ["Other university and recruitment examination",null,"competitive","other-recruitment"];
const quality = x => x.status==="verified"?"externally-verified":x.status==="conflicting"?"conflicting":"source-attributed";
const recordId=(kind,key)=>kind==="fact"?`(SELECT id FROM public.gk_facts WHERE canonical_hash=${q(key)} LIMIT 1)`:kind==="note"?`(SELECT id FROM public.gk_notes WHERE canonical_hash=${q(key)} LIMIT 1)`:`(SELECT id FROM public.gk_mcqs WHERE canonical_hash=${q(key)} LIMIT 1)`;
const tags = [["geographical-aliases","Geographical aliases","domain","Source-derived geographical-alias reference material."],["asia-reference","Asia reference","domain","Source-derived Asia geography and country-reference material."],["reference-table","Reference table","content_type","Structured source table retained as a note."],["past-exam-mcq","Past-exam MCQ","content_type","MCQ with printed examination label and answer key."],["answer-key","Answer key","content_type","Correct answer recorded from the printed source answer key."],["source-attributed","Source-attributed","quality","Source-preserved material without direct corroboration in this batch."],["externally-verified","Externally verified","quality","Claim directly corroborated by an external source."],["time-sensitive","Time-sensitive reference","quality","Historical or political reference requiring future review."],["dhaka-university","University of Dhaka","exam_source","University of Dhaka examination label as printed."],["bcs","BCS","exam_source","Bangladesh Civil Service label as printed."],["other-recruitment","Other recruitment examination","exam_source","Other university, bank, or recruitment examination label as printed."]];

export async function buildBatch(){
 const pages=await Promise.all(files.map(f=>fs.readFile(f,"utf8").then(JSON.parse)));
 const chapters=[[62,"এশিয়া মহাদেশ","asia-continent","Source-preserved Asia regional lists, geographic facts, and country-reference material.",526]];
 const topics=[["geographical-aliases","প্রবেশদ্বার, প্রাচ্যের, মুক্তা, নিষিদ্ধ ও অন্যান্য","gateway-geographical-aliases",524,4],["geographical-aliases","ভৌগোলিক উপনাম সম্পর্কিত বিগত বছরের প্রশ্ন","geographical-aliases-past-exam-mcqs",525,5],["asia-continent","এশিয়া মহাদেশের অঞ্চলভিত্তিক দেশ","asia-region-countries",526,1],["asia-continent","তথ্য তরঙ্গে এশিয়া মহাদেশের দেশ","asia-country-reference",527,2],["asia-continent","ভৌগোলিক প্রেক্ষাপটে এশিয়া ও দক্ষিণ এশিয়া","asia-geography-southasia",528,3]];
 const checks=[...facts.map(x=>({kind:"fact",...x,claim:x.fact_text})),...notes.map(x=>({kind:"note",...x,claim:x.content})),...mcqs.map(x=>({kind:"mcq",...x,claim:`${x.question} — printed answer: ${x.correct}`}))];
 const audit={batch_pages:BATCH_PAGES,pipeline_version:PIPELINE_VERSION,source_pages:pages.map(p=>({page:p.source_page,review_status:p.review.review_status,image_sha256:p.source_image_sha256})),generated_facts:facts.length,generated_notes:notes.length,generated_mcqs:mcqs.length,generated_options:mcqs.length*4,generated_flashcards:facts.length+notes.length+mcqs.length,verification_counts:{verified:checks.filter(x=>x.status==="verified").length,conflicting:0,source_attributed:checks.filter(x=>x.status==="source_attributed").length},source_anomalies:["Physical PDF pages 524–528 retain book footers 467–471.","Page 524 retains five unresolved source spellings rather than substituting inferred place names.","Page 525 retains four visually unclear MCQ options with low confidence and printed answer keys.","Page 526 retains a source-era 44-country count and political regional taxonomy.","Page 527 excludes two garbled lower OCR lines after Macau; only reviewed text is imported.","Page 528 retains time-sensitive political and constitutional source statements with corrections and confidence flags."],quality_gates:["Exactly physical pages 524–528 are imported.","All 25 ordered tiles were visually reviewed.","Facts, notes, MCQs, options, answers, and examination metadata remain relationally distinct.","Upserts are idempotent by canonical hash, page, and stable source key."]};
 const chapterSql=`INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${values(chapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
 const topicSql=`INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved material with explicit verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
 const pagesSql=pages.map(p=>{const c=ctx(p.source_page);const printed={524:467,525:468,526:469,527:470,528:471}[p.source_page];const meta={source_image_sha256:p.source_image_sha256,extraction_model:p.model,review_status:p.review.review_status,corrections:p.review.corrections,unresolved_spans:p.review.unresolved_spans,accepted_content_tags:p.review.accepted_content_tags,physical_source_page:p.source_page,printed_book_page:printed,artifact_reported_page:p.transcription.source_page,visual_review_report:"/home/ubuntu/dontonyo/reports/batch-0524-0528_visual_review.md",external_verification_report:"/home/ubuntu/dontonyo/reports/batch-0524-0528_external_verification.md",page_number_mismatch:"Physical PDF page and printed source footer are separately preserved."};return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${p.source_page},${q(p.source_page===525?"mcq":"educational")}::page_kind,${q(p.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(p.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(p.model)},'Quality-gated extraction with tile review, source-preserved anomalies, and explicit verification statuses.',${json(meta)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${p.source_page});`;}).join("\n");
 const factSql=`WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.fact_text,x.status,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct external corroboration is recorded in the batch verification ledger.' ELSE 'Source-attributed material is retained with visual review and no silent factual update.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
 const noteSql=`WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.content,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
 const mcqSql=mcqs.map(x=>{const [name,institution,type,normalized]=exam(x.source);const keys=["ক","খ","গ","ঘ"];const options=x.options.map((o,i)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[i])},${q(o)},${i+1},${keys[i]===x.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[i])});`).join("\n");return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${x.source_page}.`)},${q(normalized)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalized)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(x.question)},${q(x.correct)},'Printed answer key retained as source-attributed material; all options and the examination label were visually validated.',${x.source_page},'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন',${q(x.number)},3,${q(x.confidence)}::confidence_level,${q(x.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(x.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(x.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${options} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalized)} LIMIT 1),NULL,${q(x.source)},${q(x.source)},${x.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(x.source)} AND s.source_page=${x.source_page});`;}).join("\n");
 const tagSql=`INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(x=>`(${x.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(x=>["asia-reference",quality(x),"time-sensitive"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0524-0528-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(x=>[x.source_page===524?"geographical-aliases":"asia-reference","reference-table","source-attributed","time-sensitive"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0524-0528-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${mcqs.map(x=>["past-exam-mcq","answer-key",exam(x.source)[3],"source-attributed"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0524-0528-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
 const verificationSql=checks.map(x=>`INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${x.source_page},${q(x.kind)},${recordId(x.kind,x.canonical_hash)},${q(x.claim)},NULL,${q(x.status)},${q(x.confidence)}::confidence_level,${json(x.sources)},${q(x.status==="verified"?"Direct external corroboration is listed in the batch verification ledger.":"Source-attributed record retained with image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(x.kind)} AND v.entity_id=${recordId(x.kind,x.canonical_hash)} AND v.claim_text=${q(x.claim)});`).join("\n");
 const derivedSql=`INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0524-0528:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 524 AND 528 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0524-0528:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0524-0528:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 524 AND 528 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0524-0528:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0524-0528:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page=525 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0524-0528:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked Asia GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 524 AND 528 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 524 AND 528 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page=525 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
 const sql=`-- Generated by prepare_validated_batch_0524_0528.mjs. Source pages 524–528 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(p=>p.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pagesSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
 return {sql,audit};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {sql,audit}=await buildBatch();await fs.mkdir(outputDir,{recursive:true});await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql);await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2));await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql}));console.log(JSON.stringify({outputDir,...audit},null,2));}
