import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0514-0518";
const outputDir = path.join(root, "supabase", "batch-0514-0518");
export const BATCH_PAGES = [514, 515, 516, 517, 518];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0514-0518-v1";
const BOOK_TITLE = "Jubayer's GK";
const pageFiles = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const vals = rows => rows.map(row => `(${row.map(q).join(", ")})`).join(",\n");
const ref = {
  dod: ["https://history.defense.gov/DOD-DOW-History/Pentagon/History/"],
  un: ["https://www.un.org/en/exhibits/page/about-us"],
};

const tags = [
  ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with printed examination label and answer key."],
  ["answer-key", "Answer key", "content_type", "Answer recorded from the printed source answer key."],
  ["world-legislatures", "World legislatures", "domain", "Source-derived legislature reference content."],
  ["historical-place-names", "Historical place names", "domain", "Former/current country and place-name reference content."],
  ["famous-residences", "Famous residences", "domain", "Source-derived official-residence reference content."],
  ["government-offices", "Government offices", "domain", "Source-derived secretariat and office reference content."],
  ["reference-table", "Reference table", "content_type", "Structured source table retained as a note."],
  ["source-attributed", "Source-attributed", "quality", "Image-grounded source material without direct corroboration in this batch."],
  ["externally-verified", "Externally verified", "quality", "Claim directly corroborated by a named external authority."],
  ["conflicting", "Conflicting external evidence", "quality", "Source claim conflicts with credible external evidence and is retained without silent correction."],
  ["time-sensitive", "Time-sensitive reference", "quality", "Institutional or political material that may change over time."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka examination label as printed."],
  ["bcs", "BCS", "exam_source", "Bangladesh Civil Service examination label as printed."],
  ["medical-admission", "Medical admission", "exam_source", "Medical admission examination label as printed."],
  ["other-recruitment", "Other recruitment examination", "exam_source", "Other university or recruitment examination label as printed."],
];

const context = page => {
  if (page === 514) return { chapter: "world-legislatures", topic: "legislature-past-exam-mcqs", title: "বিশ্বের বিভিন্ন দেশের আইনসভার নাম", topicTitle: "এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন" };
  if (page === 515) return { chapter: "former-current-names", topic: "historical-name-reference", title: "পূর্বনাম ও বর্তমান নাম", topicTitle: "দেশ ও স্থানের পূর্বনাম এবং বর্তমান নাম" };
  if (page === 516) return { chapter: "former-current-names", topic: "historical-name-past-exam-mcqs", title: "পূর্বনাম ও বর্তমান নাম", topicTitle: "এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন" };
  if (page === 517) return { chapter: "famous-residences", topic: "official-residences-reference", title: "বিভিন্ন দেশের বিখ্যাত বাসভবন", topicTitle: "বিখ্যাত সরকারি বাসভবন" };
  return { chapter: "government-offices", topic: "secretariats-offices-reference", title: "বিভিন্ন দেশের সচিবালয়", topicTitle: "বিভিন্ন দেশের সচিবালয় ও সরকারি কার্যালয়" };
};
const canonical = (type, page, title, body) => hash(`${type}|${page}|${title}|${body}`);
const note = (page, title, content, confidence = "medium") => ({ source_page: page, title, content, ...context(page), status: "source_attributed", confidence, sources: [], canonical_hash: canonical("note", page, title, content) });
const fact = (page, title, fact_text, status, confidence, sources) => ({ source_page: page, title, fact_text, ...context(page), status, confidence, sources, canonical_hash: canonical("fact", page, title, fact_text) });

const notes = [
  note(515, "দেশের পূর্বনাম ও বর্তমান নাম", "পূর্বনাম | বর্তমান নাম | পূর্বনাম | বর্তমান নাম\nনিপ্পন | জাপান | গোল্ড কোস্ট | ঘানা\nফরমোজা | তাইওয়ান | দাহোমি | বেনিন\nমালয় | মালয়েশিয়া | ফ্রেঞ্চ সোমালিল্যান্ড | জিবুতি\nতুসাসিক | সিঙ্গাপুর | আপার ভোল্টা | বারকিনা ফাসো\nকাম্পুচিয়া | কম্বোডিয়া | স্পেনিস গিনি | নিরক্ষীয় গিনি\nশ্যাম | থাইল্যান্ড | পর্তুগিজ গিনি | গিনিবিসাউ\nব্রহ্মদেশ, বার্মা | মিয়ানমার | বাসুতোল্যান্ড | লেসোথো\nসিলন | শ্রীলংকা | বেচুয়ানাল্যান্ড | বতসোয়ানা\nহল্যান্ড | নেদারল্যান্ড | উত্তর রোডেশিয়া | জাম্বিয়া\nহেলভেটিয়া | সুইজারল্যান্ড | দক্ষিণ রোডেশিয়া | জিম্বাবুয়ে\nডয়েচল্যান্ড | জার্মানি | মালাগাাসি | মাদাগাস্কার\nদ্য গল | ফ্রান্স | জায়ারে | গণ. কঙ্গো প্রজাতন্ত্র\nহেলাস | গ্রিস | কঙ্গো-ব্রাজভিল | কঙ্গো প্রজাতন্ত্র\nমলদাভিয়া | মলদোভা | ব্রিটিশ হন্ডুরাস | বেলিজ\nনায়াসাল্যান্ড | মালাউই | ডাচ গায়ানা | সুরিনাম\nসোয়াজিল্যান্ড | ইসোয়াতিনি | ব্রিটিশ গায়ানা | গায়ানা\nআবিসিনিয়া | ইথিওপিয়া | এলিস দ্বীপপুঞ্জ | টুভালু\nদক্ষিণ-পশ্চিম আফ্রিকা | নামিবিয়া | নিউ হেব্রাইডিস | ভানুয়াতু\nজাঞ্জিবার ও ট্যাঙ্গানিকা | তানজানিয়া | গিলব্রাট দ্বীপপুঞ্জ | কিরিবাতি"),
  note(515, "স্থানের পূর্বনাম ও বর্তমান নাম", "পূর্বনাম | বর্তমান নাম | পূর্বনাম | বর্তমান নাম\nহস্তিনাপুর | দিল্লি (ভারত) | আল কাহিরা | কায়রো (মিশর)\nবোম্বাই | মুম্বাই (ভারত) | খ্রিস্টিনা | অসলো (নরওয়ে)\nমাদ্রাজ | চেন্নাই (ভারত) | জওহরগালা | গ্রজনি (রাশিয়া)\nবাটাভিয়া | জাকার্তা (ইন্দোনেশিয়া) | মালভিনাস | ফকল্যান্ড (ব্রিটেন)\nমানচুকিয়ো | মাঞ্চুরিয়া (চীন) | স্যান্ডউইচ দ্বীপপুঞ্জ | হাওয়াই দ্বীপপুঞ্জ (যুক্তরাষ্ট্র)\nসলসবেরি | হারারে (জিম্বাবুয়ে) | কেপকেনেডি | কেপ কেনাভিরাল (যুক্তরাষ্ট্র)"),
  note(517, "বিভিন্ন দেশের বিখ্যাত বাসভবন", "হোয়াইট হাউজ | ওয়াশিংটন ডিসি | যুক্তরাষ্ট্রের প্রেসিডেন্টের সরকারি বাসভবন\nএলিসি প্রাসাদ | প্যারিস | ফ্রান্সের প্রেসিডেন্টের সরকারি বাসভবন\n৭, লোক কল্যাণ মার্গ | নয়াদিল্লি | ভারতের প্রধানমন্ত্রীর সরকারি বাসভবন\nরাষ্ট্রপতি ভবন | নয়াদিল্লি | ভারতের রাষ্ট্রপতির সরকারি বাসভবন\nমালকানাং প্রাসাদ | ম্যানিলা | ফিলিপাইনের প্রেসিডেন্টের সরকারি বাসভবন\n১০নং ডাউনিং স্ট্রীট | লন্ডন | ইংল্যান্ডের প্রধানমন্ত্রীর সরকারি বাসভবন\n১১নং ডাউনিং স্ট্রীট | লন্ডন | প্রধানমন্ত্রীর প্রাক্তন বাসভবন (বর্তমানে অর্থমন্ত্রীর বাসভবন)\nমিরাফ্লোরেস | কারাকাস | ভেনিজুয়েলার প্রেসিডেন্টের সরকারি বাসভবন\nটেম্পল ট্রিস | কলম্বো | শ্রীলংকার প্রধানমন্ত্রীর সরকারি বাসভবন\nবাকিংহাম প্যালেস | লন্ডন | ব্রিটেনের রাজার বাসভবন\nমারদেকা প্রাসাদ | জাকার্তা | ইন্দোনেশিয়ার প্রেসিডেন্টের সরকারি বাসভবন\nবোগোর প্রাসাদ | জাকার্তা | ইন্দোনেশিয়ার প্রেসিডেন্টের গ্রীষ্মকালীন বাসভবন\nব্লু হাউস | সিউল | দক্ষিণ কোরিয়ার প্রেসিডেন্টের সরকারি বাসভবন\nপোডালা প্রাসাদ | লাসা, তিব্বত | দালাইলামার বাসভবন\nদি লজ | ক্যানবেরা | অস্ট্রেলিয়ার প্রধানমন্ত্রীর সরকারি বাসভবন"),
  note(518, "বিভিন্ন দেশের সচিবালয়", "পেন্টাগন | ভার্জিনিয়া | মার্কিন প্রতিরক্ষা বিভাগের সদর দপ্তর | নির্মাণ: ১৯৪৩ সালে\nওভাল অফিস | ওয়াশিংটন ডি.সি. | যুক্তরাষ্ট্রের প্রেসিডেন্টের সরকারি কার্যালয়\nব্লেয়ার হাউজ | ওয়াশিংটন ডিসি | যুক্তরাষ্ট্রের রাষ্ট্রীয় অতিথি ভবন\nসিংহ দরবার | কাঠমুন্ডু | নেপাল সরকারের কার্যালয়\nরাইটার্স বিল্ডিং | কলকাতা | ভারতের পশ্চিমবঙ্গ সরকারের সচিবালয়\nবুশ হাউস | লন্ডন | বিবিসির প্রধান কার্যালয় ছিল\nক্রেমলিন | মস্কো | রাশিয়া সরকারের সচিবালয়; প্রাক্তন জারদের বাসভবন\nহোয়াইট হল | লন্ডন | ব্রিটিশ সরকারের কার্যালয়\nফ্লাশিং মিডোস | নিউইয়র্ক | জাতিসংঘের মূল সভাস্থল\nশান্তি প্রাসাদ | নেদারল্যান্ডসের হেগ | আন্তর্জাতিক বিচারালয় ভবন\nক্যাপিটাল হিল | ওয়াশিংটন ডি.সি | যুক্তরাষ্ট্রের কংগ্রেস ভবন\nকুব্বে প্যালেস | কায়রো | মিশর সরকারের সচিবালয়"),
  note(518, "ব্লু হাউজ (source note)", "দক্ষিণ কোরিয়ার সিউলে অবস্থিত প্রেসিডেন্টের বাসভবন সম্পূর্ণ নীল রংয়ের বাড়ি “ব্লু হাউজ”।"),
];
const facts = [
  fact(518, "পেন্টাগন", "পেন্টাগন ভার্জিনিয়ায় অবস্থিত মার্কিন প্রতিরক্ষা বিভাগের সদর দপ্তর; উৎসে এর নির্মাণ ১৯৪৩ সালে হিসেবে উল্লিখিত।", "verified", "high", ref.dod),
  fact(518, "ফ্লাশিং মিডোস ও জাতিসংঘ (source statement)", "ফ্লাশিং মিডোস, নিউইয়র্ককে জাতিসংঘের মূল সভাস্থল হিসেবে উৎসে উল্লেখ করা হয়েছে।", "conflicting", "high", ref.un),
];
const mcq = (page, number, question, options, correct, source, confidence = "high") => ({ source_page: page, number, question, options, correct, source, ...context(page), status: "source_attributed", confidence, sources: [], canonical_hash: canonical("mcq", page, number, question) });
const mcqs = [
  mcq(514,"1","স্টেট ডুমা যে দেশের আইনসভা-",["জাপান","তুরস্ক","জার্মানি","রাশিয়া"],"ঘ","DU খ' ০৯-১০"),
  mcq(514,"2","ভারতের আইন সভার নিম্নকক্ষের নাম-",["রাজ্যসভা","লোকসভা","জাতীয় সংসদ","বিধানসভা"],"খ","DU ঘ' ০৭-০৮"),
  mcq(514,"3","উত্তর কোরিয়ার পার্লামেন্টের নাম-",["লর্ডস অ্যাসেম্বলি","সুপ্রিম পিপলস অ্যাসেম্বলি","ফেডারেল অ্যাসেম্বলি","হাউজ অব অ্যাসেম্বলি"],"খ","DU খ' ০৫-০৬"),
  mcq(514,"4","জাপানের পার্লামেন্টের নাম কী?",["কংগ্রেস","নেসেট","মজলিস","ডায়েট"],"ঘ","DU খ' ০৩-০৪; ঘ' ৯৫-৯৬, 11, 26 BCS"),
  mcq(514,"5","ইসরাইলের পার্লামেন্টের নাম কী?",["Duma","Diet","Knesset","Congress"],"গ","DU ঘ' ০৪-০৫; খ' ০১-০২/ সহকারী থানা শিক্ষা অফিসার, ০৫"),
  mcq(514,"6","নরওয়ের পার্লামেন্টের নাম-",["সীম","করতেস","স্টরটিং","ডুমা"],"গ","DU খ' ১১-১২"),
  mcq(514,"7","ফোলকেটিং (Folketing) কোন দেশের আইন সভা?",["ডেনমার্ক","বেলজিয়াম","নরওয়ে","ফিনল্যান্ড"],"ক","39 BCS"),
  mcq(514,"8","‘লয়াজিরগা’ কোন দেশের আইনসভা?",["ফিজি","সিরিয়া","লেবানন","আফগানিস্তান"],"ঘ","34 BCS"),
  mcq(514,"9","ভারতীয় আইনসভার উচ্চকক্ষের নাম-",["লোকসভা","বিধানসভা","রাজ্যসভা","লর্ডসভা"],"গ","রাবি-রাষ্ট্রবিজ্ঞান, ০৪-০৫"),
  mcq(514,"10","‘ডায়েট’ কোন দেশের পার্লামেন্টের নাম?",["মিসর","জাপান","কানাডা","ইসরাইল"],"খ","ববি প্রবি ১২-১৩"),
  mcq(514,"11","কোন দেশের পার্লামেন্টের নাম কংগ্রেস?",["ভারত","সুইডেন","ইউ.এস.এ","দক্ষিণ আফ্রিকা"],"গ","শি..নি-১০"),
  mcq(514,"12","‘হাউস অব লর্ডস’ এবং ‘হাউস অব কমন্স’- কোন দেশের পার্লামেন্টের নাম?",["যুক্তরাষ্ট্র","যুক্তরাজ্য","ইতালি","ফ্রান্স"],"খ","চবি-খ, ০৭-০৮"),
  mcq(514,"13","‘সীম’ কোন দেশের পার্লামেন্টের নাম?",["মালয়েশিয়া","পোল্যান্ড","সুইডেন","নেদারল্যান্ডস"],"খ","রাবি-গ্রন্থাগার ও তথ্যবিজ্ঞান, ০৫-০৬, মার্কেটিং বিভাগ, ০৪-০৫"),
  mcq(514,"14","মঙ্গোলিয়ার পার্লামেন্টের নাম কী?",["কংগ্রেস","চেম্বার","উয়ান","খুরাল"],"ঘ","উপজেলা মহিলা কর্মকর্তা-০৭"),
  mcq(516,"1","ইস্তাম্বুলের পূর্বনাম-",["আঙ্কারা","ইজমির","কনস্ট্যান্টিনোপল","আদানা"],"গ","DU ঘ' ০৭-০৮"),
  mcq(516,"2","জিম্বাবুয়ের পূর্ব নাম-",["দক্ষিণ রোডেশিয়া","গ্রীনল্যান্ড","গোল্ড কোস্ট","প্রিটোরিয়া"],"ক","DU খ' ০২-০৩; ঘ' ৯৫-৯৬"),
  mcq(516,"3","লেলিনগ্রাদের বর্তমান নাম-",["পেট্রোগ্রাদ","মস্কো","সেন্ট পিটার্সবার্গ","বাকু"],"গ","DU খ' ০২-০৩"),
  mcq(516,"4","কোন দেশের অপর নাম নিপ্পন?",["কোরিয়া","জাপান","ফিজি","ব্রুনাই"],"খ","DU খ' ০২-০৩"),
  mcq(516,"5","হো চি মিন নগরের পূর্ববর্তী নাম কী ছিল?",["সায়গন","ভিয়েতনাম","হ্যানয়","ভিয়েনতিয়েন"],"ক","DU ঘ' ৯৯-০০, ৯৭-৯৮"),
  mcq(516,"6","বার্মার বর্তমান নাম কী?",["আকিয়াব","মায়ানমার","ইয়াংগুন","শ্যাম"],"খ","DU ঘ' ৯৯-০০"),
  mcq(516,"7","কঙ্গো প্রজাতন্ত্রের পূর্বনাম-",["ইয়াসরিব","জিম্বাবুয়ে","জিবুতি","জায়ারে"],"ঘ","12 BCS"),
  mcq(516,"8","'হারারে'-এর পুরাতন নাম-",["পেট্রোগ্রাড","ফরমূজা","সলসবেবি","রোডেশিয়া"],"গ","11 BCS"),
  mcq(516,"9","ব্রহ্মদেশ বর্তমানে কী নামে পরিচিত?",["থাইল্যান্ড","মায়ানমার","সুরিনাম","কম্বোডিয়া"],"খ","MAT ০৩-০৪"),
  mcq(516,"10","সলসবেবির নতুন নাম কী?",["হারারে","কিনসাসা","অ্যাঙ্গোলা","জিম্বাবুয়ে"],"ক","পাবলিক সার্ভিস কমিশনে সহকারী পরিচালক, ৯৪"),
  mcq(516,"11","'ইথিওপিয়া' দেশের পুরাতন নাম কী ছিল?",["রোডেশিয়া","জায়ার","আবিসিনিয়া","সলসবেবি"],"গ","জবি-চ, ০৭-০৮"),
  mcq(516,"12","'ডয়েচল্যান্ড' এর বর্তমান নাম কী?",["নেদারল্যান্ডস","পোল্যান্ড","অস্ট্রিয়া","জার্মানি"],"ঘ","সরকারি মাধ্যমিক সহকারী শিক্ষক, ০৮"),
  mcq(516,"13","'হল্যান্ড' কোন দেশের পুরাতন নাম?",["ইংল্যান্ড","নেদারল্যান্ডস","সুইডেন","নিউজিল্যান্ড"],"খ","দুর্নীতি দমন ব্যুরোর পরিদর্শক, ০৩"),
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : source.includes("BCS") ? ["Bangladesh Civil Service", null, "competitive", "bcs"] : source.startsWith("MAT") ? ["Medical Admission Test", null, "admission", "medical-admission"] : ["Other university and recruitment examination", null, "competitive", "other-recruitment"];
const quality = status => status === "verified" ? "externally-verified" : status === "conflicting" ? "conflicting" : "source-attributed";
const recordId = (kind, h) => kind === "fact" ? `(SELECT id FROM public.gk_facts WHERE canonical_hash = ${q(h)} LIMIT 1)` : kind === "note" ? `(SELECT id FROM public.gk_notes WHERE canonical_hash = ${q(h)} LIMIT 1)` : `(SELECT id FROM public.gk_mcqs WHERE canonical_hash = ${q(h)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(pageFiles.map(async file => JSON.parse(await fs.readFile(file, "utf8"))));
  const chapters = [[57,"পূর্বনাম ও বর্তমান নাম","former-current-names","Source-preserved historical country and place-name tables and past-exam MCQs.",515],[58,"বিভিন্ন দেশের বিখ্যাত বাসভবন","famous-residences","Source-preserved famous official-residence reference material.",517],[59,"বিভিন্ন দেশের সচিবালয়","government-offices","Source-preserved office and secretariat reference material.",518]];
  const topics = [["world-legislatures","আইনসভা সম্পর্কিত বিগত বছরের প্রশ্ন","legislature-past-exam-mcqs",514,3],["former-current-names","দেশ ও স্থানের নামের পরিবর্তন","historical-name-reference",515,1],["former-current-names","নাম পরিবর্তন সম্পর্কিত বিগত বছরের প্রশ্ন","historical-name-past-exam-mcqs",516,2],["famous-residences","বিখ্যাত সরকারি বাসভবন","official-residences-reference",517,1],["government-offices","সচিবালয় ও সরকারি কার্যালয়","secretariats-offices-reference",518,1]];
  const checks = [...facts.map(x=>({kind:"fact",...x,claim:x.fact_text})),...notes.map(x=>({kind:"note",...x,claim:x.content})),...mcqs.map(x=>({kind:"mcq",...x,claim:`${x.question} — printed answer: ${x.correct}`}))];
  const audit = { batch_pages:BATCH_PAGES,pipeline_version:PIPELINE_VERSION,source_pages:pages.map(p=>({page:p.source_page,review_status:p.review.review_status,image_sha256:p.source_image_sha256})),generated_facts:facts.length,generated_notes:notes.length,generated_mcqs:mcqs.length,generated_options:mcqs.length*4,generated_flashcards:facts.length+notes.length+mcqs.length,verification_counts:{verified:checks.filter(x=>x.status==="verified").length,conflicting:checks.filter(x=>x.status==="conflicting").length,source_attributed:checks.filter(x=>x.status==="source_attributed").length},source_anomalies:["Physical pages 514–518 retain separately recorded printed footers 457–461.","Page 515 retains source readings তুসাসিক, গিলব্রাট, and the unresolved source spelling মালাগাাসি.","Page 516 corrects source-reading metadata to MAT and জবি while preserving all printed answers.","Page 518 retains the Flushing Meadows UN claim with conflicting status rather than silently updating it."],quality_gates:["Exactly five physical pages 514–518 only.","All 25 ordered dense-image tiles reviewed.","MCQs retain four options, printed answer keys, and separate source metadata.","Structured tables remain notes, with status-marked facts kept separate."] };
  const chapterSql=`INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${vals(chapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
  const topicSql=`INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved and quality-gated reference material.',x.page::integer,x.ord::integer FROM (VALUES ${vals(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const pageSql=pages.map(p=>{const c=context(p.source_page);const printed={514:457,515:458,516:459,517:460,518:461}[p.source_page];const kind=[514,516].includes(p.source_page)?"mcq":"educational";const meta={source_image_sha256:p.source_image_sha256,extraction_model:p.model,review_status:p.review.review_status,corrections:p.review.corrections,unresolved_spans:p.review.unresolved_spans,accepted_content_tags:p.review.accepted_content_tags,physical_source_page:p.source_page,printed_book_page:printed,artifact_reported_page:p.transcription.source_page,visual_review_report:"/home/ubuntu/dontonyo/reports/batch-0514-0518_visual_review.md",external_verification_report:"/home/ubuntu/dontonyo/reports/batch-0514-0518_external_verification.md",page_number_mismatch:printed!==p.source_page?"Physical PDF page and visible printed footer are preserved separately.":null};return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${p.source_page},${q(kind)}::page_kind,${q(p.review.verified_transcript)},${q(c.title)},${q(c.topicTitle)},'high'::confidence_level,'vision_ocr_with_image_grounded_review',${q(p.model)},'Quality-gated extraction with ordered dense-image review and explicit verification status.',${json(meta)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${p.source_page});`;}).join("\n");
  const factSql=`WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${vals(facts.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.fact_text,x.status,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct external corroboration is recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'Source wording is retained; external evidence conflicts and is linked in the verification ledger.' ELSE 'Source-attributed material retained without silent factual revision.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql=`WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${vals(notes.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.content,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql=mcqs.map(x=>{const [name,institution,type,normal]=exam(x.source);const keys=["ক","খ","গ","ঘ"];const opts=x.options.map((o,i)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[i])},${q(o)},${i+1},${keys[i]===x.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[i])});`).join("\n");return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${x.source_page}.`)},${q(normal)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normal)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(x.question)},${q(x.correct)},'Printed answer key retained as source-attributed material; options and exam label were visually validated.',${x.source_page},'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন',${q(x.number)},3,${q(x.confidence)}::confidence_level,${q(x.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(x.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(x.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${opts} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normal)} LIMIT 1),NULL,${q(x.source)},${q(x.source)},${x.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(x.source)} AND s.source_page=${x.source_page});`;}).join("\n");
  const tagSql=`INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(x=>`(${x.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(x=>[quality(x.status),"government-offices",...(x.source_page===518?["time-sensitive"]:[])].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0514-0518-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(x=>{const domain=x.source_page===515?"historical-place-names":x.source_page===517?"famous-residences":"government-offices";return [domain,"reference-table","source-attributed","time-sensitive"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0514-0518-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n");}).join("\n")}\n${mcqs.map(x=>["past-exam-mcq","answer-key",x.source_page===514?"world-legislatures":"historical-place-names",exam(x.source)[3],"source-attributed"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0514-0518-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
  const verificationSql=checks.map(x=>`INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${x.source_page},${q(x.kind)},${recordId(x.kind,x.canonical_hash)},${q(x.claim)},NULL,${q(x.status)},${q(x.confidence)}::confidence_level,${json(x.sources)},${q(x.status==="verified"?"Direct external corroboration is listed in the batch verification ledger.":x.status==="conflicting"?"Source wording is retained with external counter-evidence; no silent correction was made.":"Image-grounded source record retained with explicit source attribution.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(x.kind)} AND v.entity_id=${recordId(x.kind,x.canonical_hash)} AND v.claim_text=${q(x.claim)});`).join("\n");
  const derived=`INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0514-0518:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 514 AND 518 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0514-0518:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0514-0518:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 514 AND 518 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0514-0518:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0514-0518:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page IN (514,516) AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0514-0518:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 514 AND 518 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 514 AND 518 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page IN (514,516) AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql=`-- Generated by prepare_validated_batch_0514_0518.mjs. Source pages 514–518 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(p=>p.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derived}\nCOMMIT;`;
  return {sql,audit};
}
if (process.argv[1]===fileURLToPath(import.meta.url)){const {sql,audit}=await buildBatch();await fs.mkdir(outputDir,{recursive:true});await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql);await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2));await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql}));console.log(JSON.stringify({outputDir,...audit},null,2));}
