import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0504-0508";
const outputDir = path.join(root, "supabase", "batch-0504-0508");
export const BATCH_PAGES = [504, 505, 506, 507, 508];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0504-0508-v1";
const BOOK_TITLE = "Jubayer's GK";
const pageFiles = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const sha = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(", ")})`).join(",\n");

const refs = {
  coinage1835: ["https://www.rbi.org.in/CommonPerson/english/currency/scripts/britishindia.aspx"],
  paper1861: ["https://www.rbi.org.in/commonman/english/Currency/Scripts/EarlyIssues.aspx"],
  greenback: ["https://home.treasury.gov/about/history/curator/treasury-and-the-civil-war-150th-anniversary"],
  bolivia: ["https://www.congress.gov/crs-product/R48767"],
};

const tags = [
  ["world-capitals-currencies", "World capitals and currencies", "domain", "Source-derived global capital-and-currency reference."],
  ["capital-currency-table", "Capital and currency table", "content_type", "Structured source table of country, capital, and currency."],
  ["currency-history", "Currency history and terminology", "content_type", "Source-derived monetary-history or terminology fact."],
  ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with printed exam metadata and answer key."],
  ["answer-key", "Answer key", "content_type", "Correct answer from the printed source answer key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved content without a direct external corroboration in this batch."],
  ["externally-verified", "Externally verified", "quality", "Claim corroborated by a direct external reference in the batch ledger."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka examination label as printed."],
  ["bcs", "BCS", "exam_source", "Bangladesh Civil Service examination label as printed."],
  ["medical-admission", "Medical admission", "exam_source", "Medical admission examination label as printed."],
  ["other-recruitment", "Other university and recruitment examination", "exam_source", "Other university or recruitment examination label as printed."],
];

const pageContext = page => {
  if (page === 504) return { chapter: "europe-capitals-currencies", topic: "europe-regional-capitals-currencies", chapterTitle: "ইউরোপ মহাদেশ", topicTitle: "ইউরোপের আঞ্চলিক রাজধানী ও মুদ্রা" };
  if (page === 505) return { chapter: "north-america-capitals-currencies", topic: "north-america-capitals-currencies", chapterTitle: "উত্তর আমেরিকা মহাদেশ", topicTitle: "উত্তর আমেরিকার রাজধানী ও মুদ্রা" };
  if (page === 506) return { chapter: "south-america-capitals-currencies", topic: "south-america-capitals-currencies", chapterTitle: "দক্ষিণ আমেরিকা মহাদেশ", topicTitle: "দক্ষিণ আমেরিকার রাজধানী ও মুদ্রা" };
  return { chapter: "asia-capitals-currencies", topic: "capitals-currencies-past-exam-mcqs", chapterTitle: "এশিয়া মহাদেশ", topicTitle: "এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন" };
};

function verify(page, text, kind = "fact") {
  if (page === 506 && text.includes("১৮৩৫")) return { status: "verified", confidence: "high", sources: refs.coinage1835 };
  if (page === 506 && text.includes("১৮৬১")) return { status: "verified", confidence: "medium", sources: refs.paper1861 };
  if (page === 506 && text.includes("Greenback")) return { status: "verified", confidence: "high", sources: refs.greenback };
  if (page === 506 && text.includes("বলিভিয়া")) return { status: "verified", confidence: "high", sources: refs.bolivia };
  return { status: "source_attributed", confidence: kind === "mcq" ? "high" : "medium", sources: [] };
}

const note = (source_page, title, content) => {
  const context = pageContext(source_page);
  const outcome = verify(source_page, content, "note");
  return { source_page, title, content, ...context, ...outcome, canonical_hash: sha(`note|${source_page}|${title}|${content}`) };
};
const notes = [
  note(504, "দক্ষিণ-পূর্ব ইউরোপ বা বলকান উপদ্বীপের ১১টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nআলবেনিয়া | তিরানা | লেক\nবুলগেরিয়া | সোফিয়া | ইউরো\nবসনিয়া ও হার্জেগোভিনা | সারায়েভো | কনভার্টিবল মার্ক\nক্রোয়েশিয়া | জাগরেব | ইউরো\nকসোভো | প্রিস্টিনা | ইউরো\nগ্রিস | এথেন্স | ইউরো\nউত্তর মেসিডোনিয়া | স্কোপজে | দিনার\nসার্বিয়া | বেলগ্রেড | দিনার\nমন্টিনিগ্রো | পোডগোরিকো | ইউরো\nরুমানিয়া | বুখারেস্ট | লিউ\nস্লোভেনিয়া | লুবজানা | ইউরো"),
  note(504, "মধ্য ইউরোপের ৮টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nজার্মানি | বার্লিন | ইউরো\nপোল্যান্ড | ওয়ারস | জ্লোটি\nঅস্ট্রিয়া | ভিয়েনা | ইউরো\nহাঙ্গেরি | বুদাপেস্ট | ফরিন্ট\nসুইজারল্যান্ড | বার্ন | ফ্রাংক\nলিচটেনস্টেইন | ভাজাউজ | সুইস ফ্রাংক\nচেক রিপাবলিক | প্রাগ | চেক ক্রাউন\nস্লোভাকিয়া | ব্রাতিশ্লাভা | ইউরো"),
  note(504, "ট্রান্স ককেশিয়ান অঞ্চলের ৩টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nজর্জিয়া | তিবলিসি | লারি\nআজারবাইজান | বাকু | মানাত\nআর্মেনিয়া | ইয়েরেভান | ড্রাম"),
  note(505, "পশ্চিম ভারতীয় দ্বীপপুঞ্জ বা ক্যারিবিয়ান দ্বীপপুঞ্জ অঞ্চলের ১৩টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nহাইতি | পোর্ট অ প্রিন্স | গুর্দে\nকিউবা | হাভানা | পেসো\nডোমিনিকান প্রজাতন্ত্র | সেন্টো ডোমিনিনগো | পেসো\nডোমিনিকা | রোজাও | ডলার\nএন্টিগুয়া ও বারমুডা | সেন্ট জনস | ডলার\nবাহামাস | নাসাউ | ডলার\nবার্বাডোস | ব্রিজটাউন | ডলার\nগ্রানাডা | সেন্ট জর্জেস | ডলার\nজ্যামাইকা | কিংস্টন | ডলার\nসেন্ট কিটস ও নেভিস | বাসোতোর | ডলার\nসেন্ট লুসিয়া | কাসটায়ার | ডলার\nত্রিনিদাদ ও টোবাগো | পোর্ট অব স্পেন | ডলার\nসেন্ট ভিনসেন্ট এন্ড দ্যা গ্রানডাইস | কিংসটাউন | ডলার"),
  note(505, "মধ্য আমেরিকা অঞ্চলের ৭টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nবেলিজ | বেলমোপান | ডলার\nপানামা | পানামাসিটি | বালবোয়া\nগুয়েতেমালা | গুয়েতেমালা সিটি | কুয়েতজাল\nনিকারাগুয়া | ম্যানাগুয়া | কর্ডোবা\nকোস্টারিকা | স্যানজোসে | কোলন\nএল সালভাদর | স্যানসালভাদর | মার্কিন ডলার/কোলন\nহন্ডুরাস | তেগুচিগালপা | লেম্পিরা"),
  note(505, "উত্তর আমেরিকা অঞ্চলের ৩টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nকানাডা | অটোয়া | ডলার\nযুক্তরাষ্ট্র | ওয়াশিংটন ডিসি | ডলার\nমেক্সিকো | মেক্সিকো সিটি | পেসো"),
  note(506, "দক্ষিণ আমেরিকা অঞ্চলের ১২টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nব্রাজিল | ব্রাসিলিয়া | রিয়াল\nসুরিনাম | প্যারামারিবো | ডলার\nগায়ানা | জর্জ টাউন | ডলার\nআর্জেন্টিনা | বুয়েন্স আয়ার্স | পেসো\nকলম্বিয়া | বোগোতা | পেসো\nবলিভিয়া | লাপাজ (প্রশাসনিক); সুক্রে (সাংবিধানিক) | বলিভিয়ানো\nপেরু | লিমা | সোল\nউরুগুয়ে | মন্টিভিডিও | পেসো\nপ্যারাগুয়ে | আসুনসিওন | গুয়ারানি\nইকুয়েডর | কিটো | ডলার\nভেনেজুয়েলা | কারাকাস | বলিভার\nচিলি | সান্টিয়াগো | পেসো"),
  note(506, "ওশেনিয়া মহাদেশের ১৩টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nঅস্ট্রেলিয়া | ক্যানবেরা | ডলার\nসামোয়া | আপিয়া | তালা\nটুভালু | ফুনাফুটি | ডলার\nনিউজিল্যান্ড | ওয়েলিংটন | ডলার\nটোঙ্গা | নুকুয়ালোফা | পাআঙ্গা\nসলোমন দ্বীপপুঞ্জ | হনিয়ারা | ডলার\nফিজি | সুভা | ডলার\nপাপুয়া নিউগিনি | পোর্ট মোর্সবি | কিনা\nভানুয়াতু | পোর্ট ভিলা | ভাতু\nনাউরু | ইয়ারেন | ডলার\nকিরিবাতি | তারাওয়া | ডলার\nপালাউ | এনগেরুলমুদ | ডলার\nমার্শাল দ্বীপপুঞ্জ | মাজুরো | ডলার"),
];

const fact = (title, fact_text) => { const context = { chapter: "currency-reference", topic: "currency-history-reference" }; const outcome = verify(506, fact_text); return { source_page: 506, title, fact_text, ...context, ...outcome, canonical_hash: sha(`fact|506|${title}|${fact_text}`) }; };
const facts = [
  fact("মুদ্রা সম্পর্কিত তথ্য", "উপমহাদেশের প্রথম মুদ্রা আইন পাস হয়- ১৮৩৫ সালে।"),
  fact("মুদ্রা সম্পর্কিত তথ্য", "উপমহাদেশে প্রথম কাগজের মুদ্রা চালু হয়- ১৮৬১ সালে (চালু করেন- লর্ড ক্যানিং)।"),
  fact("মুদ্রা সম্পর্কিত তথ্য", "প্রথম ডিজিটাল মুদ্রার নাম- বিট কয়েন।"),
  fact("মুদ্রা সম্পর্কিত তথ্য", "মুদ্রা সংকট পরিচিত- এশিয়ান কনট্যাগিয়ন নামে।"),
  fact("মুদ্রা সম্পর্কিত তথ্য", "ডলারের এক শতাংশের নাম- সেন্ট; Green Money বলা হয়- ডলারকে।"),
  fact("মুদ্রা সম্পর্কিত তথ্য", "মার্কিন গৃহযুদ্ধের সময় আব্রাহাম লিংকন যুক্তরাষ্ট্রে চালু করেছিলেন- Greenback."),
];

const mcq = (source_page, number, question, options, correct, source) => { const outcome = verify(source_page, question, "mcq"); return { source_page, number, question, options, correct, source, ...outcome, canonical_hash: sha(`mcq|${source_page}|${number}|${question}`) }; };
const mcqs = [
  mcq(507, "01", "হেলসিংকি কোন দেশের রাজধানী?", ["সুইডেন", "ফিনল্যান্ড", "পোল্যান্ড", "নরওয়ে"], "খ", "DU খ ১৬-১৭"),
  mcq(507, "02", "দেশ ও রাজধানীর একই নাম-", ["তাইওয়ান", "উগান্ডা", "জিবুতি", "কোস্টারিকা"], "গ", "DU খ ০৯-১০"),
  mcq(507, "03", "নিকারাগুয়ার রাজধানী-", ["মানামা", "কারাকাস", "সালভাদর", "মানাগুয়া"], "ঘ", "DU ঘ ০৮-০৯"),
  mcq(507, "04", "আলবেনিয়ার রাজধানী-", ["মিলান", "জেনেভা", "প্রাগ", "তিরানা"], "ঘ", "DU ঘ ০৫-০৬"),
  mcq(507, "05", "পোর্ট অব স্পেন কোন দেশের রাজধানী?", ["স্পেন", "কিউবা", "ত্রিনিদাদ", "কোনটি নয়"], "গ", "DU খ ৯৬-৯৭"),
  mcq(507, "06", "কোনটি দক্ষিণ সুদানের রাজধানী?", ["জুবা", "মালাকাল", "টরিট", "ওয়ারাপ"], "ক", "DU ঘ ১১-১২"),
  mcq(507, "07", "মিয়ানমারের রাজধানীর নাম-", ["নাইপিডো", "ইয়াংগুন", "ম্যানডালে", "বাগান"], "ক", "DU ঘ ১২-১৩"),
  mcq(507, "08", "উজবেকিস্তানের মুদ্রার নাম-", ["সোম", "রুবল", "ডলার", "মানাত"], "ক", "DU ঘ ০৪-০৫"),
  mcq(507, "09", "নরওয়ের মুদ্রার নাম-", ["ইউরো", "গিন্ডার", "ক্রোন", "লিরা"], "গ", "DU খ ১০-১১"),
  mcq(507, "10", "ভিয়েতনামের মুদ্রার নাম-", ["ইউয়ান", "ইয়েন", "ডং", "ক্বিপ"], "গ", "DU খ ০৭-০৮"),
  mcq(507, "11", "চীনের মুদ্রার নাম-", ["ফ্রাঁ", "ইউয়ান", "তুয়ান", "ইয়েন"], "খ", "DU খ ০৬-০৭, ঘ ০৩-০৪"),
  mcq(507, "12", "ঘানা'র মুদ্রার নাম-", ["ইউয়ান", "সেডি", "তুয়ান", "পুলা"], "খ", "DU খ ১২-১৩"),
  mcq(507, "13", "পোল্যান্ডের মুদ্রার নাম-", ["পেসো", "জলোটি", "করুনা", "ইউরো"], "খ", "DU ঘ ১৩-১৪"),
  mcq(507, "14", "ওমানের মুদ্রার নাম-", ["ডলার", "দিরহাম", "রিয়াল", "দিনার"], "গ", "DU খ ১৩-১৪"),
  mcq(507, "15", "মাদাগাস্কারের রাজধানীর নাম-", ["আনতানানারিভো", "পারামারিবে", "মাসেরু", "আঞ্জনা"], "ক", "DU ঘ ১৩-১৪"),
  mcq(508, "16", "নামিবিয়ার রাজধানী-", ["প্রিটোরিয়া", "উইন্ডহোক", "করাডু", "কোটাভি"], "খ", "11 BCS"),
  mcq(508, "17", "তিমুর লিসতের রাজধানী-", ["মালে", "থিম্পু", "দিলি", "উলানবাটোর"], "গ", "15 BCS, 32 BCS"),
  mcq(508, "18", "দক্ষিণ কোরিয়ার মুদ্রার নাম কী?", ["ইয়েন", "পেসো", "ইউয়ান", "ওন"], "ঘ", "14 BCS"),
  mcq(508, "19", "মালদ্বীপের মুদ্রার নাম কী?", ["পাউন্ড", "ডলার", "রুপি", "রুপাইয়া"], "ঘ", "11 BCS"),
  mcq(508, "20", "'নাসাউ' কোন দ্বীপপুঞ্জের রাজধানী?", ["ফিজি", "নিকোবর", "মাদাগাস্কার", "বাহামা"], "ঘ", "MC ০৫-০৬"),
  mcq(508, "21", "নেদারল্যান্ডের মুদ্রার নাম কী?", ["পেসো", "ডলার", "ইউরো", "পাউন্ড"], "গ", "MC ০৩-০৪"),
  mcq(508, "22", "সুইজারল্যান্ডের মুদ্রার নাম কী?", ["ডলার", "মার্ক", "ফ্রাংক", "লিরা"], "গ", "MC ০৪-০৫"),
  mcq(508, "23", "কাতারের রাজধানী-", ["দুবাই", "দোহা", "শারজা", "আবুধাবি"], "খ", "Bangladesh Rural Deve. Board officer-04"),
  mcq(508, "24", "আদ্দিস আবাবা কোন দেশের রাজধানী?", ["রোমানিয়া", "ইথিওপিয়া", "দক্ষিণ আফ্রিকা", "উরুগুয়ে"], "খ", "বাংলাদেশ কৃষি ব্যাংক, ০৭"),
  mcq(508, "25", "ডাকার কোন দেশের রাজধানী?", ["সেনেগাল", "শাদ", "মালাউই", "বেনিন"], "ক", "তুলা উন্নয়ন বোর্ড-০৬"),
  mcq(508, "26", "পোর্ট অব প্রিন্স কোন দেশের রাজধানী?", ["ত্রিনিদাদ", "হাইতি", "কোস্টারিকা", "বারবাডোস"], "খ", "তথ্য মন্ত্রণালয়ের সহকারী পরিচালক, ০৩"),
  mcq(508, "27", "কারাকাস কোন দেশের রাজধানী?", ["হন্ডুরাস", "ভেনিজুয়েলা", "চেক-রিপাবলিক", "লিথুনিয়া"], "খ", "বাংলাদেশ ব্যাংক-০৬"),
  mcq(508, "28", "The capital city of Bhutan is-", ["থিম্পু", "কাঠমান্ডু", "গ্যাংটক", "কলম্বো"], "ক", "Bangladesh Bank Assistant Director: 08"),
  mcq(508, "29", "শ্রীলঙ্কার রাজধানী-", ["হ্যানয়", "শ্রী জয়বর্ধনেপুর কোট্টে", "রেঙ্গুন", "সায়গন"], "খ", "খাদ্য অধিদপ্তরের পরিদর্শক, ৯৩"),
  mcq(508, "30", "সৌদি আরবের রাজধানী-", ["জেদ্দা", "মক্কা", "মদিনা", "রিয়াদ"], "ঘ", "Sonali, Janata, Agrani and Rupali Bank Senior Officer, 99"),
];

function examInfo(source) {
  if (source.includes("DU")) return ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"];
  if (source.includes("BCS")) return ["Bangladesh Civil Service", null, "competitive", "bcs"];
  if (source.startsWith("MC")) return ["Medical Admission", null, "admission", "medical-admission"];
  return ["Other university and recruitment examination", null, "competitive", "other-recruitment"];
}
function recordLookup(type, hash) { if (type === "fact") return `(SELECT id FROM public.gk_facts WHERE canonical_hash = ${q(hash)} LIMIT 1)`; if (type === "note") return `(SELECT id FROM public.gk_notes WHERE canonical_hash = ${q(hash)} LIMIT 1)`; return `(SELECT id FROM public.gk_mcqs WHERE canonical_hash = ${q(hash)} LIMIT 1)`; }
function qualityTag(status) { return status === "verified" ? "externally-verified" : "source-attributed"; }
function pageMetadata(page) { const printed = { 504: 447, 505: 448, 506: 449, 507: 450, 508: 451 }[page.source_page]; return { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, accepted_content_tags: page.review.accepted_content_tags, physical_source_page: page.source_page, printed_book_page: printed, artifact_reported_page: page.transcription.source_page, visual_review_report: "/home/ubuntu/dontonyo/reports/batch-0504-0508_visual_review.md", external_verification_report: "/home/ubuntu/dontonyo/reports/batch-0504-0508_external_verification.md", page_number_mismatch: printed !== page.source_page ? "Physical PDF page and printed source footer are separately preserved." : null }; }

export async function buildBatch() {
  const pages = await Promise.all(pageFiles.map(async file => JSON.parse(await fs.readFile(file, "utf8"))));
  const checks = [...facts.map(row => ({ type: "fact", hash: row.canonical_hash, source_page: row.source_page, claim: row.fact_text, normalized: row.fact_text, status: row.status, confidence: row.confidence, sources: row.sources })), ...notes.map(row => ({ type: "note", hash: row.canonical_hash, source_page: row.source_page, claim: row.content, normalized: row.content, status: row.status, confidence: row.confidence, sources: row.sources })), ...mcqs.map(row => ({ type: "mcq", hash: row.canonical_hash, source_page: row.source_page, claim: `${row.question} — printed answer: ${row.correct}`, normalized: null, status: row.status, confidence: row.confidence, sources: row.sources }))];
  const chapters = [["উত্তর আমেরিকা মহাদেশ", "north-america-capitals-currencies", "Source-preserved North American capital-and-currency reference tables.", 505, 51], ["দক্ষিণ আমেরিকা মহাদেশ", "south-america-capitals-currencies", "Source-preserved South American capital-and-currency reference tables.", 506, 52], ["ওশেনিয়া মহাদেশ", "oceania-capitals-currencies", "Source-preserved Oceania capital-and-currency reference table.", 506, 53], ["মুদ্রা সম্পর্কিত তথ্য", "currency-reference", "Source-preserved currency history and terminology material.", 506, 54]];
  const chapterSql = `INSERT INTO public.chapters (book_id, chapter_number, title, slug, description, source_page, display_order) SELECT b.id, x.n::integer, x.title, x.slug, x.description, x.source_page::integer, x.n::integer FROM (VALUES ${values(chapters.map(row => [row[4], row[0], row[1], row[2], row[3]]))}) AS x(n, title, slug, description, source_page) JOIN public.books b ON b.title = ${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id = b.id AND c.slug = x.slug);`;
  const topics = [["north-america-capitals-currencies", "উত্তর আমেরিকার রাজধানী ও মুদ্রা", "north-america-capitals-currencies", 505, 1], ["south-america-capitals-currencies", "দক্ষিণ আমেরিকার রাজধানী ও মুদ্রা", "south-america-capitals-currencies", 506, 1], ["oceania-capitals-currencies", "ওশেনিয়ার রাজধানী ও মুদ্রা", "oceania-capitals-currencies", 506, 1], ["currency-reference", "মুদ্রা সম্পর্কিত তথ্য বৈচিত্র্য", "currency-history-reference", 506, 1], ["asia-capitals-currencies", "রাজধানী ও মুদ্রা সম্পর্কিত বিগত বছরের প্রশ্ন", "capitals-currencies-past-exam-mcqs", 507, 3]];
  const topicSql = `INSERT INTO public.topics (chapter_id, title, slug, description, source_page, display_order) SELECT c.id, x.title, x.slug, 'Source-derived capital-and-currency reference material with explicit verification status.', x.source_page::integer, x.display_order::integer FROM (VALUES ${values(topics)}) AS x(chapter_slug, title, slug, source_page, display_order) JOIN public.chapters c ON c.slug = x.chapter_slug AND c.book_id = (SELECT id FROM public.books WHERE title = ${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id = c.id AND t.slug = x.slug);`;
  const pagesSql = pages.map(page => { const context = pageContext(page.source_page); const kind = page.source_page === 506 ? "mixed" : page.source_page >= 507 ? "mcq" : "educational"; return `INSERT INTO public.source_pages (import_run_id, book_id, source_page, page_kind, raw_transcription, chapter_heading, topic_heading, confidence, extraction_method, model_name, notes, review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version = ${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1), b.id, ${page.source_page}, ${q(kind)}::page_kind, ${q(page.review.verified_transcript)}, ${q(context.chapterTitle)}, ${q(context.topicTitle)}, 'high'::confidence_level, 'vision_ocr_with_image_grounded_review', ${q(page.model)}, 'Quality-gated source extraction with ordered tile review, semantic separation, and explicit verification status.', ${json(pageMetadata(page))} FROM public.books b WHERE b.title = ${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id = b.id AND s.source_page = ${page.source_page});`; }).join("\n");
  const factsSql = `WITH d(source_page, chapter_slug, topic_slug, title, fact_text, confidence, canonical_hash, status) AS (VALUES\n${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.confidence, row.canonical_hash, row.status]))}) INSERT INTO public.gk_facts (book_id, chapter_id, topic_id, title, fact_text, explanation, source_page, source_section, source_excerpt, importance, confidence, canonical_hash) SELECT b.id, c.id, t.id, d.title, d.fact_text, CASE d.status WHEN 'verified' THEN 'Directly corroborated by an authority listed in the batch verification ledger; original wording is retained.' ELSE 'Source-attributed material retained with explicit source linkage and no silent factual update.' END, d.source_page::integer, d.title, d.fact_text, 3, d.confidence::confidence_level, d.canonical_hash FROM d JOIN public.books b ON b.title = ${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id = b.id AND c.slug = d.chapter_slug JOIN public.topics t ON t.chapter_id = c.id AND t.slug = d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text = EXCLUDED.fact_text, explanation = EXCLUDED.explanation, confidence = EXCLUDED.confidence;`;
  const notesSql = `WITH d(source_page, chapter_slug, topic_slug, title, content, confidence, canonical_hash) AS (VALUES\n${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id, chapter_id, topic_id, title, content, source_page, source_section, display_order, confidence, canonical_hash) SELECT b.id, c.id, t.id, d.title, d.content, d.source_page::integer, d.title, d.source_page::integer, d.confidence::confidence_level, d.canonical_hash FROM d JOIN public.books b ON b.title = ${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id = b.id AND c.slug = d.chapter_slug JOIN public.topics t ON t.chapter_id = c.id AND t.slug = d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content = EXCLUDED.content, confidence = EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name, institution, exam_type, normalized] = examInfo(row.source); const context = pageContext(row.source_page); const keys = ["ক", "খ", "গ", "ঘ"]; const optionsSql = row.options.map((option, index) => `INSERT INTO public.gk_mcq_options (mcq_id, option_key, option_text, display_order, is_correct) SELECT m.id, ${q(keys[index])}, ${q(option)}, ${index + 1}, ${keys[index] === row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash = ${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id = m.id AND o.option_key = ${q(keys[index])});`).join("\n"); return `INSERT INTO public.exam_sources (name, institution, exam_type, description, normalized_name) SELECT ${q(name)}, ${q(institution)}, ${q(exam_type)}, ${q(`Normalized from printed source label on page ${row.source_page}.`)}, ${q(normalized)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name = ${q(normalized)}); INSERT INTO public.gk_mcqs (book_id, chapter_id, topic_id, question, correct_option, explanation, source_page, source_section, source_question_number, difficulty, confidence, canonical_hash) SELECT b.id, c.id, t.id, ${q(row.question)}, ${q(row.correct)}, 'Printed answer key retained as source-attributed material; question/options and exam metadata were visually validated.', ${row.source_page}, 'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন', ${q(row.number)}, 3, ${q(row.confidence)}::confidence_level, ${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id = b.id AND c.slug = ${q(context.chapter)} JOIN public.topics t ON t.chapter_id = c.id AND t.slug = ${q(context.topic)} WHERE b.title = ${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option = EXCLUDED.correct_option, explanation = EXCLUDED.explanation, confidence = EXCLUDED.confidence; ${optionsSql} INSERT INTO public.gk_mcq_sources (mcq_id, exam_source_id, year, session, source_text, source_page) SELECT m.id, (SELECT id FROM public.exam_sources WHERE normalized_name = ${q(normalized)} LIMIT 1), NULL, ${q(row.source)}, ${q(row.source)}, ${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash = ${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id = m.id AND s.source_text = ${q(row.source)} AND s.source_page = ${row.source_page});`; }).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug, label, category, description) VALUES\n${tags.map(tag => `(${tag.map(q).join(", ")})`).join(",\n")} ON CONFLICT (slug) DO UPDATE SET label = EXCLUDED.label, category = EXCLUDED.category, description = EXCLUDED.description;\n${facts.map(row => ["currency-history", qualityTag(row.status)].map(tag => `INSERT INTO public.content_tag_assignments (tag_id, entity_type, entity_id, source_page, confidence, assigned_by) SELECT t.id, 'fact', f.id, ${row.source_page}, ${q(row.confidence)}::confidence_level, 'batch-0504-0508-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash = ${q(row.canonical_hash)} WHERE t.slug = ${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(row => ["capital-currency-table", qualityTag(row.status)].map(tag => `INSERT INTO public.content_tag_assignments (tag_id, entity_type, entity_id, source_page, confidence, assigned_by) SELECT t.id, 'note', n.id, ${row.source_page}, ${q(row.confidence)}::confidence_level, 'batch-0504-0508-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash = ${q(row.canonical_hash)} WHERE t.slug = ${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${mcqs.map(row => ["past-exam-mcq", "answer-key", examInfo(row.source)[3], qualityTag(row.status)].map(tag => `INSERT INTO public.content_tag_assignments (tag_id, entity_type, entity_id, source_page, confidence, assigned_by) SELECT t.id, 'mcq', m.id, ${row.source_page}, ${q(row.confidence)}::confidence_level, 'batch-0504-0508-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash = ${q(row.canonical_hash)} WHERE t.slug = ${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
  const verificationSql = checks.map(row => { const id = recordLookup(row.type, row.hash); return `INSERT INTO public.fact_verifications (source_page, entity_type, entity_id, claim_text, normalized_claim, verification_status, confidence, verification_sources, audit_note) SELECT ${row.source_page}, ${q(row.type)}, ${id}, ${q(row.claim)}, ${row.normalized ? q(row.normalized) : "NULL"}, ${q(row.status)}, ${q(row.confidence)}::confidence_level, ${json(row.sources)}, ${q(row.status === "verified" ? "Direct external corroboration is listed in the batch verification ledger." : "Source-attributed record retained with visual validation and explicit source linkage; no silent factual update.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type = ${q(row.type)} AND v.entity_id = ${id} AND v.claim_text = ${q(row.claim)});`; }).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id, book_id, chapter_id, topic_id, front_text, back_text, source_type, source_id, source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1), f.book_id, f.chapter_id, f.topic_id, f.title, f.fact_text, 'fact', f.id, 'batch0504-0508:fact:' || f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 504 AND 508 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key = 'batch0504-0508:fact:' || f.id::text); INSERT INTO public.flashcards (subject_id, book_id, chapter_id, topic_id, front_text, back_text, source_type, source_id, source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1), n.book_id, n.chapter_id, n.topic_id, n.title, n.content, 'note', n.id, 'batch0504-0508:note:' || n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 504 AND 508 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key = 'batch0504-0508:note:' || n.id::text); INSERT INTO public.flashcards (subject_id, book_id, chapter_id, topic_id, front_text, back_text, source_type, source_id, source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1), m.book_id, m.chapter_id, m.topic_id, m.question, 'সঠিক উত্তর: ' || o.option_key || '. ' || o.option_text, 'mcq', m.id, 'batch0504-0508:mcq:' || m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id = m.id AND o.is_correct WHERE m.source_page IN (507, 508) AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key = 'batch0504-0508:mcq:' || m.id::text); INSERT INTO public.search_documents (entity_type, entity_id, title, body, english_metadata) SELECT 'fact', f.id, f.title, f.fact_text, 'Source-linked GK fact | page ' || f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 504 AND 508 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type = 'fact' AND d.entity_id = f.id); INSERT INTO public.search_documents (entity_type, entity_id, title, body, english_metadata) SELECT 'note', n.id, n.title, n.content, 'Capital-and-currency reference table | page ' || n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 504 AND 508 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type = 'note' AND d.entity_id = n.id); INSERT INTO public.search_documents (entity_type, entity_id, title, body, english_metadata) SELECT 'mcq', m.id, NULL, m.question, 'Past-exam MCQ | page ' || m.source_page::text || ' | question ' || m.source_question_number FROM public.gk_mcqs m WHERE m.source_page IN (507, 508) AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type = 'mcq' AND d.entity_id = m.id);`;
  const audit = { batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION, source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256 })), generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length, verification_counts: { verified: checks.filter(row => row.status === "verified").length, source_attributed: checks.filter(row => row.status === "source_attributed").length }, source_anomalies: ["Physical PDF pages 504–508 have printed source footers 447–451.", "Page 508 OCR correction: Dakar (ডাকার), not Dhaka (ঢাকার).", "MCQ answers are sourced from visually validated printed answer keys; not inferred.", "Source-specific capital-role and terminology wording is preserved without silent normalization."], quality_gates: ["Five physical PDF pages only; stop before page 509.", "All 25 dense-image tiles were reviewed in manifest order.", "Facts, tables, MCQs, four options, answer keys, and exam metadata remain relationally distinct.", "All generated records are idempotent by source page, canonical hash, or source key."] };
  const sql = `-- Generated by scripts/prepare_validated_batch_0504_0508.mjs\n-- Source pages: 504–508 only. Stop before page 509.\nBEGIN;\nINSERT INTO public.import_runs (source_filename, source_sha256, pipeline_version, status, completed_at, audit) VALUES ('Jubayer''sgk.pdf', ${q(sha(pages.map(page => page.source_image_sha256).join("|")))}, ${q(PIPELINE_VERSION)}, 'completed', now(), ${json(audit)});\n${chapterSql}\n${topicSql}\n${pagesSql}\n${factsSql}\n${notesSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) { const { sql, audit } = await buildBatch(); await fs.mkdir(outputDir, { recursive: true }); await fs.writeFile(path.join(outputDir, "validated_import.sql"), sql); await fs.writeFile(path.join(outputDir, "batch_audit.json"), JSON.stringify(audit, null, 2)); await fs.writeFile(path.join(outputDir, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql })); console.log(JSON.stringify({ outputDir, ...audit }, null, 2)); }
