import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const work = "/home/ubuntu/dontonyo-work/batch-0749-0753";
const out = path.join(root, "supabase", "batch-0749-0753");
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const j = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => createHash("sha256").update(value).digest("hex");
export const BATCH_PAGES = [749, 750, 751, 752, 753];
export const PIPELINE_VERSION = "local-ocr-quality-gated-batch-0749-0753-v1";

export async function buildBatch() {
  const content = JSON.parse(await fs.readFile(path.join(out, "approved_content.json"), "utf8"));
  const pages = await Promise.all(BATCH_PAGES.map(async page => ({ page, sha256: hash(await fs.readFile(path.join(work, "rendered", `page_${String(page).padStart(4, "0")}.jpg`)),), raw: await fs.readFile(path.join(work, "ocr", `page_${String(page).padStart(4, "0")}.txt`), "utf8") })));
  const audit = { batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION, generated_facts: 0, generated_notes: 0, generated_mcqs: 0, generated_options: 0, generated_flashcards: 0, source_pages: pages.map(p => ({ page: p.page, review_status: "completed_image_grounded_review", image_sha256: p.sha256, overall_confidence: "medium" })), verification_counts: { verified: 0, conflicting: 0, source_attributed: 0 }, source_anomalies: ["All 35 ordered overlap-safe source tiles were reviewed.", "Local OCR was reconciled with visual evidence.", "Pages 750 and 753 contain visually confirmed printed corrections; all political, diplomatic, religious, ideological, security-sensitive, military, constitutional, colonial, institutional, membership, leadership, policy, legal, ranking, location, date, and current-status claims were withheld."], quality_gates: ["Only source pages 749–753 are included.", "No facts, notes, or MCQs are included because no reviewed source claim clears the conservative quality and safety boundary.", "Only allowed tag categories are inserted.", "Only reviewed source-page provenance and source-page topic boundaries are admitted."] };
  const topicSql = content.topics.map(t => `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,${q(t.title)},${q(t.slug)},'Source-derived content with completed visual review, conservative classification, and recorded verification.',${t.page},${t.order} FROM public.chapters c JOIN public.books b ON b.id=c.book_id WHERE b.title='Jubayer''s GK' AND c.slug='europe' AND NOT EXISTS (SELECT 1 FROM public.topics x WHERE x.chapter_id=c.id AND x.slug=${q(t.slug)});`).join("\n");
  const pageSql = pages.map(p => { const topic = content.topics.find(t => t.page === p.page).slug; const metadata = { physical_source_page: p.page, source_image_sha256: p.sha256, review_status: "completed_image_grounded_review", review_report: `${out}/visual_review_749_753.md`, classification_report: `${out}/classification_decisions.md`, verification_report: `${out}/external_verification.md`, recovery_artifacts: [`page_${String(p.page).padStart(4, "0")}.txt`], orientation_note: "Rendered source image visually verified upright before local OCR." }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${p.page},'educational'::page_kind,${q(p.raw)},'World history',${q(topic)},'medium'::confidence_level,'local_ocr_with_image_grounded_review','tesseract-ben+eng','All ordered source tiles reviewed; upright OCR reconciled with visual evidence; only classified records imported.',${j(metadata)} FROM public.books b WHERE b.title='Jubayer''s GK' AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${p.page});`; }).join("\n");
  const tags = [["world-history","World history","domain","Historically scoped world-reference material."],["reference-note","Structured source note","content_type","Bounded source reference with caveats."],["source-attributed","Source-attributed","quality","Source-preserved record without direct corroboration in this batch."],["externally-verified","Externally verified","quality","Directly corroborated record."],["historic-scope","Historic scope","quality","Historic political, institutional, or diplomatic reference."]];
  const derived = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0749-0753:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 749 AND 753 AND NOT EXISTS (SELECT 1 FROM public.flashcards z WHERE z.source_key='batch0749-0753:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0749-0753:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 749 AND 753 AND NOT EXISTS (SELECT 1 FROM public.flashcards z WHERE z.source_key='batch0749-0753:note:'||n.id::text);`;
  const sql = `-- Generated by prepare_validated_batch_0749_0753.mjs. Source pages 749–753 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(p => p.sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${j(audit)});\n${topicSql}\n${pageSql}\nINSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row => `(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${derived}\nCOMMIT;`;
  return { sql, audit, counts: { batch_pages: BATCH_PAGES, review_tiles: 35, eligible_facts: 0, eligible_notes: 0, eligible_mcqs: 0, eligible_mcq_options: 0, withheld_mcqs: 0, derived_records: 0, verification_statuses: audit.verification_counts } };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { const { sql, audit, counts } = await buildBatch(); await fs.mkdir(out, { recursive: true }); await fs.writeFile(path.join(out, "validated_import.sql"), sql); await fs.writeFile(path.join(out, "batch_audit.json"), JSON.stringify(audit, null, 2)); await fs.writeFile(path.join(out, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql })); await fs.writeFile(path.join(work, "import_input_counts.json"), JSON.stringify(counts, null, 2)); }
