import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0519-0523";
const outputDir = path.join(root, "supabase", "batch-0519-0523");
export const BATCH_PAGES = [519, 520, 521, 522, 523];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0519-0523-v1";
const BOOK_TITLE = "Jubayer's GK";
const pageFiles = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = text => crypto.createHash("sha256").update(text, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(", ")})`).join(",\n");
const refs = { bhutanFlower: ["https://nbc.gov.bt/the-national-flower-of-bhutan-found-to-be-a-new-species/"], bhutanBird: ["https://www.visitbhutan.com/page.php?id=18"] };
const tags = [
  ["national-symbols", "National symbols", "domain", "Source-derived national-symbol reference material."],
  ["geographical-aliases", "Geographical aliases", "domain", "Source-derived geographical-alias reference material."],
  ["reference-table", "Reference table", "content_type", "Structured source table retained as a note."],
  ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with printed examination label and answer key."],
  ["answer-key", "Answer key", "content_type", "Correct answer recorded from the printed source answer key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."],
  ["externally-verified", "Externally verified", "quality", "Claim directly corroborated by an external authority."],
  ["conflicting", "Conflicting external evidence", "quality", "Source claim conflicts with credible external evidence and is retained without silent correction."],
  ["time-sensitive", "Time-sensitive reference", "quality", "Historical or changing reference material requiring future review."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka examination label as printed."],
  ["other-recruitment", "Other recruitment examination", "exam_source", "Other university, bank, or recruitment examination label as printed."],
];
const ctx = page => page <= 520 ? { chapter: "national-symbols", topic: page === 520 ? "national-symbols-past-exam-mcqs" : "national-symbols-reference", title: "বিভিন্ন দেশের জাতীয় প্রতীক", topicTitle: page === 520 ? "এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন" : "বিভিন্ন দেশের জাতীয় প্রতীক" } : { chapter: "geographical-aliases", topic: page === 523 ? "city-geographical-aliases" : page === 522 ? "country-geographical-aliases" : "world-continent-europe-aliases", title: "ভৌগোলিক উপনাম", topicTitle: page === 523 ? "শহর/নগরী" : page === 522 ? "দেশ ও হাজার" : "বিশ্ব/পৃথিবী, মহাদেশ ও ইউরোপ" };
const note = (page, title, content, confidence = "medium") => ({ source_page: page, title, content, ...ctx(page), status: "source_attributed", confidence, sources: [], canonical_hash: hash(`note|${page}|${title}|${content}`) });
const fact = (page, title, text, status, confidence, sources) => ({ source_page: page, title, fact_text: text, ...ctx(page), status, confidence, sources, canonical_hash: hash(`fact|${page}|${title}|${text}`) });
const notes = [
  note(519, "বিভিন্ন দেশের জাতীয় প্রতীক", "দেশ | উৎসে দৃশ্যমান প্রতীক/ক্যাপশন\nপাকিস্তান | অর্ধচন্দ্রাকৃতি চাঁদ ও তারা\nভারত | অশোক চক্র\nফ্রান্স | লিলি ফুল\nযুক্তরাজ্য | টিউডর গোলাপ\nইউ এস এ | পালকহীন ঈগল\nচীন | তিয়েন আনমেন গেইট\nজাপান | ক্রিস্যান্থেমাম সিংহাসন\nনিউজিল্যান্ড | কিউই পাখি\nসৌদি আরব | খেজুর বৃক্ষ ও তরবারি\nজার্মানি | ফেডারেল ঈগল\nকানাডা | ম্যাপল পাতা\nঅস্ট্রেলিয়া | ক্যাঙ্গারু", "medium"),
  note(520, "জাতীয় ফুল ও পাখি (source callouts)", "বাংলাদেশের জাতীয় ফুল | শাপলা\nভারতের জাতীয় ফুল | পদ্ম\nভুটানের জাতীয় ফুল | নীল পপি\nভারতের জাতীয় পাখি | ময়ূর\nভুটানের জাতীয় পাখি (source callout) | কাক", "high"),
  note(521, "ভৌগোলিক উপনাম — বিশ্ব, মহাদেশ ও ইউরোপ", "বিভাগ | ভৌগোলিক উপনাম | Geographical Alias | দেশ/স্থান\nবিশ্ব/পৃথিবী | পৃথিবীর স্বর্গ/ভূর্গ | Paradise on earth | কাশ্মীর\nবিশ্ব/পৃথিবী | পৃথিবীর ছাদ | Roof of the World | তিবত, পামীর মালভূমি\nবিশ্ব/পৃথিবী | বিশ্বের রাজধানী | Capital of the World | নিউইয়র্ক\nবিশ্ব/পৃথিবী | পৃথিবীর কসাইখানা | Slaughterhouse of the World | শিকাগো\nবিশ্ব/পৃথিবী | বিশ্বের রুটির ঝুড়ি | Breadbasket of the world | ইউক্রেন, প্রেইরি\nমহাদেশ | দ্বীপ মহাদেশ | Island’s Continent | ওশেনিয়া\nমহাদেশ | অন্ধকার মহাদেশ | Dark Continent | আফ্রিকা\nমহাদেশ | বৃহৎকার চিড়িয়াখানা | Sizable Zoo | আফ্রিকা\nমহাদেশ | আফ্রিকার মৃত হৃদয় | Dead Heart of Africa | শাদ*\nনোট | * Dead Heart of Africa বলা হয়- সমুদ্র থেকে এর দূরত্ব এবং মরু আবহাওয়ার কারণে। | | \nইউরোপ | ইউরোপের রণক্ষেত্র | Battlefield of Europe | বেলজিয়াম\nইউরোপ | ইউরোপের ককপিট | Cockpit of Europe | বেলজিয়াম\nইউরোপ | ইউরোপের ক্রীড়াক্ষেত্র | Playground of Europe | সুইজারল্যান্ড\nদৃশ্যমান ক্যাপশন | হাজার হ্রদের দেশ | | ফিনল্যান্ড\nদৃশ্যমান ক্যাপশন | হাজার দ্বীপের দেশ | | ইন্দোনেশিয়া", "medium"),
  note(522, "ভৌগোলিক উপনাম — দেশ", "ভৌগোলিক উপনাম | Geographical Alias | দেশ/স্থান\nভাটির দেশ | Ebb tide Country | বাংলাদেশ\nচির সবুজের দেশ | Country of Eternal Green | বাংলাদেশ\nনীরব খনির দেশ | Silent Mine Country | বাংলাদেশ, রাশিয়া\nসোনালি আঁশের দেশ | Country of Golden Fiber | বাংলাদেশ\nতামার দেশ | Country of Copper | জামাইকা\nশ্বেতহস্তীর দেশ | Country of White Elephant | থাইল্যান্ড\nপশমের দেশ | Country of Wool | অস্ট্রেলিয়া\nসিল্ক রুটের দেশ | Country of Silk Route | ইরান\nসাত পাহাড়ের দেশ | Country of Seven Hills | রোম (ইতালি)\nমৎস্যজীবী/ধীবরের দেশ | Country of Fisherman | নরওয়ে\nনিশীথ সূর্যের দেশ | Land of Midnight Sun | নরওয়ে\nভূমিকম্পের দেশ | Earthquake Country | জাপন (source spelling)\nসূর্যোদয়ের দেশ | Land of the Rising Sun | জাপন (source spelling)\nবরফ ও আগ্নেয়ের দেশ | Lands of Ice and Fire | আইসল্যান্ড\nপবিত্র দেশ (ভূমি) | The Holy Land | জেরুজালেম\nনীল আকাশের দেশ | Land of Blue Sky | মঙ্গোলিয়া\nশান্ত সকালের দেশ | Land of the Morning Calm | কোরিয়া\nসকাল বেলার শান্তি | Peace of the Morning Calm | [rightmost cell unreadable]\nলিলি ফুলের দেশ | Land of Lillies | কানাডা\nবজ্রপাতের দেশ | Land of the Thunderbolt | ভুটান\nবজ্র ড্রাগনের দেশ | Land of the Thunder Dragon | ভুটান\nপঞ্চনদীর দেশ | Land of five rivers | পাঞ্জাব (ভারত)\nমার্বেলের দেশ | Land of Marbles | ইতালি\nউর্বর ভূমির দেশ | Land of Fertile Fields | আলজেরিয়া\nপাম গাছের দেশ | Land of Palms | ব্রাজিল\nকবিদের দেশ | Land of Poets | চিলি", "medium"),
  note(522, "ভৌগোলিক উপনাম — হাজার", "ভৌগোলিক উপনাম | Geographical Alias | দেশ/স্থান\nহাজার হ্রদের দেশ | Country of Thousand Lakes | ফিনল্যান্ড\nহাজার দ্বীপের দেশ | Country of Thousand Islands | ইন্দোনেশিয়া\nহাজার পাহাড়ের দেশ | The land of a Thousand Hills | রুয়ান্ডা", "high"),
  note(523, "ভৌগোলিক উপনাম — শহর/নগরী", "ভৌগোলিক উপনাম | Geographical Alias | দেশ/স্থান\nগোলাপী শহর | Pink City | জয়পুর, রাজস্থান\nমন্দিরের শহর | The Temple City | বেনারস\nরাজপ্রাসাদের শহর | Royal Palace City | কলকাতা\nস্বপ্নের শহর | City of Dreams | মুম্বাই, ভিয়েনা\nবাজারের শহর | Markets City | কায়রো\nউদ্যানের শহর | City of Garden | [rightmost cell blank in image]\nবাতাসের শহর | Windy City | শিকাগো\nগগনচুম্বী অট্টালিকার শহর | City of Skyscrapers | নিউইয়র্ক\nসোনালি তোরণের শহর | City of the Golden gate | সানফ্রান্সিসকো\nভালোবাসা ও আলোর শহর | City of Love & Light | [rightmost cell blank in image]\nসংস্কৃতির শহর | City of Culture | প্যারিস\nগ্রানাইটের শহর | The Granite City | এবারডিন\nসম্মেলনের শহর | City of Conferences | জেনেভা\nপুষ্পমিত বৃক্ষের শহর | The City of Flowering Trees | হারারে\nপবিত্র শহর | Holy City | ভ্যাটিকান সিটি\nঝরনার শহর | City of Fountain | তাসখন্দ, রোম\nচির বসন্তের শহর | City of Eternal Spring | কিটো, রোম\nসাত পাহাড়ের শহর | City of Seven hills | [rightmost cell blank in image]\nনীরব শহর | Silent City | রোম (ইতালি)\nচির শান্তির শহর | City of eternal Peace | [rightmost cell blank in image]\nনিঃশব্দ সড়কের শহর | Silent road City | [rightmost cell blank in image]\nদ্বীপের নগরী | Island's City | ভেনিস (ইতালি)\nখালের নগরী | City of Canals | [rightmost cell blank in image]\nনিমজ্জমান নগরী | Sinking City | [rightmost cell blank in image]\nস্বর্ণনগরী | City of Gold | জোহানেসবার্গ\nজাকালো নগরী | Splendid City | নিউইয়র্ক", "medium"),
];
const facts = [
  fact(520, "ভুটানের জাতীয় ফুল", "ভুটানের জাতীয় ফুল নীল পপি।", "verified", "high", refs.bhutanFlower),
  fact(520, "ভুটানের জাতীয় পাখি (source statement)", "উৎসের কলআউটে ভুটানের জাতীয় পাখি কাক হিসেবে উল্লেখ করা হয়েছে।", "conflicting", "high", refs.bhutanBird),
];
const mcq = (number, question, options, correct, source) => ({ source_page: 520, number, question, options, correct, source, ...ctx(520), status: "source_attributed", confidence: "high", sources: [], canonical_hash: hash(`mcq|520|${number}|${question}`) });
const mcqs = [
  mcq("01", "গোলাপ কোন দেশের জাতীয় প্রতীক?", ["U.K", "U.S.A", "Iran", "France"], "ক", "Bangladesh Bank, 08"),
  mcq("02", "অস্ট্রেলিয়ার জাতীয় প্রতীক কি?", ["ঈগল", "গোলাপ", "পদ্মফুল", "ক্যাঙ্গারু"], "ঘ", "DAT, 04-05"),
  mcq("03", "জাপানের জাতীয় প্রতীক কি?", ["Dragon", "Lilly Flower", "Water Lilly", "Chrysanthemum"], "ঘ", "সার-রেজিস্ট্রার, ০৩, Rupali Bank Ltd., 10"),
  mcq("04", "‘Kiwi’ কোন দেশের জাতীয় প্রতীক?", ["চীন", "কোরিয়া", "জাপান", "নিউজিল্যান্ড"], "ঘ", "রা. বি., ১৩–১৪"),
  mcq("05", "ভুটানের রাষ্ট্রীয় ফুল কোনটি?", ["নীল পপি", "লাল গোলাপ", "পদ্ম", "লিলি"], "ক", "DU ঘ, ১৩–১৪"),
  mcq("06", "ভারতের জাতীয় পাখি-", ["রাজহাঁস", "ঈগল", "ময়ূর", "গরু"], "গ", "DU ঘ, ১৪–১৫"),
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : ["Other university and recruitment examination", null, "competitive", "other-recruitment"];
const quality = status => status === "verified" ? "externally-verified" : status === "conflicting" ? "conflicting" : "source-attributed";
const findId = (kind, key) => kind === "fact" ? `(SELECT id FROM public.gk_facts WHERE canonical_hash=${q(key)} LIMIT 1)` : kind === "note" ? `(SELECT id FROM public.gk_notes WHERE canonical_hash=${q(key)} LIMIT 1)` : `(SELECT id FROM public.gk_mcqs WHERE canonical_hash=${q(key)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(pageFiles.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const chapters = [[60, "বিভিন্ন দেশের জাতীয় প্রতীক", "national-symbols", "Source-preserved national symbol captions and past-exam MCQs.", 519], [61, "ভৌগোলিক উপনাম", "geographical-aliases", "Source-preserved world, country, and city geographical-alias tables.", 521]];
  const topics = [["national-symbols", "বিভিন্ন দেশের জাতীয় প্রতীক", "national-symbols-reference", 519, 1], ["national-symbols", "জাতীয় প্রতীক সম্পর্কিত বিগত বছরের প্রশ্ন", "national-symbols-past-exam-mcqs", 520, 2], ["geographical-aliases", "বিশ্ব, মহাদেশ ও ইউরোপ", "world-continent-europe-aliases", 521, 1], ["geographical-aliases", "দেশ ও হাজার", "country-geographical-aliases", 522, 2], ["geographical-aliases", "শহর/নগরী", "city-geographical-aliases", 523, 3]];
  const checks = [...facts.map(x => ({ kind:"fact", ...x, claim:x.fact_text })), ...notes.map(x => ({ kind:"note", ...x, claim:x.content })), ...mcqs.map(x => ({ kind:"mcq", ...x, claim:`${x.question} — printed answer: ${x.correct}` }))];
  const audit = { batch_pages:BATCH_PAGES, pipeline_version:PIPELINE_VERSION, source_pages:pages.map(p => ({page:p.source_page,review_status:p.review.review_status,image_sha256:p.source_image_sha256})), generated_facts:facts.length, generated_notes:notes.length, generated_mcqs:mcqs.length, generated_options:mcqs.length*4, generated_flashcards:facts.length+notes.length+mcqs.length, verification_counts:{verified:checks.filter(x=>x.status==="verified").length,conflicting:checks.filter(x=>x.status==="conflicting").length,source_attributed:checks.filter(x=>x.status==="source_attributed").length}, source_anomalies:["Physical PDF pages 519–523 retain visible book footers 462–466.","Pages 519–520 used the recovered GPT vision fallback after the original vision service returned empty completions.","Page 521 retains source-visible শাদ* without replacing it with a presumed country name.","Page 522 retains জাপন and the unreadable Peace of the Morning Calm country cell.","Page 523 retains seven visually blank rightmost cells and corrects the Paris row placement without inference."], quality_gates:["Exactly physical pages 519–523 only.","All 25 ordered overlapping tiles reviewed.","MCQs retain four options, printed answer keys, question numbers, and exam metadata.","Source tables remain notes; verified/conflicting claims are stored separately."] };
  const chapterSql = `INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${values(chapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved reference material with explicit verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const pagesSql = pages.map(p => { const c=ctx(p.source_page); const printed={519:462,520:463,521:464,522:465,523:466}[p.source_page]; const meta={source_image_sha256:p.source_image_sha256,extraction_model:p.model,review_status:p.review.review_status,corrections:p.review.corrections,unresolved_spans:p.review.unresolved_spans,accepted_content_tags:p.review.accepted_content_tags,physical_source_page:p.source_page,printed_book_page:printed,artifact_reported_page:p.transcription.source_page,visual_review_report:"/home/ubuntu/dontonyo/reports/batch-0519-0523_visual_review.md",external_verification_report:"/home/ubuntu/dontonyo/reports/batch-0519-0523_external_verification.md",recovery_note:"GPT vision fallback after earlier empty-completion errors."}; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${p.source_page},${q(p.source_page===520?"mcq":"educational")}::page_kind,${q(p.review.verified_transcript)},${q(c.title)},${q(c.topicTitle)},${q(p.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(p.model)},'Quality-gated extraction after transient model failure; ordered visual review and source-preserved anomalies recorded.',${json(meta)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${p.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.fact_text,x.status,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct external corroboration is recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'Source wording is retained; external evidence conflicts and is linked in the verification ledger.' ELSE 'Source-attributed material retained without a silent factual update.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.content,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(x=>{const [name,institution,type,normal]=exam(x.source);const keys=["ক","খ","গ","ঘ"];const opts=x.options.map((o,i)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[i])},${q(o)},${i+1},${keys[i]===x.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[i])});`).join("\n");return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${x.source_page}.`)},${q(normal)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normal)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(x.question)},${q(x.correct)},'Printed answer key retained as source-attributed material; all options and printed examination metadata were visually validated.',${x.source_page},'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন',${q(x.number)},3,'high'::confidence_level,${q(x.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(x.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(x.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${opts} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normal)} LIMIT 1),NULL,${q(x.source)},${q(x.source)},${x.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(x.source)} AND s.source_page=${x.source_page});`;}).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(x=>`(${x.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(x=>[quality(x.status),"national-symbols"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0519-0523-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(x=>[x.source_page<=520?"national-symbols":"geographical-aliases","reference-table","source-attributed","time-sensitive"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0519-0523-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${mcqs.map(x=>["past-exam-mcq","answer-key","national-symbols",exam(x.source)[3],"source-attributed"].map(tag=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${x.source_page},'high'::confidence_level,'batch-0519-0523-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
  const verificationSql = checks.map(x=>`INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${x.source_page},${q(x.kind)},${findId(x.kind,x.canonical_hash)},${q(x.claim)},NULL,${q(x.status)},${q(x.confidence)}::confidence_level,${json(x.sources)},${q(x.status==="verified"?"Direct external corroboration is listed in the batch verification ledger.":x.status==="conflicting"?"Source wording is retained with linked external counter-evidence; no silent correction was made.":"Image-grounded source record retained with explicit source attribution.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(x.kind)} AND v.entity_id=${findId(x.kind,x.canonical_hash)} AND v.claim_text=${q(x.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0519-0523:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 519 AND 523 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0519-0523:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0519-0523:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 519 AND 523 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0519-0523:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0519-0523:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page=520 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0519-0523:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 519 AND 523 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 519 AND 523 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page=520 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0519_0523.mjs. Source pages 519–523 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(p=>p.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pagesSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return {sql,audit};
}
if (process.argv[1]===fileURLToPath(import.meta.url)){const {sql,audit}=await buildBatch();await fs.mkdir(outputDir,{recursive:true});await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql);await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2));await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql}));console.log(JSON.stringify({outputDir,...audit},null,2));}
