import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0499-0503";
const outputDir = path.join(root, "supabase", "batch-0499-0503");
export const BATCH_PAGES = [499, 500, 501, 502, 503];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0499-0503-v1";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const sha = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const book = "Jubayer's GK";
const imagePages = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));
const rows = values => values.map(row => `(${row.map(q).join(", ")})`).join(",\n");
const verification = (page, text) => {
  if (page === 499 && text.includes("নুসানতারা")) return { status: "verified", confidence: "high", sources: ["https://www.trade.gov/market-intelligence/indonesia-new-capital-city-nusantara"] };
  if (page === 502 && text.includes("প্রিটোরিয়া")) return { status: "verified", confidence: "high", sources: ["https://www.gov.za/about-sa/south-africa-glance"] };
  if (page === 500 && text.includes("ইসরাইল")) return { status: "conflicting", confidence: "low", sources: ["https://embassies.gov.il/cyprus/en/node/9946"] };
  return { status: "source_attributed", confidence: "medium", sources: [] };
};
const context = page => ({
  chapter: page < 501 ? "asia-capitals-currencies" : page < 503 ? "africa-capitals-currencies" : "europe-capitals-currencies",
  title: page < 501 ? "এশিয়া মহাদেশ" : page < 503 ? "আফ্রিকা মহাদেশ" : "ইউরোপ মহাদেশ",
  topic: page === 499 ? "asia-south-southeast-capitals-currencies" : page === 500 ? "asia-far-central-other-capitals-currencies" : page === 501 ? "africa-north-northeast-east-capitals-currencies" : page === 502 ? "africa-south-central-west-capitals-currencies" : "europe-regional-capitals-currencies",
});
const note = (source_page, title, content) => ({ source_page, title, content, ...context(source_page), ...verification(source_page, content), canonical_hash: sha(`note|${source_page}|${title}|${content}`) });
const notes = [
  note(499, "সার্কভুক্ত দেশসমূহের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nআফগানিস্তান | কাবুল | আফগানি\nপাকিস্তান | ইসলামাবাদ | রুপি\nভুটান | থিম্পু | গুলট্রাম\nভারত | নয়াদিল্লি | রুপি\nনেপাল | কাঠমুন্ডু | রুপি\nমালদ্বীপ | মালে | রুপিয়া\nশ্রীলঙ্কা | শ্রী জয়াবর্ধনেপুরা (প্রশাসনিক); কলম্বো (বাণিজ্যিক) | রুপি"),
  note(499, "দক্ষিণ-পূর্ব এশিয়ার দেশসমূহের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nব্রুনাই | বন্দর সেরি বেগওয়ান | ডলার\nইন্দোনেশিয়া** | জাকার্তা* | রুপিয়া\nমিয়ানমার | নাইপিদো | কিয়াট\nসিঙ্গাপুর | সিঙ্গাপুর | ডলার\nমালয়েশিয়া | কুয়ালালামপুর (সাংবিধানিক); পুত্রজায়া (প্রশাসনিক) | রিঙ্গিত\nথাইল্যান্ড | ব্যাংকক | বাথ\nভিয়েতনাম | হ্যানয় | ডং\nলাওস | ভিয়েনতিয়েন | কিপ\nকম্বোডিয়া | নমপেন | রিয়েল\nতিমুর লিসতে | দিলি | মা. ডলার\nফিলিপাইন | ম্যানিলা | পেসো"),
  note(500, "দূরপ্রাচ্যের ৫ দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nচীন | বেইজিং | ইউয়ান\nজাপান | টোকিও | ইয়েন\nমঙ্গোলিয়া | উলানবাটোর | তুগরিক\nউত্তর কোরিয়া | পিয়ংইয়ং | ওন\nদক্ষিণ কোরিয়া | সিউল | ওন"),
  note(500, "মধ্য এশিয়ার গুরুত্বপূর্ণ দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nকাজাখস্তান | আস্তানা | তেঙ্গে\nকিরগিজস্তান | বিশকেক | সোম\nতুর্কমেনিস্তান | আশখাবাদ | মানাত\nউজবেকিস্তান | তাসখন্দ | সোম\nতাজিকিস্তান | দুশানবে | সোমনি"),
  note(500, "এশিয়ার অন্যান্য গুরুত্বপূর্ণ দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nআজারবাইজান | বাকু | মানাত\nবাহরাইন | মানামা | দিনার\nজর্ডান | আম্মান | দিনার\nকুয়েত | কুয়েত সিটি | দিনার\nইরাক | বাগদাদ | দিনার\nইরান | তেহরান | রিয়াল\nইসরাইল | তেল আবিব | শেকেল\nলেবানন | বৈরুত | পাউন্ড\nসিরিয়া | দামাস্কাস | পাউন্ড\nতুরস্ক | আঙ্কারা | লিরা\nওমান | মাস্কাট | রিয়াল\nইয়েমেন | সানা | রিয়াল\nকাতার | দোহা | রিয়াল\nসৌদি আরব | রিয়াদ | রিয়াল\nসংযুক্ত আরব আমিরাত | আবুধাবি | দিরহাম"),
  note(501, "উত্তর আফ্রিকার ৭টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nমিশর | কায়রো | পাউন্ড\nসুদান | খার্তুম | পাউন্ড\nদক্ষিণ সুদান | জুবা | পাউন্ড\nতিউনিশিয়া | তিউনিশ | দিনার\nআলজেরিয়া | আলজিয়ার্স | দিনার\nলিবিয়া | ত্রিপোলি | দিনার\nমরক্কো | রাবাত | দিরহাম"),
  note(501, "উত্তর-পূর্ব আফ্রিকার ৪টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nসোমালিয়া | মোগাদিসু | শিলিং\nইরিত্রিয়া | আসমারা | নাকফা\nইথিওপিয়া | আদ্দিস আবাবা | বির\nজিবুতি | জিবুতি | ফ্রাংক"),
  note(501, "পূর্ব আফ্রিকার ১৩টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nবুরুন্ডি | বুজুমবুরা | ফ্রাংক\nকমোরোস | মরোনি | ফ্রাংক\nজাম্বিয়া | লুসাকা | কোয়াচা\nকেনিয়া | নাইরোবি | শিলিং\nমাদাগাস্কার | আন্তানানারিভো | এরিয়ারি\nমালাউই | লিলানগিয়ে | কোয়াচা\nমরিশাস | পোর্টলুইস | রুপি\nমোজাম্বিক | মাপুটো | মেটিকাল\nরুয়ান্ডা | কিগালি | ফ্রাংক\nউগান্ডা | কাম্পালা | শিলিং\nসিচেলিস | ভিক্টোরিয়া | রুপি\nতাঞ্জানিয়া | দোদোমা | শিলিং\nজিম্বাবুয়ে | হারারে | ইউএস ডলার"),
  note(502, "দক্ষিণ আফ্রিকার ৫টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nলেসেথো | ম্যাসেরু | লোতি\nনামিবিয়া | উইন্ডহুক | ডলার\nদক্ষিণ আফ্রিকা | প্রিটোরিয়া (প্রশাসনিক); কেপটাউন (সাংবিধানিক); ব্লুয়েমফন্টেইন (বিচারবিভাগীয়) | র‍্যান্ড\nইসোয়াতিনি | লেমেম্বা | লিলানগেনি\nবতসোয়ানা | গ্যাবরোন | পুলা"),
  note(502, "মধ্য আফ্রিকার ৯টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nঅ্যাঙ্গোলা | লুয়ান্ডা | কোয়ানজা\nক্যামেরুন | ইয়াওউন্ডে | ফ্রাংক\nমধ্য আফ্রিকান প্রজাতন্ত্র | বাঙ্গুই | ফ্রাংক\nচাদ/শাদ | এন জামেনা | ফ্রাংক\nনিরক্ষীয় গিনি | মালাবো | ফ্রাংক\nকঙ্গো প্রজাতন্ত্র | ব্রাজাভিল | ফ্রাংক\nগণতান্ত্রিক কঙ্গো প্রজাতন্ত্র | কিনসাসা | ফ্রাংক\nগ্যাবন | লিব্রোভিল | ফ্রাংক\nসাউটোমে এন্ড প্রিন্সিপে | সাউটোমে | ডোবরা"),
  note(502, "পশ্চিম আফ্রিকার ১৬টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nবেনিন | পোর্টোনোভো | ফ্রাংক\nবারকিনাফাসো | ওয়াগাদুগু | ফ্রাংক\nকাবো ভার্ডে | প্রাইয়া | এসকুডো\nগিনি | কোনাক্রি | গিনি ফ্রাংক\nগিনি বিসাউ | বিসাউ | ফ্রাংক\nগাম্বিয়া | বানজুল | দালাসি\nলাইবেরিয়া | মনরোভিয়া | ডলার\nসিয়েরা লিওন | ফ্রিটাউন | লিওন\nমালি | বামাকো | ফ্রাংক\nমৌরিতানিয়া | নোয়াকচট | অগুইয়া\nনাইজেরিয়া | আবুজা | নাইরা\nনাইজার | নিয়ামে | ফ্রাংক\nসেনেগাল | ডাকার | ফ্রাংক\nটোগো | লোমে | ফ্রাংক\nঘানা | আক্রা | সিডি\nআইভরি কোস্ট | ইয়ামুসুক্রো | ফ্রাংক"),
  note(503, "উত্তর ইউরোপ/নরডিক/স্ক্যান্ডিনেভীয় অঞ্চলের ৫টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nফিনল্যান্ড | হেলসিংকি | ইউরো\nডেনমার্ক | কোপেনহেগেন | ক্রোন\nআইসল্যান্ড | রিকজাভিক | ক্রোনা\nসুইডেন | স্টকহোম | ক্রোনা\nনরওয়ে | অসলো | ক্রোন"),
  note(503, "পূর্ব ইউরোপের ৭টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nরাশিয়া | মস্কো | রুবল\nবেলারুশ | মিনস্ক | রুবল\nএস্তোনিয়া | তাল্লিন | ইউরো\nলাটভিয়া | রিগা | ইউরো\nইউক্রেন | কিয়েভ | হ্রিভনিয়া\nমলদোভা | কিশিনেভ | লিউ\nলিথুয়ানিয়া | ভিলনিয়াস | ইউরো"),
  note(503, "পশ্চিম ইউরোপের ৭টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nযুক্তরাজ্য | লন্ডন | পাউন্ড স্টার্লিং\nআয়ারল্যান্ড | ডাবলিন | ইউরো\nফ্রান্স | প্যারিস | ইউরো\nমোনাকো | মোনাকো | ইউরো\nবেলজিয়াম | ব্রাসেলস | ইউরো\nনেদারল্যান্ডস | আমস্টারডাম | ইউরো\nলুক্সেমবার্গ | লুক্সেমবার্গ | ইউরো"),
  note(503, "দক্ষিণ ইউরোপের ৭টি দেশের রাজধানী ও মুদ্রা", "দেশ | রাজধানী | মুদ্রা\nইতালি | রোম | ইউরো\nসান ম্যারিনো | সান ম্যারিনো | ইউরো\nভ্যাটিকান সিটি | ভ্যাটিকান সিটি | ইউরো\nমাল্টা | ভেলেটা | ইউরো\nঅ্যান্ডোরা | অ্যান্ডোরা লা ভিলা | ইউরো\nস্পেন | মাদ্রিদ | ইউরো\nপর্তুগাল | লিসবন | ইউরো"),
];
const facts = [
  { source_page: 499, title: "ইন্দোনেশিয়ার প্রস্তাবিত রাজধানী", text: "ইন্দোনেশিয়ার প্রস্তাবিত রাজধানীর নাম নুসানতারা।" },
  { source_page: 502, title: "দক্ষিণ আফ্রিকার তিন রাজধানী", text: "দক্ষিণ আফ্রিকা: প্রিটোরিয়া (প্রশাসনিক), কেপটাউন (সাংবিধানিক), ব্লুয়েমফন্টেইন (বিচারবিভাগীয়)।" },
  { source_page: 500, title: "ইসরাইলের রাজধানী ও মুদ্রা (source table row)", text: "ইসরাইল | তেল আবিব | শেকেল" },
].map(row => ({ ...row, ...context(row.source_page), ...verification(row.source_page, row.text), canonical_hash: sha(`fact|${row.source_page}|${row.title}|${row.text}`) }));
const tags = [["world-capitals-currencies", "World capitals and currencies", "domain", "Source-derived regional capital-and-currency reference."], ["capital-currency-table", "Capital and currency table", "content_type", "Structured source table of country, capital, and currency."], ["source-attributed", "Source-attributed", "quality", "Source-preserved content without direct external corroboration."], ["externally-verified", "Externally verified", "quality", "Directly corroborated source claim."], ["conflicting", "Conflicting external evidence", "quality", "Source claim conflicts with external authority and is retained without silent correction."], ["time-sensitive", "Time-sensitive reference", "quality", "Current-status information requiring future review."], ["asia", "Asia", "domain", "Asian reference material."], ["africa", "Africa", "domain", "African reference material."], ["europe", "Europe", "domain", "European reference material."]];
function pageMetadata(page) { const printed = { 499: 442, 500: 443, 501: 888, 502: 445, 503: 446 }[page.source_page]; return { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, accepted_content_tags: page.review.accepted_content_tags, physical_source_page: page.source_page, printed_book_page: printed, artifact_reported_page: page.transcription.source_page, visual_review_report: "/home/ubuntu/dontonyo/reports/batch-0499-0503_visual_review.md", external_verification_report: "/home/ubuntu/dontonyo/reports/batch-0499-0503_external_verification.md", page_number_mismatch: printed !== page.source_page ? "Physical PDF page and visible printed footer are separately preserved in source metadata." : null }; }
export async function buildBatch() {
  const pages = await Promise.all(imagePages.map(async file => JSON.parse(await fs.readFile(file, "utf8"))));
  const audit = { batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION, source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256 })), generated_facts: facts.length, generated_notes: notes.length, generated_flashcards: facts.length + notes.length, verification_counts: { verified: [...facts, ...notes].filter(row => row.status === "verified").length, conflicting: [...facts, ...notes].filter(row => row.status === "conflicting").length, source_attributed: [...facts, ...notes].filter(row => row.status === "source_attributed").length }, source_anomalies: ["Page 499 printed footer 442; physical PDF page 499.", "Page 500 printed footer 443; physical PDF page 500.", "Page 501 printed footer 888; physical PDF page 501.", "Page 502 footer corrected from initial OCR 885 to visually reviewed 445.", "Page 503 printed footer 446; physical PDF page 503.", "The page-500 Israel–Tel Aviv table row is retained with externally conflicting status; not silently replaced."], quality_gates: ["Five physical PDF pages only; do not extend without explicit user instruction.", "All 25 tiles were visually reviewed in manifest order.", "Capital-and-currency rows stay in structured source tables; no mass invented fact decomposition.", "Idempotency is enforced by source page, canonical hash, and source key."] };
  const chapterSql = `INSERT INTO public.chapters (book_id, chapter_number, title, slug, description, source_page, display_order) SELECT b.id, x.n, x.title, x.slug, x.description, x.source_page, x.n FROM (VALUES (48, 'এশিয়া মহাদেশ', 'asia-capitals-currencies', 'Source-preserved Asian capital-and-currency reference tables.', 499), (49, 'আফ্রিকা মহাদেশ', 'africa-capitals-currencies', 'Source-preserved African capital-and-currency reference tables.', 501), (50, 'ইউরোপ মহাদেশ', 'europe-capitals-currencies', 'Source-preserved European capital-and-currency reference tables.', 503)) AS x(n, title, slug, description, source_page) JOIN public.books b ON b.title = ${q(book)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id = b.id AND c.slug = x.slug);`;
  const topicDefs = [["asia-capitals-currencies", "এশিয়ার রাজধানী ও মুদ্রা: সার্ক ও দক্ষিণ-পূর্ব এশিয়া", "asia-south-southeast-capitals-currencies", 499, 1], ["asia-capitals-currencies", "এশিয়ার রাজধানী ও মুদ্রা: দূরপ্রাচ্য, মধ্য এশিয়া ও অন্যান্য", "asia-far-central-other-capitals-currencies", 500, 2], ["africa-capitals-currencies", "আফ্রিকার রাজধানী ও মুদ্রা: উত্তর, উত্তর-পূর্ব ও পূর্ব", "africa-north-northeast-east-capitals-currencies", 501, 1], ["africa-capitals-currencies", "আফ্রিকার রাজধানী ও মুদ্রা: দক্ষিণ, মধ্য ও পশ্চিম", "africa-south-central-west-capitals-currencies", 502, 2], ["europe-capitals-currencies", "ইউরোপের রাজধানী ও মুদ্রা", "europe-regional-capitals-currencies", 503, 1]];
  const topicsSql = `INSERT INTO public.topics (chapter_id, title, slug, description, source_page, display_order) SELECT c.id, x.title, x.slug, 'Structured source-preserved capital-and-currency reference tables.', x.source_page::integer, x.display_order::integer FROM (VALUES ${rows(topicDefs)}) AS x(chapter_slug, title, slug, source_page, display_order) JOIN public.chapters c ON c.slug = x.chapter_slug AND c.book_id = (SELECT id FROM public.books WHERE title = ${q(book)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id = c.id AND t.slug = x.slug);`;
  const pageSql = pages.map(page => { const c = context(page.source_page); return `INSERT INTO public.source_pages (import_run_id, book_id, source_page, page_kind, raw_transcription, chapter_heading, topic_heading, confidence, extraction_method, model_name, notes, review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version = ${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1), b.id, ${page.source_page}, 'educational'::page_kind, ${q(page.review.verified_transcript)}, ${q(c.title)}, ${q(c.topic)}, 'high'::confidence_level, 'vision_ocr_with_image_grounded_review', ${q(page.model)}, 'Ordered five-tile review; structured tables remain source-derived; validation status is explicit.', ${json(pageMetadata(page))} FROM public.books b WHERE b.title = ${q(book)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id = b.id AND s.source_page = ${page.source_page});`; }).join("\n");
  const notesSql = `WITH d(source_page, title, content, chapter_slug, topic_slug, confidence, canonical_hash) AS (VALUES\n${rows(notes.map(row => [row.source_page, row.title, row.content, row.chapter, row.topic, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id, chapter_id, topic_id, title, content, source_page, source_section, display_order, confidence, canonical_hash) SELECT b.id, c.id, t.id, d.title, d.content, d.source_page::integer, d.title, d.source_page::integer, d.confidence::confidence_level, d.canonical_hash FROM d JOIN public.books b ON b.title = ${q(book)} JOIN public.chapters c ON c.book_id = b.id AND c.slug = d.chapter_slug JOIN public.topics t ON t.chapter_id = c.id AND t.slug = d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content = EXCLUDED.content, confidence = EXCLUDED.confidence;`;
  const factsSql = `WITH d(source_page, title, text, chapter_slug, topic_slug, confidence, canonical_hash, status) AS (VALUES\n${rows(facts.map(row => [row.source_page, row.title, row.text, row.chapter, row.topic, row.confidence, row.canonical_hash, row.status]))}) INSERT INTO public.gk_facts (book_id, chapter_id, topic_id, title, fact_text, explanation, source_page, source_section, source_excerpt, importance, confidence, canonical_hash) SELECT b.id, c.id, t.id, d.title, d.text, CASE d.status WHEN 'verified' THEN 'Directly corroborated by a source recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'Source wording retained exactly; external authority conflicts and is recorded in the verification ledger.' ELSE 'Source-attributed reference material retained without silent updating.' END, d.source_page::integer, d.title, d.text, 3, d.confidence::confidence_level, d.canonical_hash FROM d JOIN public.books b ON b.title = ${q(book)} JOIN public.chapters c ON c.book_id = b.id AND c.slug = d.chapter_slug JOIN public.topics t ON t.chapter_id = c.id AND t.slug = d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text = EXCLUDED.fact_text, explanation = EXCLUDED.explanation, confidence = EXCLUDED.confidence;`;
  const tagSql = `INSERT INTO public.content_tags (slug, label, category, description) VALUES\n${tags.map(tag => `(${tag.map(q).join(", ")})`).join(",\n")} ON CONFLICT (slug) DO UPDATE SET label = EXCLUDED.label, category = EXCLUDED.category, description = EXCLUDED.description;\n${notes.map(row => { const region = row.source_page < 501 ? "asia" : row.source_page < 503 ? "africa" : "europe"; return ["capital-currency-table", "source-attributed", region].map(tag => `INSERT INTO public.content_tag_assignments (tag_id, entity_type, entity_id, source_page, confidence, assigned_by) SELECT t.id, 'note', n.id, ${row.source_page}, ${q(row.confidence)}::confidence_level, 'batch-0499-0503-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash = ${q(row.canonical_hash)} WHERE t.slug = ${q(tag)} ON CONFLICT DO NOTHING;`).join("\n"); }).join("\n")}\n${facts.map(row => { const tag = row.status === "verified" ? "externally-verified" : row.status === "conflicting" ? "conflicting" : "source-attributed"; return [tag, "time-sensitive"].map(value => `INSERT INTO public.content_tag_assignments (tag_id, entity_type, entity_id, source_page, confidence, assigned_by) SELECT t.id, 'fact', f.id, ${row.source_page}, ${q(row.confidence)}::confidence_level, 'batch-0499-0503-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash = ${q(row.canonical_hash)} WHERE t.slug = ${q(value)} ON CONFLICT DO NOTHING;`).join("\n"); }).join("\n")}`;
  const verificationSql = [...notes, ...facts].map(row => { const type = row.text ? "fact" : "note"; const hash = row.canonical_hash; const entity = type === "fact" ? `(SELECT id FROM public.gk_facts WHERE canonical_hash = ${q(hash)} LIMIT 1)` : `(SELECT id FROM public.gk_notes WHERE canonical_hash = ${q(hash)} LIMIT 1)`; const claim = row.text ?? row.content; return `INSERT INTO public.fact_verifications (source_page, entity_type, entity_id, claim_text, normalized_claim, verification_status, confidence, verification_sources, audit_note) SELECT ${row.source_page}, ${q(type)}, ${entity}, ${q(claim)}, ${q(claim)}, ${q(row.status)}, ${q(row.confidence)}::confidence_level, ${json(row.sources)}, ${q(row.status === "conflicting" ? "Source-table wording retained without silent correction; conflicting external authority is linked." : row.status === "verified" ? "Direct corroboration is linked in the external-verification ledger." : "Source-attributed structured table retained with explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type = ${q(type)} AND v.entity_id = ${entity} AND v.claim_text = ${q(claim)});`; }).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id, book_id, chapter_id, topic_id, front_text, back_text, source_type, source_id, source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1), n.book_id, n.chapter_id, n.topic_id, n.title, n.content, 'note', n.id, 'batch0499-0503:note:' || n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 499 AND 503 AND NOT EXISTS (SELECT 1 FROM public.flashcards f WHERE f.source_key = 'batch0499-0503:note:' || n.id::text); INSERT INTO public.flashcards (subject_id, book_id, chapter_id, topic_id, front_text, back_text, source_type, source_id, source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1), f.book_id, f.chapter_id, f.topic_id, f.title, f.fact_text, 'fact', f.id, 'batch0499-0503:fact:' || f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 499 AND 503 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key = 'batch0499-0503:fact:' || f.id::text); INSERT INTO public.search_documents (entity_type, entity_id, title, body, english_metadata) SELECT 'note', n.id, n.title, n.content, 'Capital-and-currency reference table | source page ' || n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 499 AND 503 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type = 'note' AND d.entity_id = n.id); INSERT INTO public.search_documents (entity_type, entity_id, title, body, english_metadata) SELECT 'fact', f.id, f.title, f.fact_text, 'Verified/status-marked capital reference | source page ' || f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 499 AND 503 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type = 'fact' AND d.entity_id = f.id);`;
  const sql = `-- Generated by scripts/prepare_validated_batch_0499_0503.mjs\n-- Source pages: 499–503 only. Do not extend without explicit user instruction.\nBEGIN;\nINSERT INTO public.import_runs (source_filename, source_sha256, pipeline_version, status, completed_at, audit) VALUES ('Jubayer''sgk.pdf', ${q(sha(pages.map(page => page.source_image_sha256).join("|")))}, ${q(PIPELINE_VERSION)}, 'completed', now(), ${json(audit)});\n${chapterSql}\n${topicsSql}\n${pageSql}\n${notesSql}\n${factsSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { const { sql, audit } = await buildBatch(); await fs.mkdir(outputDir, { recursive: true }); await fs.writeFile(path.join(outputDir, "validated_import.sql"), sql); await fs.writeFile(path.join(outputDir, "batch_audit.json"), JSON.stringify(audit, null, 2)); await fs.writeFile(path.join(outputDir, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql })); console.log(JSON.stringify({ outputDir, ...audit }, null, 2)); }
