import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const work = "/home/ubuntu/dontonyo-work/batch-0609-0613";
const out = path.join(root, "supabase", "batch-0609-0613");
const BOOK = "Jubayer's GK";
export const BATCH_PAGES = [609, 610, 611, 612, 613];
export const PIPELINE_VERSION = "local-ocr-quality-gated-batch-0609-0613-v1";
const q = x => `'${String(x ?? "").replaceAll("'", "''")}'`;
const js = x => `${q(JSON.stringify(x))}::jsonb`;
const h = x => crypto.createHash("sha256").update(x, "utf8").digest("hex");
const vals = rows => rows.map(r => `(${r.map(q).join(",")})`).join(",\n");
const ref = { nightingale: "https://www.britannica.com/biography/Florence-Nightingale", mussolini: "https://www.britannica.com/biography/Benito-Mussolini", spain: "https://www.britannica.com/place/Spain/Francos-Spain-1939-75", catalonia: "https://www.britannica.com/place/Catalonia", lateran: "https://www.britannica.com/event/Lateran-Treaty", nordic: "https://www.norden.org/en/information/facts-about-nordic-countries", greenland: "https://www.britannica.com/place/Greenland", yugoslavia: "https://history.state.gov/milestones/1989-1992/breakup-yugoslavia", unYugoslavia: "https://www.un.org/en/about-us/member-states/yugoslavia" };
const ctx = p => p === 609 ? ["italy-personalities-and-past-questions-reference", "italy"] : p === 610 ? ["spain-franco-and-catalonia-reference", "spain"] : p === 611 ? ["vatican-city-reference-and-past-questions", "vatican-city"] : p === 612 ? ["nordic-region-reference", "nordic-region"] : ["former-yugoslavia-reference", "former-yugoslavia"];
const f = (p,t,b,s="source_attributed",u=[],c="high") => ({p,t,b,s,u,c,topic:ctx(p)[0],domain:ctx(p)[1],hash:h(`f|${p}|${t}|${b}`)});
const n = (p,t,b,s="source_attributed",u=[],c="high") => ({p,t,b,s,u,c,topic:ctx(p)[0],domain:ctx(p)[1],hash:h(`n|${p}|${t}|${b}`)});
const m = (p,no,qst,opts,key,src,s="source_attributed",u=[]) => ({p,no,qst,opts,key,src,s,u,c:"high",topic:ctx(p)[0],domain:ctx(p)[1],hash:h(`m|${p}|${no}|${qst}`)});
const facts = [
 f(609,"Florence Nightingale — 1820 Florence birth","Britannica অনুযায়ী Florence Nightingale ১২ মে ১৮২০ সালে Italy-এর Florence-এ জন্মগ্রহণ করেন।","verified",[ref.nightingale]),
 f(609,"Florence Nightingale — Lady with the Lamp","Crimean War-এ night rounds-এ আহত সৈন্যদের সেবা Florence Nightingale-এর `Lady with the Lamp` পরিচিতির সঙ্গে যুক্ত।","verified",[ref.nightingale]),
 f(609,"International Nurses Day — 12 May","International Nurses Day প্রতি বছর ১২ মে Florence Nightingale-এর জন্মদিনে পালিত হয়।","verified",[ref.nightingale]),
 f(609,"Benito Mussolini — Italy prime minister historic office","Benito Mussolini Italy-এর prime minister ছিলেন ১৯২২–১৯৪৩; এটি historic office context।","verified",[ref.mussolini]),
 f(609,"Benito Mussolini — 1945 death","Benito Mussolini ১৯৪৫ সালে মারা যান; এটি historic reference।","verified",[ref.mussolini]),
 f(610,"Spanish Civil War — 1936–1939","উৎসে Spanish Civil War-এর সময়কাল ১৯৩৬–১৯৩৯ বলা হয়েছে; এটি historic reference।","verified",[ref.spain]),
 f(610,"Francisco Franco — 1939–1975 rule","Britannica অনুযায়ী General Francisco Franco ১৯৩৯ থেকে ১৯৭৫ সালে তাঁর মৃত্যু পর্যন্ত Spain শাসন করেন; authoritarian historic context স্পষ্ট রাখা হয়েছে।","verified",[ref.spain]),
 f(610,"Spain — capital Madrid","উৎসে Madrid-কে Spain-এর রাজধানী বলা হয়েছে; Barcelona-কে একটি গুরুত্বপূর্ণ শহর হিসেবে উল্লেখ করা হয়েছে।","verified",[ref.spain]),
 f(610,"Catalonia — autonomous community and historic region","Britannica অনুযায়ী Catalonia Spain-এর autonomous community ও historic region; এর রাজধানী Barcelona।","verified",[ref.catalonia]),
 f(610,"Catalonia — 2017 event boundary","উৎসে ২০১৭ সালের independence declaration-এর উল্লেখ আছে; এটি bounded historic event হিসেবে source-attributed রাখা হয়েছে, contemporary status claim হিসেবে নয়।","source_attributed",[],"medium"),
 f(611,"Lateran Treaty — Vatican sovereignty in 1929","Lateran Treaty ১৯২৯ সালে Vatican City-এর sovereignty স্বীকার করে; এটি historic institutional reference।","verified",[ref.lateran]),
 f(611,"Vatican City — Rome enclave","Vatican City Rome দ্বারা বেষ্টিত enclave এবং বিশ্বের ক্ষুদ্রতম fully independent nation-state।","verified",[ref.lateran]),
 f(611,"Vatican City — Holy See and Pope","Vatican City-এর government হলো Holy See, যা Pope-এর নেতৃত্বে পরিচালিত; এটি institutional reference।","verified",[ref.lateran]),
 f(611,"Swiss Guards — Pope safety role","Swiss Guards ১৫০৬ সাল থেকে Pope-এর personal safety-এর জন্য দায়ী; এটি institutional historic reference।","verified",[ref.lateran]),
 f(611,"Vatican Palace — Pope residence","Vatican Palace city walls-এর মধ্যে Pope-এর residence।","verified",[ref.lateran]),
 f(611,"Vatican City — UNESCO 1984","Vatican City ১৯৮৪ সালে UNESCO World Heritage site হিসেবে মনোনীত হয়।","verified",[ref.lateran]),
 f(612,"Nordic Region — countries and territories","Nordic Region-এ Denmark, Norway, Sweden, Finland, Iceland, Faroe Islands, Greenland ও Åland অন্তর্ভুক্ত।","verified",[ref.nordic]),
 f(612,"Kingdom of Denmark — realm composition","Kingdom of Denmark গঠিত Denmark, Greenland ও Faroe Islands নিয়ে।","verified",[ref.nordic]),
 f(612,"Greenland — largest island and Denmark context","Greenland বিশ্বের বৃহত্তম island এবং Kingdom of Denmark-এর অংশ; domestic affairs-এ এর self-government আছে।","verified",[ref.greenland]),
 f(612,"Iceland — North Atlantic island nation","Iceland North Atlantic-এর একটি island nation।","verified",[ref.nordic]),
 f(612,"Finland — Nordic lake-rich geography","Finland Nordic region-এর lake-rich country হিসেবে official Nordic reference-এ বর্ণিত।","verified",[ref.nordic]),
 f(613,"Yugoslavia — post-World War I creation","Yugoslavia World War I-এর শেষে তৈরি হয়; এটি historic state reference।","verified",[ref.yugoslavia]),
 f(613,"Slovenia and Croatia — 1991 declarations","Slovenia ও Croatia ২৫ জুন ১৯৯১ সালে Yugoslav federation থেকে formal independence ঘোষণা করে।","verified",[ref.yugoslavia]),
 f(613,"North Macedonia — 1991 independence referendum","North Macedonia September 1991 referendum-এর পর independence ঘোষণা করে; এটি historic reference।","verified",[ref.yugoslavia]),
 f(613,"Bosnia and Herzegovina — 1992 independence","Bosnia and Herzegovina May 1992-এ Yugoslavia থেকে independence ঘোষণা করে; এটি historic reference।","verified",[ref.yugoslavia]),
 f(613,"Serbia and Montenegro — 1992 successor context","Serbia ও Montenegro ১৯৯২ সালে new Federal Republic of Yugoslavia গঠন করে; এটি successor-state historic context।","verified",[ref.yugoslavia,ref.unYugoslavia]),
 f(613,"Kosovo — 2008 declaration boundary","Kosovo ২০০৮ সালে independence ঘোষণা করে; recognition question-টি politically contested থাকায় এটি source-attributed historic/diplomatic contextে রাখা হয়েছে।","source_attributed",[ref.yugoslavia],"medium")
];
const notes = [
 n(609,"Italy personalities — ideology and quotation boundary","Nightingale-এর bounded biography এবং Mussolini-এর corroborated historic office context রাখা হয়েছে। Political quotation, propaganda-style wording, and ideological summaries neutral factsে রূপান্তরিত হয়নি."),
 n(610,"Spain and Catalonia — political boundary","Franco-era material historic scopeে রাখা হয়েছে। Catalonia-এর 2017 event contemporary independence, recognition, or territorial-status claim নয়; political/time-sensitive MCQs withheld."),
 n(611,"Vatican City — office-holder boundary","Lateran Treaty, enclave, Holy See, Swiss Guards, Palace, and UNESCO facts retained. Current-Pope wording, inaccurate `Holy City` label, and scan area line are withheld."),
 n(612,"Nordic region — ranking and definition boundary","Official Nordic-region membership and Denmark/Greenland context are retained. Peace/happiness rankings, priority claims, aliases, and simplified Scandinavia definitions are withheld."),
 n(613,"Former Yugoslavia — territorial and diplomatic boundary","The breakup timeline is limited to directly corroborated historic declarations and successor-state context. Kosovo is stored only with historic/diplomatic qualification; map/mnemonic text is not flattened into current-territory claims."),
 n(613,"Local OCR recovery — orientation provenance","All pages were source-sideways. A clockwise review copy plus local `ben+eng` OCR was reconciled with all 35 original ordered tiles. The initial counterclockwise copy was upside down and is retained only as a failed recovery artifact.","source_attributed",[],"medium")
];
const mcqs = [
 m(609,"01","‘The lady with the Lamp’ নামে পরিচিত—",["হেলেন কেলার","ফ্লোরেন্স নাইটিঙ্গেল","মাদার তেরেসা","সরোজিনী নাইডু"],"খ","43 BCS","verified",[ref.nightingale]),
 m(609,"02","ভ্যাটিক্যান কোন শহরের পাশে অবস্থিত?",["রিওডি জেনিরিও","রোম","এথেন্স","বৈরুত"],"খ","DU ঘ 96–97","verified",[ref.lateran]),
 m(609,"03","Renaissance কথাটির অর্থ কী?",["মৃত্যু","বার্ধক্য","পৌঢ়ত্ব","নবজীবন"],"ঘ","মহা হিসাবরক্ষক-এর অধীনে অধীক্ষক 98","source_attributed"),
 m(609,"04","ইউরোপে রেনেসাঁ শুরু হয়—",["পঞ্চদশ শতাব্দীতে","ষোড়শ শতাব্দীতে","চতুর্দশ শতাব্দীতে","সপ্তদশ শতাব্দীতে"],"গ","দুদক 04","source_attributed"),
 m(609,"05","বেনিতো মুসোলিনী কোন দেশের নেতা ছিলেন?",["ফ্রান্স","ব্রিটেন","ইতালি","পর্তুগাল"],"গ","মন্ত্রিপরিষদ কার্যালয়ে প্রশাসনিক কর্মকর্তা 04","verified",[ref.mussolini]),
 m(609,"06","ফ্যাসিজমের প্রবর্তক কে ছিলেন?",["হিটলার","জেনারেল ফ্রাঙ্কো","স্টালিন","মুসোলিনী"],"ঘ","রাবি রাষ্ট্রবিজ্ঞান 05–06; ভূগোল ও পরিবেশ বিদ্যা 05–06","verified",[ref.mussolini]),
 m(611,"01","বর্তমান পোপ ফ্রান্সিস কোন দেশের নাগরিক?",["ব্রাজিল","বলিভিয়া","আর্জেন্টিনা","পেরু"],"গ","DU খ 13–14","verified",[ref.lateran]),
 m(611,"02","ভ্যাটিকান কী?",["উত্তর আমেরিকার পর্বতমালা","যুক্তরাষ্ট্রের পপ সঙ্গীত গোষ্ঠী","ক্যাথলিক ধর্মীয় রাষ্ট্রব্যবস্থা","বস্তবাদী নাস্তিক ইউরোপীয় সংগঠন"],"গ","কেরা তত্ত্বাবধায়ক 10","verified",[ref.lateran])
];
const topics = [["Italy personalities ও past-question reference","italy-personalities-and-past-questions-reference",609,21],["Spain, Franco ও Catalonia reference","spain-franco-and-catalonia-reference",610,22],["Vatican City reference ও past questions","vatican-city-reference-and-past-questions",611,23],["Nordic region reference","nordic-region-reference",612,24],["Former Yugoslavia reference","former-yugoslavia-reference",613,25]];
const tags = [["europe","Europe","domain","Europe source material."],["italy","Italy","domain","Italy source material."],["spain","Spain","domain","Spain source material."],["vatican-city","Vatican City","domain","Vatican City source material."],["nordic-region","Nordic region","domain","Nordic source material."],["former-yugoslavia","Former Yugoslavia historic reference","domain","Historic Balkan source material."],["reference-note","Structured source note","content_type","Bounded source reference with caveats."],["past-exam-mcq","Past-exam MCQ","content_type","Source-complete past-exam item."],["answer-key","Printed answer key","content_type","Visually reviewed printed answer key."],["source-attributed","Source-attributed","quality","Source-preserved record without direct corroboration in this batch."],["externally-verified","Externally verified","quality","Directly corroborated record."],["historic-scope","Historic scope","quality","Historic political, institutional, territorial, cultural, or geographic reference."],["dhaka-university","University of Dhaka","exam_source","Printed University of Dhaka source label."],["bcs","Bangladesh Civil Service","exam_source","Printed BCS source label."],["other-bangladesh-exam","Other Bangladesh examination","exam_source","Other printed examination source label."]];
const meta = src => src.includes("DU") ? ["University of Dhaka","University of Dhaka","admission","dhaka-university"] : src.includes("BCS") ? ["Bangladesh Civil Service",null,"competitive","bcs"] : ["Other Bangladesh examination",null,"competitive","other-bangladesh-exam"];
const table = k => k === "fact" ? "gk_facts" : k === "note" ? "gk_notes" : "gk_mcqs";
const ent = (k,x) => `(SELECT id FROM public.${table(k)} WHERE canonical_hash=${q(x.hash)} LIMIT 1)`;
const qual = x => x.s === "verified" ? "externally-verified" : "source-attributed";
export async function buildBatch() {
 const pages = await Promise.all(BATCH_PAGES.map(async p => { const raw=await fs.readFile(path.join(work,"pages",`page_${String(p).padStart(4,"0")}_tesseract_readable.txt`),"utf8"); const im=await fs.readFile(path.join(work,"rendered",`page_${String(p).padStart(4,"0")}.jpg`)); return {p,raw,sha:crypto.createHash("sha256").update(im).digest("hex")}; }));
 const rec=[...facts.map(x=>["fact",x,x.b]),...notes.map(x=>["note",x,x.b]),...mcqs.map(x=>["mcq",x,`${x.qst} — printed answer: ${x.key}`])];
 const audit={batch_pages:BATCH_PAGES,pipeline_version:PIPELINE_VERSION,source_pages:pages.map(x=>({page:x.p,review_status:"completed_image_grounded_review",image_sha256:x.sha,overall_confidence:"medium"})),generated_facts:facts.length,generated_notes:notes.length,generated_mcqs:mcqs.length,generated_options:mcqs.length*4,generated_flashcards:rec.length,verification_counts:{verified:rec.filter(r=>r[1].s==="verified").length,conflicting:0,source_attributed:rec.filter(r=>r[1].s==="source_attributed").length},source_anomalies:["All 35 original tiles were reviewed. Source pages were sideways and recovered with clockwise copies plus local Bangla OCR.","The first counterclockwise recovery was upside down and is not used for classification.","Political, territorial, current-office, ranking, superlative, and ideological source lines were explicitly bounded or withheld."],quality_gates:["Exactly physical source pages 609–613 are imported.","Every imported MCQ has four visually reviewed options and exactly one printed source key.","No current-status, corrupted, ambiguous, ideological, or historically unsafe MCQ is imported.","Only approved content-tag categories are used."]};
 const topicSql=`INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with complete visual review and explicit verification status.',x.page::integer,x.ord::integer FROM (VALUES ${vals(topics.map(x=>["europe",...x]))}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
 const pageSql=pages.map(x=>{const [topic]=ctx(x.p);const rm={physical_source_page:x.p,source_image_sha256:x.sha,extraction_method:"local_tesseract_ben_eng_clockwise_recovery",review_status:"completed_image_grounded_review",review_report:`${work}/visual_review_609_613.md`,classification_report:`${work}/classification_decisions.md`,verification_report:`${work}/external_verification.md`,recovery_artifacts:[`page_${String(x.p).padStart(4,"0")}_tesseract_readable.txt`,`page_${String(x.p).padStart(4,"0")}_cw.jpg`]};return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${x.p},'educational'::page_kind,${q(x.raw)},'Europe',${q(topic)},'medium'::confidence_level,'local_ocr_with_image_grounded_review','tesseract-ben+eng','Clockwise recovery and all ordered tile review complete; import uses classified records only.',${js(rm)} FROM public.books b WHERE b.title=${q(BOOK)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${x.p});`;}).join("\n");
 const factSql=`WITH d(page,topic,title,body,confidence,canonical_hash) AS (VALUES ${vals(facts.map(x=>[x.p,x.topic,x.t,x.b,x.c,x.hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,'Source-derived reference with explicit verification status and historic scope where applicable.',d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.canonical_hash FROM d JOIN public.books b ON b.title=${q(BOOK)} JOIN public.chapters c ON c.book_id=b.id AND c.slug='europe' JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
 const noteSql=`WITH d(page,topic,title,body,confidence,canonical_hash) AS (VALUES ${vals(notes.map(x=>[x.p,x.topic,x.t,x.b,x.c,x.hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.canonical_hash FROM d JOIN public.books b ON b.title=${q(BOOK)} JOIN public.chapters c ON c.book_id=b.id AND c.slug='europe' JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
 const mcqSql=mcqs.map(x=>{const [name,institution,type,tag]=meta(x.src);const ks=["ক","খ","গ","ঘ"];const os=x.opts.map((o,i)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(ks[i])},${q(o)},${i+1},${ks[i]===x.key} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(ks[i])});`).join("\n");return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${x.p}.`)},${q(tag)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(tag)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(x.qst)},${q(x.key)},${q(x.s==="verified"?"Printed key visually reviewed; verification and historic scope are recorded in the batch ledger.":"Printed key visually reviewed; the source-attributed context is recorded in the batch ledger.")},${x.p},'বিগত বছরের প্রশ্ন',${q(x.no)},3,'high'::confidence_level,${q(x.hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug='europe' JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(x.topic)} WHERE b.title=${q(BOOK)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${os} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(tag)} LIMIT 1),NULL,${q(x.src)},${q(x.src)},${x.p} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources z WHERE z.mcq_id=m.id AND z.source_text=${q(x.src)} AND z.source_page=${x.p});`;}).join("\n");
 const assign=(k,x,ss)=>ss.map(s=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,${q(k)},${ent(k,x)},${x.p},${q(x.c)}::confidence_level,'batch-0609-0613-quality-pipeline' FROM public.content_tags t WHERE t.slug=${q(s)} ON CONFLICT DO NOTHING;`).join("\n");
 const tagSql=`INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(r=>`(${r.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(x=>assign("fact",x,["europe",x.domain,qual(x),"historic-scope"])).join("\n")}\n${notes.map(x=>assign("note",x,["europe",x.domain,"reference-note",qual(x),"historic-scope"])).join("\n")}\n${mcqs.map(x=>assign("mcq",x,["europe",x.domain,"past-exam-mcq","answer-key",meta(x.src)[3],qual(x),"historic-scope"])).join("\n")}`;
 const verSql=rec.map(([k,x,claim])=>`INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${x.p},${q(k)},${ent(k,x)},${q(claim)},NULL,${q(x.s)},${q(x.c)}::confidence_level,${js(x.u)},${q(x.s==="verified"?"Direct corroboration and historic boundary are recorded in the batch verification ledger.":"Source-attributed record retained after complete image review and conservative classification.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(k)} AND v.entity_id=${ent(k,x)} AND v.claim_text=${q(claim)});`).join("\n");
 const derived=`INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0609-0613:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.flashcards z WHERE z.source_key='batch0609-0613:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0609-0613:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.flashcards z WHERE z.source_key='batch0609-0613:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0609-0613:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.flashcards z WHERE z.source_key='batch0609-0613:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page BETWEEN 609 AND 613 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
 const sql=`-- Generated by prepare_validated_batch_0609_0613.mjs. Source pages 609–613 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(h(pages.map(x=>x.sha).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${js(audit)});\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verSql}\n${derived}\nCOMMIT;`;
 return {sql,audit};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {sql,audit}=await buildBatch();const counts={batch_pages:BATCH_PAGES,review_tiles:35,eligible_facts:facts.length,eligible_notes:notes.length,eligible_mcqs:mcqs.length,eligible_mcq_options:mcqs.length*4,withheld_mcqs:4,derived_records:audit.generated_flashcards,verification_statuses:audit.verification_counts};await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,"validated_import.sql"),sql);await fs.writeFile(path.join(out,"batch_audit.json"),JSON.stringify(audit,null,2));await fs.writeFile(path.join(out,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql}));await fs.writeFile(path.join(work,"import_input_counts.json"),JSON.stringify(counts,null,2));console.log(JSON.stringify({out,audit,counts},null,2));}
