import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0589-0593";
const outputDir = path.join(root, "supabase", "batch-0589-0593");
export const BATCH_PAGES = [589, 590, 591, 592, 593];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0589-0593-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));

const refs = {
  women1918: "https://www.parliament.uk/about/living-heritage/transformingsociety/electionsvoting/womenvote/case-study-the-right-to-vote/the-right-to-vote/birmingham-and-the-equal-franchise/1918-representation-of-the-people-act/",
  magnaCarta: "https://www.parliament.uk/magnacarta/",
  downingStreet: "https://www.gov.uk/government/history/10-downing-street",
  pastPm: "https://www.gov.uk/government/history/past-prime-ministers",
  openUniversity: "https://about.open.ac.uk/strategy-and-policies/history-ou",
  frenchArchives: "https://www.nationalarchives.gov.uk/education/resources/french-revolution/",
  parisMusees: "https://www.parismusees.paris.fr/en/parcours-thematiques/focus-on-paris-during-the-revolution",
  eiffel: "https://www.toureiffel.paris/en/the-monument/history",
  eiffelFigures: "https://www.toureiffel.paris/en/the-monument/key-figures",
  jacobin: "https://revolution.chnm.org/d/1094",
  robespierre: "https://www.britannica.com/biography/Maximilien-Robespierre",
};

const ctx = page => {
  if (page <= 591) return { chapter: "europe", chapterTitle: "ইউরোপ", topic: "uk-reference-and-past-questions-589-591", topicTitle: "যুক্তরাজ্য — রেফারেন্স ও বিগত বছরের প্রশ্ন", domain: "united-kingdom" };
  if (page === 592) return { chapter: "europe", chapterTitle: "ইউরোপ", topic: "france-reference-and-eiffel-tower-592", topicTitle: "ফ্রান্স — তথ্যভাণ্ডার ও আইফেল টাওয়ার", domain: "france" };
  return { chapter: "europe", chapterTitle: "ইউরোপ", topic: "french-revolution-and-jacobin-reference-593", topicTitle: "ফরাসি বিপ্লব ও জ্যাকোবিন রেফারেন্স", domain: "french-revolution" };
};
const fact = (page, title, body, status = "source_attributed", confidence = "medium", sources = [], timeSensitive = false) => ({ source_page: page, title, fact_text: body, status, confidence, sources, timeSensitive, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${body}`) });
const note = (page, title, content, status = "source_attributed", confidence = "high", timeSensitive = true, sources = []) => ({ source_page: page, title, content, status, confidence, sources, timeSensitive, ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${content}`) });
const mcq = (page, number, question, options, correct, source, confidence = "high", sources = [], timeSensitive = false) => ({ source_page: page, number, question, options, correct, source, status: sources.length ? "verified" : "source_attributed", confidence, sources, timeSensitive, ...ctx(page), canonical_hash: hash(`mcq|${page}|${number}|${question}`) });

const facts = [
  fact(589, "Representation of the People Act 1918 — qualified women’s suffrage", "UK Parliament অনুযায়ী ১৯১৮ সালের Representation of the People Act সম্পত্তি-যোগ্যতাসহ ৩০ বছরের বেশি বয়সী নারীদের ভোটাধিকার দেয়।", "verified", "high", [refs.women1918], true),
  fact(589, "The Open University — Royal Charter 1969", "The Open University-এর ইতিহাস অনুযায়ী প্রতিষ্ঠানটি ১৯৬৯ সালে Royal Charter লাভ করে।", "verified", "high", [refs.openUniversity], true),
  fact(589, "Buckingham Palace — উৎস-রেফারেন্স", "উৎসে Buckingham Palace-কে ব্রিটিশ রাজপরিবারের বাসভবন এবং Westminster, London-এর একটি স্থাপনা হিসেবে দেখানো হয়েছে।", "source_attributed", "high", [], true),
  fact(589, "Whitehall — উৎস-রেফারেন্স", "উৎসে Whitehall-কে London, England-এ ব্রিটিশ সরকারের প্রশাসনিক পরিসর/ভবন হিসেবে উপস্থাপন করা হয়েছে।", "source_attributed", "high", [], true),
  fact(589, "Union Jack — উৎস-রেফারেন্স", "উৎসে যুক্তরাজ্যের পতাকাকে Union Jack বলা হয়েছে।", "source_attributed", "high"),
  fact(589, "Waterloo — Duke of Wellington উৎস-রেফারেন্স", "উৎসে Waterloo যুদ্ধের বিজয়ী ব্রিটিশ সেনাপতি হিসেবে Duke of Wellington-এর নাম আছে।", "source_attributed", "high"),
  fact(589, "Pall Mall — উৎস-রেফারেন্স", "উৎসে Pall Mall-কে London-এর Westminster City-র একটি পরিচিত সড়ক বলা হয়েছে।", "source_attributed", "high"),
  fact(589, "Ted Hughes — উৎস-রেফারেন্স", "উৎসে Ted Hughes-কে ব্রিটিশ কবি বলা হয়েছে।", "source_attributed", "high"),
  fact(592, "France — Republic proclaimed in 1792", "Paris Musées-এর chronology অনুযায়ী ফ্রান্সে Republic ২২ সেপ্টেম্বর ১৭৯২ ঘোষণা করা হয়।", "verified", "high", [refs.parisMusees], true),
  fact(592, "Eiffel Tower — 1889 Exposition Universelle", "Official Eiffel Tower history অনুযায়ী Tower-টি ১৮৮৯ সালের Exposition Universelle উপলক্ষে নির্মিত হয়, যা French Revolution-এর শতবর্ষকে স্মরণ করেছিল।", "verified", "high", [refs.eiffel], true),
  fact(592, "Eiffel Tower — Paris, France", "উৎসে Eiffel Tower-এর অবস্থান Paris, France বলা হয়েছে; official Tower history এটিকে Paris-এর Champ-de-Mars প্রকল্প হিসেবে বর্ণনা করে।", "verified", "high", [refs.eiffel]),
  fact(593, "Bastille — 14 July 1789", "The National Archives অনুযায়ী ১৪ জুলাই ১৭৮৯ Paris-এর জনতা Bastille fortress/prison আক্রমণ করে; এই ঘটনাটি French Revolution-এর গুরুত্বপূর্ণ সূচনাকালীন ঘটনা।", "verified", "high", [refs.frenchArchives], true),
  fact(593, "Louis XVI — 21 January 1793 execution", "Paris Musées অনুযায়ী Louis XVI-কে ২১ জানুয়ারি ১৭৯৩ guillotine-এ মৃত্যুদণ্ড দেওয়া হয়।", "verified", "high", [refs.parisMusees], true),
  fact(593, "Robespierre — 28 July 1794 execution", "Paris Musées এবং Britannica অনুযায়ী Robespierre ২৭ জুলাই ১৭৯৪ গ্রেপ্তার হন এবং পরের দিন, ২৮ জুলাই, guillotine-এ মৃত্যুদণ্ড পান।", "verified", "high", [refs.parisMusees, refs.robespierre], true),
];

const notes = [
  note(589, "যুক্তরাজ্য রেফারেন্স — source-attribution boundary", "উৎসে Whitehall, Union Jack, Waterloo, Pall Mall, Ted Hughes এবং আরও UK reference lines আছে।\nসতর্কতা | institutional wording, cultural labels, Royal Family residence shorthand, এবং source-era reference claims আপডেট করা হয়নি; এগুলো কেবল visually reviewed source-attributed study reference হিসেবে রাখা হয়েছে।", "source_attributed", "high", true),
  note(590, "যুক্তরাজ্য past-exam MCQ — quality boundary", "পৃষ্ঠা 590-এ ১৩টি printed-key MCQ আছে। Q02–Q08, Q10–Q13-এর stem/options/key visually complete; তবে Q01-এ duplicated/corrupted option text এবং Q09-এ time-sensitive Downing Street office/residence premise থাকায় withheld। Q12 ও Q13 past-exam wording source-attributed রেখেছে।", "source_attributed", "high", true, [refs.magnaCarta, refs.downingStreet]),
  note(591, "যুক্তরাজ্য past-exam MCQ — quality boundary", "পৃষ্ঠা 591-এর Q17, Q19, Q20, Q22, Q23, Q25 ও Q26 complete option/key boundary পূরণ করে। Q14-এর written-constitution premise, Q15-এর absolute first-document framing, Q16-এর reductive marriage premise, Q18/Q21-এর unclear options, এবং Q24-এর transcript/key conflict withheld। Q19-এর Walpole ‘first PM’ wording এবং Q25-এর longest-reign context explanation-এ caveated।", "source_attributed", "high", true, [refs.pastPm]),
  note(592, "ফ্রান্স — source-attribution boundary", "উৎসে France geography, 14 July, Paris cultural labels, Gaul, Versailles, Hundred Years’ War, এবং presidential-term reference আছে।\nসতর্কতা | France ‘independence war’ label, Versailles-as-Paris claim, blurred building/person names, army nickname, Iron Lady/Sun King distortions, and Eiffel financing claim withheld; no correction was silently substituted.", "source_attributed", "high", true),
  note(593, "ফরাসি বিপ্লব ও Jacobin — chronology boundary", "উৎসে 1789–1799 periodization, Bastille, Rousseau/Voltaire, Liberty–Equality–Fraternity, Robespierre, Napoleon, and Jacobin Club reference আছে।\nসতর্কতা | credible sources differ on periodization; ‘Napoleon father of the Revolution’, ‘Elite Revolution’, source's false 21 January 1793 Robespierre execution, and Robespierre-founder claim withheld. Jacobin reference is retained only with source attribution and explicit uncertainty.", "conflicting_source", "high", true, [refs.frenchArchives, refs.parisMusees, refs.jacobin]),
];

const mcqs = [
  mcq(590, "02", "শিল্প বিপ্লব সংঘটিত হয় কোন শতকে?", ["সপ্তদশ শতকে", "অষ্টাদশ শতকে", "উনবিংশ শতকে", "বিশ শতকে"], "খ", "DU খ ০৬–০৭", "high"),
  mcq(590, "03", "যুক্তরাজ্যের অর্থমন্ত্রীর সরকারি পদবি কী?", ["Chancellor of the Exchequer", "Lord Privy Seal", "Secretary of the Treasury", "Chief of Finance"], "ক", "DU খ ০৬–০৭, ১০–১১", "high", [], true),
  mcq(590, "04", "ব্রিটিশ রাজপরিবারের বাসভবনের নাম কোনটি?", ["Victoria Palace", "Buckingham Palace", "Elizabeth Palace", "Edward Palace"], "খ", "DU খ ০৩–০৪"),
  mcq(590, "05", "Magna Carta, 1215 কোন দেশে গৃহীত হয়?", ["যুক্তরাজ্য", "ইংল্যান্ড", "ফ্রান্স", "চীন"], "খ", "DU খ ০৩–০৪", "high", [refs.magnaCarta], true),
  mcq(590, "06", "ব্রিটিশ প্রধানমন্ত্রীর সরকারি বাসভবন কোনটি?", ["Chequers House", "Whitehall", "১০ নং Downing Street", "Buckingham Palace"], "গ", "DU খ ০০–০১", "high", [refs.downingStreet], true),
  mcq(590, "07", "ইউরোপে শিল্প বিপ্লব সংঘটিত হয় কোন শতাব্দীতে?", ["বিশ শতকে", "উনবিংশ শতকে", "অষ্টাদশ শতকে", "সপ্তদশ শতকে"], "গ", "DU খ ০৬–০৭ / চবি-খ ০২–০৩"),
  mcq(590, "08", "India House কোথায় অবস্থিত?", ["দিল্লি", "লন্ডন", "নিউইয়র্ক", "সিমলা"], "খ", "রাবি-হিসাববিজ্ঞান ০৭–০৮ / DU খ ০২–০৩", "high", [], true),
  mcq(590, "10", "কোন দেশের সংবিধান অলিখিত?", ["যুক্তরাজ্য", "চীন", "যুক্তরাষ্ট্র", "জাপান"], "ক", "DU ঘ ০৪–০৫", "high", [], true),
  mcq(590, "11", "Trafalgar Square কোথায় অবস্থিত?", ["রাশিয়া", "ইংল্যান্ড", "ফ্রান্স", "চীন"], "খ", "43 BCS"),
  mcq(590, "12", "যুক্তরাজ্যের রানি কোন দেশের সাংবিধানিক রাষ্ট্রপ্রধান নন?", ["ফিজি", "কানাডা", "অস্ট্রিয়া", "অস্ট্রেলিয়া"], "গ", "26 BCS", "high", [], true),
  mcq(590, "13", "কোন দেশের ডাকটিকিটে সেই দেশের নাম লেখা থাকে না?", ["দক্ষিণ কোরিয়া", "যুক্তরাজ্য", "যুক্তরাষ্ট্র", "অস্ট্রিয়া"], "খ", "MC ০৭–০৮", "high", [], true),
  mcq(591, "17", "ব্রিটেনের সাবেক প্রধানমন্ত্রী Margaret Thatcher ক্ষমতায় ছিলেন কত বছর?", ["৯ বছর", "১০ বছর", "১১ বছর", "১২ বছর"], "গ", "ব্যাংক অধিদপ্তর সহকারী–১০", "high", [refs.pastPm], true),
  mcq(591, "19", "ব্রিটেনের প্রথম প্রধানমন্ত্রীর নাম কী?", ["Robert Walpole", "Charles", "John Adams", "John Walpole"], "ক", "রাবি ০৫–০৬", "high", [refs.pastPm], true),
  mcq(591, "20", "কোন দেশের পতাকাকে Union Jack বলা হয়?", ["ফ্রান্স", "ইতালি", "ব্রিটেন", "কানাডা"], "গ", "রাবি-রাষ্ট্রবিজ্ঞান ০৭–০৮ / জবি-১ ০৬–০৭"),
  mcq(591, "22", "The name Margaret Thatcher relates to—", ["Information Technology", "Politics", "Book", "Space technology"], "খ", "Bangladesh Commerce Bank Officer–06"),
  mcq(591, "23", "শিল্প বিপ্লব যে দেশে শুরু হয়েছিল—", ["মার্কিন যুক্তরাষ্ট্র", "ফ্রান্স", "জার্মানি", "ইংল্যান্ড"], "ঘ", "রাবি-ইতিহাস ০৭–০৮ / দুদক সহকারী পরিদর্শক ০৪"),
  mcq(591, "25", "ব্রিটিশ ইতিহাসে দীর্ঘকাল শাসনকারী রাজা/রানির নাম—", ["রানি ভিক্টোরিয়া", "রানি দ্বিতীয় এলিজাবেথ", "রাজা পঞ্চম জর্জ", "রাজা দ্বিতীয় এডওয়ার্ড"], "খ", "ববি ১৫–১৬", "high", [], true),
  mcq(591, "26", "‘Workshop of the World’ বলা হতো—", ["ব্রিটেনকে", "ফ্রান্সকে", "জার্মানিকে", "রাশিয়াকে"], "ক", "জাহবি CS ১৫–১৬"),
];

const topics = [
  ["europe", "যুক্তরাজ্য — রেফারেন্স ও বিগত বছরের প্রশ্ন", "uk-reference-and-past-questions-589-591", 589, 7],
  ["europe", "ফ্রান্স — তথ্যভাণ্ডার ও আইফেল টাওয়ার", "france-reference-and-eiffel-tower-592", 592, 8],
  ["europe", "ফরাসি বিপ্লব ও জ্যাকোবিন রেফারেন্স", "french-revolution-and-jacobin-reference-593", 593, 9],
];
const tags = [
  ["europe", "Europe", "domain", "Source-derived Europe reference."], ["united-kingdom", "United Kingdom", "domain", "United Kingdom source material."], ["france", "France", "domain", "France source material."],
  ["reference-note", "Structured source note", "content_type", "Structured source reference with explicit caveats."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with printed source key."], ["answer-key", "Answer key", "content_type", "Correct option from printed key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Directly corroborated by cited evidence."], ["time-sensitive", "Time-sensitive reference", "quality", "Historical, institutional, or dated source material."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed examination label."], ["bcs", "Bangladesh Civil Service", "exam_source", "BCS printed examination label."], ["medical-admission", "Medical admission test", "exam_source", "Medical admission test printed label."], ["other-bangladesh-exam", "Other Bangladesh examination", "exam_source", "Printed competitive-examination label retained without expansion."],
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : source.includes("BCS") ? ["Bangladesh Civil Service", null, "competitive", "bcs"] : source.includes("MC") ? ["Medical admission test", null, "admission", "medical-admission"] : ["Other Bangladesh examination", null, "competitive", "other-bangladesh-exam"];
const entityRef = (kind, canonicalHash) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(canonicalHash)} LIMIT 1)`;
const quality = row => row.status === "verified" ? "externally-verified" : "source-attributed";

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const checks = [...facts.map(row => ({ kind: "fact", claim: row.fact_text, ...row })), ...notes.map(row => ({ kind: "note", claim: row.content, ...row })), ...mcqs.map(row => ({ kind: "mcq", claim: `${row.question} — printed answer: ${row.correct}`, ...row }))];
  const audit = {
    batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION,
    source_pages: pages.map(page => ({ page: page.source_page, review_status: "completed_image_grounded_review", image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })),
    generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length,
    verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: checks.filter(row => row.status === "conflicting_source").length, source_attributed: checks.filter(row => row.status === "source_attributed").length },
    source_anomalies: ["All five pages were rendered at 300 DPI, transcribed with gpt-5-mini, and reviewed through all 35 ordered overlap-safe tiles.", "Pages 590–591 contain 18 source-complete MCQs; ten unsafe MCQs are withheld for corrupted options, unsound premises, time-sensitive office assignments, or visual/key conflicts.", "The scan’s global Open University superlative, France reference distortions, Eiffel Tower financing claim, false Robespierre date, and Jacobin-founder claim are withheld rather than corrected into invented records.", "Political, institutional, constitutional, geographic-label, cultural-label, and historical periodization language remains explicitly source-attributed or caveated."],
    quality_gates: ["Exactly physical source pages 589–593 are imported.", "Every imported MCQ has four visually reviewed options and one printed source key.", "No corrupted, ambiguous, time-sensitive, institutionally unsafe, or historically conflicting MCQ is imported.", "Content tags use only approved categories; country and region tags use category domain.", "Upserts use canonical hashes and stable derived-record keys."],
  };
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with explicit review and verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 589: 592, 590: 593, 591: 594, 592: 595, 593: 596 };
  const pageSql = pages.map(page => { const c = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: "completed_image_grounded_review", corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: `${workDir}/visual_review_589_593.md`, external_verification_report: `${workDir}/external_verification.md`, classification_report: `${workDir}/classification_decisions.md` }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},'educational'::page_kind,${q(page.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered source-tile review, withholding rules, source attribution, and explicit verification status.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.status, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct corroboration is recorded in the batch verification ledger.' ELSE 'Source-attributed material retained after ordered image review; it is not silently updated as a current assertion.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name, institution, examType, normalizedName] = exam(row.source); const keys = ["ক", "খ", "গ", "ঘ"]; const optionSql = row.options.map((option, index) => `INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index + 1},${keys[index] === row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); const explanation = row.status === "verified" ? "Printed answer key visually reviewed; direct corroboration and scope are recorded in the batch verification ledger." : "Printed answer key visually reviewed; this past-exam wording is source-attributed and bounded in the batch verification ledger."; return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(examType)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalizedName)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalizedName)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},${q(explanation)},${row.source_page},'এই অধ্যায়ের সাথে জড়িত বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${optionSql} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalizedName)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const assignment = (kind, row, tagSlugs) => tagSlugs.map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,${q(kind)},${entityRef(kind, row.canonical_hash)},${row.source_page},${q(row.confidence)}::confidence_level,'batch-0589-0593-quality-pipeline' FROM public.content_tags t WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n");
  const domainTag = row => row.domain === "united-kingdom" ? "united-kingdom" : row.domain === "france" ? "france" : "europe";
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row => `(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;
${facts.map(row => assignment("fact", row, ["europe", domainTag(row), quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])])).join("\n")}
${notes.map(row => assignment("note", row, ["europe", domainTag(row), "reference-note", quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])])).join("\n")}
${mcqs.map(row => assignment("mcq", row, ["europe", domainTag(row), "past-exam-mcq", "answer-key", exam(row.source)[3], quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])])).join("\n")}`;
  const verificationSql = checks.map(row => { const dbStatus = row.status === "conflicting_source" ? "conflicting" : row.status; const noteText = row.status === "verified" ? "Direct corroboration is listed in the batch verification ledger." : row.status === "conflicting_source" ? "Conflict is explicitly documented in the batch verification ledger; record is a caveated source note." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage."; return `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${entityRef(row.kind, row.canonical_hash)},${q(row.claim)},NULL,${q(dbStatus)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(noteText)} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${entityRef(row.kind, row.canonical_hash)} AND v.claim_text=${q(row.claim)});`; }).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0589-0593:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0589-0593:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0589-0593:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0589-0593:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0589-0593:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0589-0593:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page BETWEEN 589 AND 593 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0589_0593.mjs. Source pages 589–593 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page => page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { sql, audit } = await buildBatch();
  const counts = { batch_pages: BATCH_PAGES, review_tiles: 35, eligible_mcqs: mcqs.length, eligible_mcq_options: mcqs.length * 4, withheld_mcqs: 10, fact_candidates: facts.length, note_candidates: notes.length, verification_statuses: audit.verification_counts };
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, "validated_import.sql"), sql);
  await fs.writeFile(path.join(outputDir, "batch_audit.json"), JSON.stringify(audit, null, 2));
  await fs.writeFile(path.join(outputDir, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql }));
  await fs.writeFile(path.join(workDir, "import_input_counts.json"), JSON.stringify(counts, null, 2));
  console.log(JSON.stringify({ outputDir, ...audit, counts }, null, 2));
}
