import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0554-0558";
const outputDir = path.join(root, "supabase", "batch-0554-0558");
export const BATCH_PAGES = [554, 555, 556, 557, 558];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0554-0558-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));

const refs = {
  plo1964: "https://history.state.gov/historicaldocuments/frus1964-68v18/d356",
  oslo: "https://history.state.gov/milestones/1993-2000/oslo",
  recognition: "https://www.un.org/unispal/document/auto-insert-205528/",
  nobel: "https://www.nobelprize.org/prizes/peace/1994/summary/",
  balfour: "https://www.un.org/unispal/document/auto-insert-193242/",
  war1948: "https://history.state.gov/milestones/1945-1952/arab-israeli-war",
  war1973: "https://history.state.gov/milestones/1969-1976/arab-israeli-war-1973",
};

const ctx = page => {
  if (page === 554) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "al-aqsa-plo-israel-reference", topicTitle: "আল-আকসা, PLO ও ইসরাইল — উৎস-রেফারেন্স", domain: "palestine" };
  if (page === 555) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "intifada-hebron-past-questions", topicTitle: "ইন্তিফাদা ও হেবরন — বিগত প্রশ্ন", domain: "palestine" };
  return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "al-aqsa-plo-israel-reference", topicTitle: "আল-আকসা, PLO ও ইসরাইল — উৎস-রেফারেন্স", domain: "israel" };
};
const fact = (page, title, body, status = "source_attributed", confidence = "medium", sources = [], domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, fact_text: body, status, confidence, sources, domain, timeSensitive, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${body}`) });
const note = (page, title, body, confidence = "medium", domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, content: body, status: "source_attributed", confidence, sources: [], domain, timeSensitive, ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${body}`) });
const mcq = (page, number, question, options, correct, source, confidence = "high", domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, number, question, options, correct, source, confidence, status: "source_attributed", sources: [], domain, timeSensitive, ...ctx(page), canonical_hash: hash(`mcq|${page}|${number}|${question}`) });

const facts = [
  fact(554, "PLO গঠন (১৯৬৪)", "U.S. Office of the Historian-এর নথিতে ১৯৬৪ সালে Palestine Liberation Organization (PLO) গঠনের উল্লেখ আছে।", "verified", "high", [refs.plo1964], "plo", true),
  fact(554, "PLO–Israel mutual recognition (১৯৯৩)", "৯ সেপ্টেম্বর ১৯৯৩-এর চিঠিতে PLO ইসরাইলের শান্তি ও নিরাপত্তার মধ্যে অস্তিত্বের অধিকার স্বীকার করে; ইসরাইল PLO-কে Palestinian people-এর প্রতিনিধি হিসেবে স্বীকৃতি দেয়।", "verified", "high", [refs.recognition], "plo", true),
  fact(554, "Oslo Declaration of Principles (১৯৯৩)", "U.S. Office of the Historian অনুযায়ী, ১৩ সেপ্টেম্বর ১৯৯৩ PLO Negotiator Mahmoud Abbas ও Israeli Prime Minister Yitzhak Rabin Declaration of Principles-এ স্বাক্ষর করেন।", "verified", "high", [refs.oslo], "plo", true),
  fact(554, "Yasser Arafat-এর Nobel Peace Prize (১৯৯৪)", "Nobel Foundation অনুযায়ী Yasser Arafat, Shimon Peres ও Yitzhak Rabin যৌথভাবে ১৯৯৪ সালের Nobel Peace Prize পান।", "verified", "high", [refs.nobel], "yasser-arafat", true),
  fact(555, "Hebron Protocol (১৯৯৭)", "U.S. Office of the Historian অনুযায়ী, ১৯৯৭ সালের জানুয়ারিতে U.S. mediation-এর পরে Israel ও Palestinian Authority Hebron Protocol-এ স্বাক্ষর করে।", "verified", "high", [refs.oslo], "palestine", true),
  fact(556, "Balfour Declaration (১৯১৭)", "United Nations-এ সংরক্ষিত UK/Non-UN নথি অনুযায়ী, Arthur James Balfour ২ নভেম্বর ১৯১৭ Lord Rothschild-কে চিঠিটি লেখেন; এতে Palestine-এ Jewish people-এর national home প্রতিষ্ঠাকে সমর্থনের ভাষা আছে।", "verified", "high", [refs.balfour], "israel", true),
  fact(556, "Israel independence announcement (১৪ মে ১৯৪৮)", "U.S. Office of the Historian অনুযায়ী, ১৪ মে ১৯৪৮ state of Israel-এর independence announcement-এর পর ১৯৪৮ Arab–Israeli War শুরু হয়।", "verified", "high", [refs.war1948], "israel", true),
  fact(558, "১৯৪৮ Arab–Israeli War-এর তারিখ ও প্রেক্ষিত", "U.S. Office of the Historian ১৯৪৮ Arab–Israeli War-কে ১৪ মে ১৯৪৮-এর independence announcement-এর পর সংঘটিত সংঘাত হিসেবে বর্ণনা করে।", "verified", "high", [refs.war1948], "israel", true),
  fact(558, "১৯৭৩ Arab–Israeli War-এর তারিখ ও প্রেক্ষিত", "U.S. Office of the Historian অনুযায়ী ৬ অক্টোবর ১৯৭৩ Egypt ও Syria Sinai Peninsula ও Golan Heights-এ Israel-এর বাহিনীর ওপর আক্রমণ করে।", "verified", "high", [refs.war1973], "israel", true),
  fact(558, "Golan সংক্রান্ত ২০১৮ UN-বক্তব্যের উৎস-সতর্কতা", "উৎসে ‘জাতিসংঘ গোলান মালভূমিকে সিরিয়ার বলে ঘোষণা দেয়—২০১৮ সালে’ বলা হয়েছে। এই নির্দিষ্ট তারিখ ও সূত্রায়ন স্বাধীনভাবে corroborate করা যায়নি; তাই এটি conflicting source statement হিসেবে সংরক্ষিত, সংশোধন করা হয়নি।", "conflicting", "high", [refs.oslo], "israel", true),
];

const notes = [
  note(554, "আল-আকসা — উৎস-সময়ভিত্তিক রেফারেন্স", "উৎসে আল-আকসা/বায়তুল মুকাদ্দাস, প্রথম কিবলা, জেরুজালেমের পুরনো শহর, ধর্মীয় সম্পর্ক ও ১৯৬৭-সংক্রান্ত বক্তব্য আছে।\nসতর্কতা | ধর্মীয়, territorial ও রাজনৈতিক wording কেবল source-attributed অবস্থায় রাখা হয়েছে; অস্পষ্ট ‘Haram Sharif’ scope বা উক্তিগুলো স্বাধীন current fact হিসেবে আমদানি করা হয়নি।", "medium", "al-aqsa", true),
  note(554, "PLO ও ইয়াসির আরাফাত — উৎস-সময়ভিত্তিক রেফারেন্স", "উৎসে PLO, Fatah, Orient House, Ramallah, ১৯৬৯, ১৯৯৩ এবং ইয়াসির আরাফাতের জন্ম, উপনাম, Nobel Prize, মৃত্যু ও সমাহি-সংক্রান্ত বক্তব্য আছে।\nসতর্কতা | ‘বর্তমান নেতা’, office/title ও headquarters ভাষা time-sensitive; কেবল নির্দিষ্ট verified historic events আলাদা fact হিসেবে নেওয়া হয়েছে।", "medium", "plo", true),
  note(555, "ইন্তিফাদা — উৎস-সংজ্ঞা ও বিগত প্রশ্ন", "উৎসে ইন্তিফাদাকে ফিলিস্তিনিদের গণজাগরণ এবং আরবি শব্দ হিসেবে বর্ণনা করা হয়েছে।\nসতর্কতা | রাজনৈতিক framing source-attributed; উৎসের ভাষা পরিবর্তন বা সমসাময়িক ব্যাখ্যা হিসেবে উপস্থাপন করা হয়নি।", "high", "palestine", true),
  note(555, "হেবরন মসজিদে হত্যাকাণ্ড — উৎস-সতর্কতা", "উৎসে হেবরন, ১৯৯৪ সালের মসজিদ-হত্যাকাণ্ড ও ১৯৯৭ Hebron agreement/Protocol-এর কথা আছে।\nসতর্কতা | OCR/scan-এ নিহতের সংখ্যা (২৫/১২৫) এবং নামের পাঠ অনিরাপদ; এই casualty/attribution line fact হিসেবে আমদানি করা হয়নি।", "medium", "palestine", true),
  note(556, "ইসরাইল — উৎস-সময়ভিত্তিক ঐতিহাসিক রেফারেন্স", "উৎসে Palestine/Israel history, Jerusalem-এর ধর্মীয় গুরুত্ব, diaspora ও ১৯৪৮-সম্পর্কিত রাজনৈতিক narrative আছে।\nসতর্কতা | এই narrative রাজনৈতিক ও territorial; এটি source-attributed note, কোনো present-tense geographic/legal assertion নয়।", "medium", "israel", true),
  note(556, "Balfour Declaration — উৎস ও যাচাইকৃত প্রাথমিক নথি", "উৎসে Balfour Declaration, Arthur James Balfour, Rothschild ও ১৯১৭ সালের কথা আছে।\nসতর্কতা | primary document-এ ২ নভেম্বর ১৯১৭-এর চিঠি ও national-home wording দেখা যায়; source-এর consequence framing আলাদাভাবে source-attributed থাকে।", "high", "israel", true),
  note(556, "ইসরাইলের basic information ও recognition list — উৎস-সতর্কতা", "উৎসে ভাষা, shekel, Knesset, capital-claim এবং ১৯৪৮/১৯৪৯/১৯৭৯ recognition list আছে।\nসতর্কতা | ভাষা-status, capital, recognition order ও diplomatic framing পরিবর্তনশীল বা সংবেদনশীল; এগুলো বর্তমান independent facts হিসেবে নয়, source-attributed table note হিসেবে রাখা হয়েছে।", "medium", "israel", true),
  note(557, "ইসরাইলের সীমান্ত, শহর ও বন্দর — উৎস-ম্যাপ রেফারেন্স", "উৎসের মানচিত্রে সীমান্ত, Green Line, Haifa, Tel Aviv, Ashdod, Eilat, Gaza, West Bank এবং conflict callout আছে।\nসতর্কতা | map labels ও territorial/capital statements source-attributed; অসম্পূর্ণ city labels, superlatives এবং blurred dispute captions withheld।", "medium", "israel", true),
  note(558, "আরব–ইসরাইল চার যুদ্ধ — উৎস-টেবিল", "উৎসে ১৯৪৮, ১৯৫৬, ১৯৬৭ ও ১৯৭৩ সালের চারটি যুদ্ধের পক্ষ ও ফলাফল তালিকাভুক্ত আছে।\nসতর্কতা | ফলাফল, territorial wording, OIC line এবং oil-crisis language রাজনৈতিক/ঐতিহাসিক সংক্ষিপ্তসার; tableটি কেবল source-attributed অবস্থায় রাখা হয়েছে।", "medium", "israel", true),
  note(558, "সীমান্ত-বিরোধ ও আরব রাষ্ট্রগুলোর সঙ্গে সম্পর্ক — উৎস-টেবিল", "উৎসে Dead Sea, Lebanon, Sinai, Golan, Wazzani এবং Egypt/Jordan/UAE/Bahrain/Sudan/Morocco-সংক্রান্ত diplomatic list আছে।\nসতর্কতা | borders, disputes, river/farm names ও recognition/normalization status time-sensitive; ‘UN Golan 2018’ claim conflicting হিসেবে আলাদা flagged fact-এ সংরক্ষিত।", "medium", "israel", true),
];

const mcqs = [
  mcq(555, "01", "ইন্তিফাদা কী?", ["ইসরায়েলি দমনদারিত্বের বিরুদ্ধে ফিলিস্তিনী গণজাগরণ", "দেশীয় শাসনের বিরুদ্ধে বুদ্ধিজীবী জাতীয়তাবাদী আন্দোলন", "ফরাসি কৃষি বিদ্রোহ", "মুক্তিযুদ্ধের স্বাধীনতা যুদ্ধ"], "ক", "DU '97-98; DU '04-05", "high", "palestine", true),
  mcq(555, "02", "প্যালেস্টাইন নেতা ইয়াসির আরাফাতকে কোথায় সমাহিত করা হয়েছে?", ["গাজা", "কায়রো", "রামাল্লা", "জেরুজালেম"], "গ", "DU '92-93", "high", "palestine", true),
  mcq(555, "03", "Orient House কার সদর দফতর?", ["PLO", "USA-র ডেমোক্র্যাটিক পার্টি", "ব্রিটিশ লেবার পার্টি", "ভারতীয় জাতীয় কংগ্রেস"], "ক", "DU '92-03", "high", "plo", true),
  mcq(555, "04", "‘ইন্তিফাদা’ শব্দের কি মূল?", ["যুদ্ধ", "শান্তি", "অভ্যুত্থান", "কূটনীতি"], "গ", "DU '92-01", "high", "palestine", true),
  mcq(555, "06", "PLO এর সদর দফতর কোথায়?", ["রামাল্লা", "জেনিন", "গাজা", "জেরুজালেম"], "ক", "10 BCS", "medium", "plo", true),
  mcq(555, "07", "পিএলও কত সালে গঠিত হয়?", ["১৯৬৪", "১৯৬৫", "১৯৬৬", "১৯৬৭"], "ক", "23 BCS", "high", "plo", true),
  mcq(555, "10", "ফিলিস্তিনি আধিকারিক নেতা ইয়াসির আরাফাত কোথায় মৃত্যু বরণ করেন?", ["মিশর", "মুকুত্তায়", "ফ্রান্স", "জার্মানিতে"], "গ", "জাতি সম্প্রতি, 10-11", "medium", "yasser-arafat", true),
  mcq(555, "11", "রামাল্লা কোথায় অবস্থিত?", ["ইরাক", "আফগানিস্তান", "ফিলিস্তিন", "মিসর"], "গ", "অস্পষ্ট মুদ্রিত লেবেল, 04-05", "medium", "palestine", true),
];

const tags = [
  ["west-asia", "West Asia", "domain", "Source-derived Middle East reference."], ["palestine", "Palestine", "domain", "Palestine source material."], ["israel", "Israel", "domain", "Israel source material."], ["al-aqsa", "Al-Aqsa", "domain", "Al-Aqsa source material."], ["plo", "PLO", "domain", "Palestine Liberation Organization source material."], ["yasser-arafat", "Yasser Arafat", "domain", "Yasser Arafat source material."],
  ["reference-note", "Structured source note", "content_type", "Structured source reference with explicit caveats."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with a printed source key."], ["answer-key", "Answer key", "content_type", "Correct option from the printed key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Directly corroborated by cited official evidence."], ["conflicting-source", "Historically qualified source claim", "quality", "The printed source conflicts with or compresses an independently checked historical distinction."], ["time-sensitive", "Time-sensitive reference", "quality", "Political, institutional, territorial, religious, or diplomatic source material."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed exam label."], ["bcs", "Bangladesh Civil Service", "exam_source", "Bangladesh Civil Service printed exam label."], ["jati-samproti", "জাতি সম্প্রতি", "exam_source", "Printed examination/source label preserved from the scan."], ["unresolved-printed-label", "Unresolved printed label", "exam_source", "Partly unclear examination/source label retained without invention."],
];
const exam = source => {
  if (source.includes("DU")) return ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"];
  if (source.includes("BCS")) return ["Bangladesh Civil Service", null, "competitive", "bcs"];
  if (source.includes("জাতি")) return ["জাতি সম্প্রতি", null, "competitive", "jati-samproti"];
  return ["Unresolved printed label", null, "competitive", "unresolved-printed-label"];
};
const quality = row => row.status === "verified" ? "externally-verified" : row.status === "conflicting" ? "conflicting-source" : "source-attributed";
const entityRef = (kind, h) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(h)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const topics = [
    ["middle-east-country-profiles", "আল-আকসা, PLO ও ইসরাইল — উৎস-রেফারেন্স", "al-aqsa-plo-israel-reference", 554, 2],
    ["middle-east-country-profiles", "ইন্তিফাদা ও হেবরন — বিগত প্রশ্ন", "intifada-hebron-past-questions", 555, 3],
  ];
  const checks = [...facts.map(row => ({ kind: "fact", claim: row.fact_text, ...row })), ...notes.map(row => ({ kind: "note", claim: row.content, ...row })), ...mcqs.map(row => ({ kind: "mcq", claim: `${row.question} — printed answer: ${row.correct}`, ...row }))];
  const audit = {
    batch_pages: BATCH_PAGES,
    pipeline_version: PIPELINE_VERSION,
    source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })),
    generated_facts: facts.length,
    generated_notes: notes.length,
    generated_mcqs: mcqs.length,
    generated_options: mcqs.length * 4,
    generated_flashcards: facts.length + notes.length + mcqs.length,
    verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: checks.filter(row => row.status === "conflicting").length, source_attributed: checks.filter(row => row.status === "source_attributed").length },
    source_anomalies: [
      "All five pages rendered at 300 DPI and completed gpt-5-mini transcription plus independent image-grounded review.",
      "All 35 ordered overlapping dense-image tiles were reviewed.",
      "Page 555 questions 05 and 08 are withheld because their stems are corrupted; question 09 is withheld because its printed key conflicts with historical context.",
      "Page 555 Hebron casualty and perpetrator lines are withheld because the scan preserves uncertain/incorrect numeric and attribution content.",
      "Page 557 is map-heavy and incomplete labels are retained only in the visual review, not reconstructed as database facts.",
      "The page 558 UN/Golan 2018 wording is retained as an explicit conflicting source claim, not silently corrected.",
    ],
    quality_gates: [
      "Exactly physical pages 554–558 are imported.",
      "Every imported MCQ has four visually reviewed source options and one printed key.",
      "No blurry, corrupted, reconstructed, or historically inconsistent MCQ is imported.",
      "Tags use only approved categories and region/person/institution labels use category domain.",
      "Upserts are idempotent by canonical hash and stable derived-record keys.",
    ],
  };
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with explicit review and verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 554: 497, 555: 498, 556: 499, 557: 500, 558: 501 };
  const pageSql = pages.map(page => { const c = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: "/home/ubuntu/dontonyo-work/batch-0554-0558/visual_review_554_558.md", external_verification_report: "/home/ubuntu/dontonyo-work/batch-0554-0558/external_verification.md", classification_report: "/home/ubuntu/dontonyo-work/batch-0554-0558/classification_decisions.md" }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},${q(page.source_page === 555 ? "mcq" : "educational")}::page_kind,${q(page.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered source-tile review, withholding rules, and explicit verification status.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.status, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct official corroboration is recorded in the batch verification ledger.' WHEN 'conflicting' THEN 'The printed source is retained with a directly cited historical caveat and is not silently corrected.' ELSE 'Source-attributed material retained after ordered image review; it is not silently updated as a current assertion.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name,institution,examType,normalizedName] = exam(row.source); const keys=["ক","খ","গ","ঘ"]; const options=row.options.map((option,index)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index+1},${keys[index]===row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); const explanation = "Printed answer key retained as source-attributed, time-sensitive material; all four options and the examination label were visually validated."; return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(examType)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalizedName)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalizedName)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},${q(explanation)},${row.source_page},'বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${options} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalizedName)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const factTags = facts.map(row => ["west-asia", row.domain, quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0554-0558-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const noteTags = notes.map(row => ["west-asia", row.domain, "reference-note", "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0554-0558-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const mcqTags = mcqs.map(row => ["west-asia", row.domain, "past-exam-mcq", "answer-key", exam(row.source)[3], "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0554-0558-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row=>`(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${factTags}\n${noteTags}\n${mcqTags}`;
  const verificationSql = checks.map(row => `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${entityRef(row.kind,row.canonical_hash)},${q(row.claim)},NULL,${q(row.status)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(row.status === "verified" ? "Direct official corroboration is listed in the batch verification ledger." : row.status === "conflicting" ? "The printed source has a direct historical caveat; the wording is retained without silent correction." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${entityRef(row.kind,row.canonical_hash)} AND v.claim_text=${q(row.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0554-0558:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 554 AND 558 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0554-0558:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0554-0558:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 554 AND 558 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0554-0558:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0554-0558:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page=555 AND m.source_question_number IN ('01','02','03','04','06','07','10','11') AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0554-0558:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 554 AND 558 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 554 AND 558 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page=555 AND m.source_question_number IN ('01','02','03','04','06','07','10','11') AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0554_0558.mjs. Source pages 554–558 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page=>page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { const {sql,audit}=await buildBatch(); await fs.mkdir(outputDir,{recursive:true}); await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql); await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2)); await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql})); console.log(JSON.stringify({outputDir,...audit},null,2)); }
