import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0564-0568";
const outputDir = path.join(root, "supabase", "batch-0564-0568");
export const BATCH_PAGES = [564, 565, 566, 567, 568];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0564-0568-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));

const refs = {
  ataturk: "https://www.ktb.gov.tr/EN-103908/biography-of-ataturk.html",
  turkey: "https://www.britannica.com/place/Turkey/Declaration-of-the-Turkish-republic",
  troy: "https://whc.unesco.org/en/list/849/",
  uae: "https://uaecabinet.ae/en/uae",
  palm: "https://eros.usgs.gov/earthshots/palm-jumeirah",
  syriaUn: "https://ask.un.org/faq/97169",
  aleppo: "https://www.britannica.com/place/Aleppo",
  golanMission: "https://www.un.int/syria/syria/syrian-golan",
  ibnSaud: "https://www.britannica.com/biography/Ibn-Saud",
  saudiRiyal: "https://www.sama.gov.sa/en-US/Currency/SRS/Pages/default.aspx",
  saudiFlag: "https://saudipedia.com/en/why-is-the-saudi-national-flag-not-flown-at-half-mast",
  imru: "https://www.britannica.com/biography/Imru-al-Qays-Arab-poet",
  chinaConstitution: "https://english.www.gov.cn/archive/lawsregulations/201911/20/content_WS5ed8856ec6d0b3f0e9499913.html",
  mayFourth: "https://www.nationalarchives.gov.uk/education/resources/may-fourth-movement-1919/",
};

const ctx = page => {
  if (page === 564) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "turkey-ottoman-ataturk-reference", topicTitle: "তুরস্ক — উসমানীয় সাম্রাজ্য ও আতাতুর্ক", domain: "turkey" };
  if (page === 565) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "turkey-past-questions-uae-reference", topicTitle: "তুরস্কের বিগত প্রশ্ন ও সংযুক্ত আরব আমিরাত", domain: "turkey" };
  if (page === 566) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "syria-reference-past-questions", topicTitle: "সিরিয়া — উৎস-রেফারেন্স ও বিগত প্রশ্ন", domain: "syria" };
  if (page === 567) return { chapter: "middle-east-country-profiles", chapterTitle: "মধ্যপ্রাচ্যের দেশসমূহ", topic: "saudi-arabia-reference-past-questions", topicTitle: "সৌদি আরব — উৎস-রেফারেন্স ও বিগত প্রশ্ন", domain: "saudi-arabia" };
  return { chapter: "china", chapterTitle: "চীন", topic: "china-reference-early-modern-history", topicTitle: "চীন — প্রারম্ভিক উৎস-রেফারেন্স", domain: "china" };
};
const fact = (page, title, body, status = "source_attributed", confidence = "medium", sources = [], domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, fact_text: body, status, confidence, sources, domain, timeSensitive, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${body}`) });
const note = (page, title, body, confidence = "medium", domain = ctx(page).domain, timeSensitive = false) => ({ source_page: page, title, content: body, status: "source_attributed", confidence, sources: [], domain, timeSensitive, ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${body}`) });
const mcq = (page, number, question, options, correct, source, confidence = "high", domain = ctx(page).domain, timeSensitive = false, sources = []) => ({ source_page: page, number, question, options, correct, source, confidence, status: "source_attributed", sources, domain, timeSensitive, ...ctx(page), canonical_hash: hash(`mcq|${page}|${number}|${question}`) });

const facts = [
  fact(564, "তুরস্ক প্রজাতন্ত্র ও আতাতুর্ক (১৯২৩)", "তুরস্কের সংস্কৃতি ও পর্যটন মন্ত্রণালয়ের জীবনী অনুযায়ী ২৯ অক্টোবর ১৯২৩ তুরস্ক প্রজাতন্ত্র ঘোষণা করা হয় এবং Mustafa Kemal Atatürk প্রথম রাষ্ট্রপতি নির্বাচিত হন।", "verified", "high", [refs.ataturk, refs.turkey], "turkey", true),
  fact(564, "তুরস্কে সুলতানত বিলোপ (১৯২২)", "তুরস্কের সংস্কৃতি ও পর্যটন মন্ত্রণালয়ের জীবনী অনুযায়ী ১ নভেম্বর ১৯২২ সুলতানত বিলোপ করা হয়।", "verified", "high", [refs.ataturk], "turkey", true),
  fact(564, "ট্রয় প্রত্নস্থল — তুরস্ক", "UNESCO অনুযায়ী Troy প্রত্নস্থলটি তুরস্কের Aegean উপকূলের Hisarlık ঢিবিতে অবস্থিত।", "verified", "high", [refs.troy], "turkey", false),
  fact(565, "সংযুক্ত আরব আমিরাতের সাত আমিরাত", "UAE Cabinet অনুযায়ী United Arab Emirates একটি federation; এতে Abu Dhabi, Dubai, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah ও Fujairah—এই সাতটি আমিরাত আছে।", "verified", "high", [refs.uae], "united-arab-emirates", true),
  fact(565, "UAE federation ও Sheikh Zayed (১৯৭১)", "UAE Cabinet অনুযায়ী Sheikh Zayed bin Sultan Al Nahyan ১৯৭১ সালে সাত আমিরাতের Union প্রতিষ্ঠা করেন এবং প্রথম UAE President ছিলেন।", "verified", "high", [refs.uae], "united-arab-emirates", true),
  fact(565, "Palm Jumeirah — Dubai", "U.S. Geological Survey অনুযায়ী Palm Jumeirah Dubai উপকূলে নির্মিত কৃত্রিম দ্বীপগুলোর প্রথমটি।", "verified", "high", [refs.palm], "united-arab-emirates", false),
  fact(566, "United Arab Republic union (১৯৫৮–১৯৬১)", "UN Dag Hammarskjöld Library অনুযায়ী Egypt ও Syria-র union হিসেবে United Arab Republic ফেব্রুয়ারি ১৯৫৮ থেকে সেপ্টেম্বর ১৯৬১ পর্যন্ত ছিল; Syria ১৩ অক্টোবর ১৯৬১ পৃথক UN membership পুনরায় গ্রহণ করে।", "verified", "high", [refs.syriaUn], "syria", true),
  fact(566, "Aleppo — Syria", "Britannica Aleppo-কে northern Syria-র একটি প্রধান শহর হিসেবে বর্ণনা করে।", "verified", "high", [refs.aleppo], "syria", false),
  fact(567, "Saudi Arabia formation (১৯৩২)", "Britannica অনুযায়ী Ibn Saud Najd ও Hejaz একীভূত করে ১৯৩২ সালে Kingdom of Saudi Arabia প্রতিষ্ঠা করেন।", "verified", "high", [refs.ibnSaud], "saudi-arabia", true),
  fact(567, "Saudi riyal", "Saudi Central Bank-এর currency overview-তে Saudi riyal-কে Saudi Arabia-র national currency হিসেবে উল্লেখ করা হয়েছে।", "verified", "high", [refs.saudiRiyal], "saudi-arabia", true),
  fact(568, "People's Republic of China (১৯৪৯) — constitutional reference", "People's Republic of China-এর সংবিধানের প্রস্তাবনায় ১৯৪৯ সালে People's Republic of China প্রতিষ্ঠার বর্ণনা আছে।", "verified", "medium", [refs.chinaConstitution], "china", true),
  fact(568, "May Fourth Movement (১৯১৯)", "UK National Archives অনুযায়ী Versailles-এ Shandong-সংক্রান্ত সিদ্ধান্তের পর ৪ মে ১৯১৯ Beijing-এ student protest শুরু হয়, যা May Fourth Movement নামে পরিচিত।", "verified", "high", [refs.mayFourth], "china", true),
];

const notes = [
  note(564, "তুরস্ক — উসমানীয় ও আতাতুর্ক উৎস-রেফারেন্স", "উৎসে Ottoman/উসমানীয় সাম্রাজ্য, Osman I, ১২৯৯–১৯২২, Mehmed VI, Atatürk, Istanbul, Anatolia, Hagia Sophia ও প্রণালীসমূহের উল্লেখ আছে।\nসতর্কতা | source-এর caliphate-abolition year ১৯২২ হলেও corroborated chronology অনুযায়ী caliphate ১৯২৪ সালে বিলোপ হয়; `Grey Wolf/Gazi`, superlative, religious-building ও compressed geographic wording স্বাধীন fact হিসেবে নেওয়া হয়নি।", "high", "turkey", true),
  note(565, "সংযুক্ত আরব আমিরাত — উৎস-রেফারেন্স", "উৎসে Sheikh Zayed, সাত আমিরাত, Palm Jumeirah, Burj Khalifa এবং Burj Al Arab-এর উল্লেখ আছে।\nসতর্কতা | emirate/governance, commercial, hotel এবং `বর্তমান বিশ্বের সর্বোচ্চ` ভাষা source-attributed; changing superlative ও promotional wording current neutral fact হিসেবে নেওয়া হয়নি।", "medium", "united-arab-emirates", true),
  note(566, "সিরিয়া — উৎস-রেফারেন্স ও সংবেদনশীল বিষয়", "উৎসে Syria, France, United Arab Republic, Aleppo, Golan, Alawite community, Assad family, Free Syrian Army, Ugarit ও Palmyra-এর উল্লেখ আছে।\nসতর্কতা | territorial, religious, political, security, colonial-generalization এবং `oldest/cradle/first` superlative wording source-attributed; Golan সম্পর্কিত দাবি কোনো neutral territorial fact হিসেবে রূপান্তর করা হয়নি।", "high", "syria", true),
  note(567, "সৌদি আরব — উৎস-রেফারেন্স ও ধর্মীয়/প্রাতিষ্ঠানিক সীমা", "উৎসে Ibn Saud, Makkah, Madinah, Riyadh, Saudi riyal, Hijra, Shahada-সহ পতাকা, Sharia ও Majlis ash-Shura-এর উল্লেখ আছে।\nসতর্কতা | sacred-status, prophetic, flag-symbolism, governance, constitution/parliament এবং appointment wording source-attributed; Q03-সহ time-sensitive institutional premise import করা হয়নি।", "high", "saudi-arabia", true),
  note(568, "চীন — রাজনৈতিক ও ঐতিহাসিক উৎস-রেফারেন্স", "উৎসে Han, National People's Congress, People’s Square, Suzhou, Falun Gong, ১৯৪৯, Great Hall of the People, ৪ঠা মে আন্দোলন এবং ১৯২১-এর political-history wording আছে।\nসতর্কতা | legislature, demographic, ideological, institutional size/ranking, officeholder ও low-confidence ১৯১০/May Fourth text source-attributed অথবা withheld; কেবল directly corroborated dated material আলাদা fact হিসেবে রাখা হয়েছে।", "high", "china", true),
];

const mcqs = [
  mcq(565, "01", "বিশ্ববিখ্যাত ট্রয় নগরী কোন দেশে অবস্থিত?", ["গ্রিস", "তুরস্ক", "ফ্রান্স", "ইটালি"], "খ", "DU (printed label partly unclear), ২৪–২৫", "medium", "turkey", false, [refs.troy]),
  mcq(565, "02", "কোনটিকে ইউরেশিয়ান রাষ্ট্র হিসেবে বিবেচনা করা হয়?", ["জাপান", "সৌদি আরব", "তুরস্ক", "ওমান"], "গ", "DU, ০৮–০৯", "high", "turkey", false, [refs.turkey]),
  mcq(565, "03", "ইতিহাস বিখ্যাত ট্রয় নগরী কোথায়?", ["গ্রিস", "ইতালিতে", "তুরস্ক", "স্পেন"], "গ", "10, 19 BCS", "medium", "turkey", false, [refs.troy]),
  mcq(565, "04", "কোন দেশ এশিয়া ও ইউরোপ উভয় মহাদেশে বিভক্ত?", ["ইরান", "পাকিস্তান", "তুরস্ক", "ওমান"], "গ", "Unresolved printed label, ২০০০", "high", "turkey", false, [refs.turkey]),
  mcq(565, "06", "দুই মহাদেশ বিধৃত নগর কোনটি?", ["কায়রো", "কাসা ব্লাঙ্কা", "প্যারিস", "ইস্তাম্বুল"], "ঘ", "Unresolved printed label, ১০", "high", "turkey", false, [refs.turkey]),
  mcq(566, "01", "আলেপ্পো শহরটি কোন দেশে অবস্থিত?", ["ইরান", "ইরাক", "জর্দান", "সিরিয়া"], "ঘ", "46 BCS", "high", "syria", false, [refs.aleppo]),
  mcq(566, "02", "কোথায় ঐতিহাসিক ট্রয় নগর অবস্থিত?", ["ইতালি", "গ্রিস", "তুরস্ক", "ফ্রান্স"], "গ", "45 BCS", "high", "turkey", false, [refs.troy]),
  mcq(566, "03", "আলেপ্পো শহরটি কোথায় অবস্থিত?", ["মিশর", "ইরান", "সিরিয়া", "ইয়েমেন"], "গ", "DU ও ১২–১৩, 36 BCS", "medium", "syria", false, [refs.aleppo]),
  mcq(567, "01", "ইমরুল কায়েস একজন?", ["চিত্রশিল্পী", "বিজ্ঞানী", "কবি", "প্রেসিডেন্ট"], "গ", "DU খ, ১৭–১৮", "high", "saudi-arabia", false, [refs.imru]),
  mcq(567, "02", "যে দেশের জাতীয় পতাকা কখনোই অর্ধনমিত করা হয় না—", ["সৌদি আরব", "আইসল্যান্ড", "সিঙ্গাপুর", "ভ্যাটিকান সিটি"], "ক", "DU খ, ০৪–০৫ / বি বি ১২–১৬", "high", "saudi-arabia", true, [refs.saudiFlag]),
];

const tags = [
  ["west-asia", "West Asia", "domain", "Source-derived West Asia reference."], ["asia", "Asia", "domain", "Source-derived Asia reference."], ["turkey", "Turkey", "domain", "Turkey source material."], ["united-arab-emirates", "United Arab Emirates", "domain", "United Arab Emirates source material."], ["syria", "Syria", "domain", "Syria source material."], ["saudi-arabia", "Saudi Arabia", "domain", "Saudi Arabia source material."], ["china", "China", "domain", "China source material."],
  ["reference-note", "Structured source note", "content_type", "Structured source reference with explicit caveats."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with a printed source key."], ["answer-key", "Answer key", "content_type", "Correct option from the printed key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Directly corroborated by cited evidence."], ["time-sensitive", "Time-sensitive reference", "quality", "Political, institutional, territorial, religious, diplomatic, military, or security source material."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed examination label."], ["bcs", "Bangladesh Civil Service", "exam_source", "Bangladesh Civil Service printed examination label."], ["unresolved-printed-label", "Unresolved printed label", "exam_source", "Partly unclear examination/source label retained without invention."],
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : source.includes("BCS") ? ["Bangladesh Civil Service", null, "competitive", "bcs"] : ["Unresolved printed label", null, "competitive", "unresolved-printed-label"];
const quality = row => row.status === "verified" ? "externally-verified" : "source-attributed";
const region = page => page === 568 ? "asia" : "west-asia";
const entityRef = (kind, h) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(h)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const topics = [
    ["middle-east-country-profiles", "তুরস্ক — উসমানীয় সাম্রাজ্য ও আতাতুর্ক", "turkey-ottoman-ataturk-reference", 564, 9],
    ["middle-east-country-profiles", "তুরস্কের বিগত প্রশ্ন ও সংযুক্ত আরব আমিরাত", "turkey-past-questions-uae-reference", 565, 10],
    ["middle-east-country-profiles", "সিরিয়া — উৎস-রেফারেন্স ও বিগত প্রশ্ন", "syria-reference-past-questions", 566, 11],
    ["middle-east-country-profiles", "সৌদি আরব — উৎস-রেফারেন্স ও বিগত প্রশ্ন", "saudi-arabia-reference-past-questions", 567, 12],
    ["china", "চীন — প্রারম্ভিক উৎস-রেফারেন্স", "china-reference-early-modern-history", 568, 1],
  ];
  const checks = [...facts.map(row => ({ kind: "fact", claim: row.fact_text, ...row })), ...notes.map(row => ({ kind: "note", claim: row.content, ...row })), ...mcqs.map(row => ({ kind: "mcq", claim: `${row.question} — printed answer: ${row.correct}`, ...row }))];
  const audit = {
    batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION,
    source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })),
    generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length,
    verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: 0, source_attributed: checks.filter(row => row.status === "source_attributed").length },
    source_anomalies: [
      "All five pages were rendered at 300 DPI, transcribed with gpt-5-mini, and reviewed through all 35 ordered overlap-safe tiles.",
      "Page 564 source prints 29 October 1923 on visual review; a stale OCR reading of 23 October is excluded. Its caliphate-abolition line says 1922 and is retained only as a conflict-caveated note because authoritative chronology gives 1924.",
      "Page 565 Q05 is withheld because option ক remains low-confidence. Page 566 Q04 and page 567 Q03 are withheld because their premises are time-sensitive political/institutional material.",
      "Page 566 Golan, security, community, and political language; page 567 religious/institutional wording; and page 568 political, demographic, ranking, and low-confidence text remain source-attributed rather than being normalized.",
    ],
    quality_gates: [
      "Exactly physical source pages 564–568 are imported.", "Every imported MCQ has four visually reviewed options and one printed key.",
      "No corrupted, low-confidence-option, time-bound, or institutional-premise MCQ is imported.", "Content tags use only approved categories; countries/regions are category domain.", "Upserts are idempotent by canonical hash and stable derived-record keys.",
    ],
  };
  const chapterSql = `INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,display_order) SELECT b.id,COALESCE((SELECT MAX(c.chapter_number) FROM public.chapters c WHERE c.book_id=b.id),0)+1,'চীন','china','Source-preserved China country profile with explicit review and verification status.',COALESCE((SELECT MAX(c.display_order) FROM public.chapters c WHERE c.book_id=b.id),0)+1 FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug='china');`;
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with explicit review and verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 564: 507, 565: 508, 566: 509, 567: 510, 568: 511 };
  const pageSql = pages.map(page => { const c = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: `${workDir}/visual_review_564_568.md`, external_verification_report: `${workDir}/external_verification.md`, classification_report: `${workDir}/classification_decisions.md` }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},${q([565, 566, 567].includes(page.source_page) ? "mcq" : "educational")}::page_kind,${q(page.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered source-tile review, withholding rules, and explicit verification status.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.status, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct corroboration is recorded in the batch verification ledger.' ELSE 'Source-attributed material retained after ordered image review; it is not silently updated as a current assertion.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name, institution, examType, normalizedName] = exam(row.source); const keys = ["ক", "খ", "গ", "ঘ"]; const options = row.options.map((option, index) => `INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index + 1},${keys[index] === row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); const explanation = "Printed answer key retained after visual review; any historical, geographic, religious, institutional, or political context is source-attributed and linked in the batch verification ledger."; return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(examType)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalizedName)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalizedName)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},${q(explanation)},${row.source_page},'বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${options} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalizedName)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const factTags = facts.map(row => [region(row.source_page), row.domain, quality(row), ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0564-0568-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const noteTags = notes.map(row => [region(row.source_page), row.domain, "reference-note", "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0564-0568-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const mcqTags = mcqs.map(row => [region(row.source_page), row.domain, "past-exam-mcq", "answer-key", exam(row.source)[3], "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])].map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${row.source_page},${q(row.confidence)}::confidence_level,'batch-0564-0568-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(row.canonical_hash)} WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row => `(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${factTags}\n${noteTags}\n${mcqTags}`;
  const verificationSql = checks.map(row => `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${entityRef(row.kind, row.canonical_hash)},${q(row.claim)},NULL,${q(row.status)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(row.status === "verified" ? "Direct corroboration is listed in the batch verification ledger." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${entityRef(row.kind, row.canonical_hash)} AND v.claim_text=${q(row.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0564-0568:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 564 AND 568 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0564-0568:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0564-0568:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 564 AND 568 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0564-0568:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0564-0568:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page IN (565,566,567) AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0564-0568:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 564 AND 568 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 564 AND 568 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page IN (565,566,567) AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0564_0568.mjs. Source pages 564–568 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page => page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { sql, audit } = await buildBatch();
  const counts = { batch_pages: BATCH_PAGES, review_tiles: 35, eligible_mcqs: mcqs.length, eligible_mcq_options: mcqs.length * 4, withheld_mcqs: 3, fact_candidates: facts.length, note_candidates: notes.length, verification_statuses: audit.verification_counts };
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, "validated_import.sql"), sql);
  await fs.writeFile(path.join(outputDir, "batch_audit.json"), JSON.stringify(audit, null, 2));
  await fs.writeFile(path.join(outputDir, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql }));
  await fs.writeFile(path.join(workDir, "import_input_counts.json"), JSON.stringify(counts, null, 2));
  console.log(JSON.stringify({ outputDir, ...audit, counts }, null, 2));
}
