import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const workDir="/home/ubuntu/dontonyo-work/batch-0539-0543";
const outputDir=path.join(root,"supabase","batch-0539-0543");
export const BATCH_PAGES=[539,540,541,542,543];
export const PIPELINE_VERSION="vision-quality-gated-batch-0539-0543-v1";
const BOOK_TITLE="Jubayer's GK";
const q=v=>`'${String(v??"").replaceAll("'","''")}'`;
const json=v=>`${q(JSON.stringify(v))}::jsonb`;
const hash=v=>crypto.createHash("sha256").update(v,"utf8").digest("hex");
const values=rows=>rows.map(r=>`(${r.map(q).join(",")})`).join(",\n");
const files=BATCH_PAGES.map(p=>path.join(workDir,"pages",`page_${String(p).padStart(4,"0")}.json`));
const refs={bhutan:"https://climateactiontracker.org/countries/bhutan/",ceylon:"https://www.britannica.com/topic/history-of-Sri-Lanka/Independent-Ceylon-1948-71",sirimavo:"https://www.britannica.com/biography/Sirimavo-Bandaranaike",maldives:"https://sos.noaa.gov/education/phenomenon-based-learning/underwater-cabinet-meeting/"};
const ctx=p=>({chapter:"south-asia-country-profiles",chapterTitle:"দক্ষিণ এশিয়ার দেশসমূহ",topic:p===539?"afghanistan-reference":p===540?"bhutan-reference":p===541?"nepal-reference":p===542?"sri-lanka-reference":"maldives-reference",topicTitle:p===539?"আফগানিস্তান":p===540?"ভুটান":p===541?"নেপাল":p===542?"শ্রীলঙ্কা":"মালদ্বীপ"});
const fact=(p,title,text,status="source_attributed",confidence="medium",sources=[])=>({source_page:p,title,fact_text:text,status,confidence,sources,...ctx(p),canonical_hash:hash(`fact|${p}|${title}|${text}`)});
const note=(p,title,content,confidence="medium")=>({source_page:p,title,content,status:"source_attributed",confidence,sources:[],...ctx(p),canonical_hash:hash(`note|${p}|${title}|${content}`)});
const mcq=(p,n,question,options,correct,source,confidence="high")=>({source_page:p,number:n,question,options,correct,source,confidence,status:"source_attributed",sources:[],...ctx(p),canonical_hash:hash(`mcq|${p}|${n}|${question}`)});

const facts=[
 fact(539,"আফগানিস্তানের স্বাধীনতা (source statement)","আফগানিস্তান ১৯১৯ সালে ব্রিটেনের কাছ থেকে স্বাধীনতা লাভ করে।","source_attributed","high"),fact(539,"আফগান রাজতন্ত্রের অবসান (source statement)","আফগানিস্তানে রাজতন্ত্রের অবসান ঘটে ১৯৭৩ সালে।","source_attributed","high"),fact(539,"আফগানিস্তানের শেষ রাজা (source statement)","আফগানিস্তানের শেষ রাজা ছিলেন জহির শাহ।","source_attributed","high"),fact(539,"দাউদ খান (source statement)","উৎসে মোহাম্মদ দাউদ খানকে আফগানিস্তানের প্রথম রাষ্ট্রপতি এবং প্রজাতন্ত্র ঘোষণাকারী বলা হয়েছে।","source_attributed","high"),fact(539,"আফগান প্রদেশ ও সীমান্ত (source statement)","উৎসে আফগানিস্তানে ৩৪টি প্রদেশ এবং ছয় দেশের সঙ্গে সীমান্ত বলা হয়েছে।","source_attributed","high"),fact(539,"বাগরাম কারাগার (source statement)","বাগরাম কারাগার আফগানিস্তানের কাবুলে অবস্থিত বলে উৎসে বলা হয়েছে।","source_attributed","medium"),fact(539,"পশতুন সংখ্যাগরিষ্ঠতা (source statement)","উৎসে পশতুনকে আফগানিস্তানের সংখ্যাগরিষ্ঠ জাতিগোষ্ঠী বলা হয়েছে।","source_attributed","high"),fact(539,"Operation Enduring Freedom (source statement)","Operation Enduring Freedom আফগানিস্তানে পরিচালিত মার্কিন অভিযানের সাংকেতিক নাম বলে উৎসে বলা হয়েছে।","source_attributed","high"),
 fact(540,"ভুটানের শাসনতান্ত্রিক রাজতন্ত্র (source statement)","উৎসে ভুটানকে দক্ষিণ এশিয়ার শাসনতান্ত্রিক রাজতান্ত্রিক দেশ বলা হয়েছে।","source_attributed","high"),fact(540,"টাইগার্স নেস্ট (source statement)","টাইগার্স নেস্ট বৌদ্ধ আশ্রম ভুটানে অবস্থিত।","source_attributed","high"),fact(540,"ভুটানের কার্বন অবস্থা", "ভুটান কার্বন-নেগেটিভ/কার্বন প্রভাবমুক্ত রাষ্ট্র হিসেবে পরিচিত বলে উৎসে বলা হয়েছে।","verified","high",[refs.bhutan]),fact(540,"বজ্র ড্রাগনের দেশ (source statement)","ভুটান বজ্র ড্রাগনের দেশ নামে পরিচিত।","source_attributed","high"),fact(540,"ভুটানের মুদ্রা (source-printed spelling)","উৎসে ভুটানের মুদ্রার নাম ঙুলট্রাম (Ngultrum) লেখা হয়েছে।","source_attributed","medium"),fact(540,"ভুটানের প্রথম পার্লামেন্ট নির্বাচন (source statement)","ভুটানে প্রথম পার্লামেন্ট নির্বাচন ২০০৮ সালে অনুষ্ঠিত হয় বলে উৎসে বলা হয়েছে।","source_attributed","high"),fact(540,"Gross National Happiness (source statement)","ভুটান মোট জাতীয় সুখকে অর্থনৈতিক উন্নয়নের মানদণ্ড হিসেবে গ্রহণ করেছে বলে উৎসে বলা হয়েছে।","source_attributed","high"),
 fact(541,"নেপালের ভৌগোলিক অবস্থান (source statement)","নেপাল হিমালয় অধ্যুষিত দক্ষিণ এশীয় দেশ; উত্তরে চীন এবং দক্ষিণ, পূর্ব ও পশ্চিমে ভারতের সীমান্ত।","source_attributed","high"),fact(541,"নেপালের রাজতন্ত্রের অবসান (source statement)","উৎসে ২০০৮ সালে ২৪০ বছরের নেপালি রাজতন্ত্রের অবসান ও সংসদীয় গণতন্ত্র প্রতিষ্ঠার বর্ণনা রয়েছে।","source_attributed","high"),fact(541,"নেপালের শেষ রাজা (source statement)","নেপালের সর্বশেষ রাজা ছিলেন জ্ঞানেন্দ্র বীর বিক্রম শাহ দেব।","source_attributed","high"),fact(541,"নেপালের রাষ্ট্রপতির বাসভবন (source statement)","নেপালের রাষ্ট্রপতির সরকারি বাসভবনের নাম শীতল নিবাস।","source_attributed","high"),fact(541,"নেপালি সৈন্যদের নাম (source statement)","নেপালের সৈন্যদের গুর্খা বলা হয়।","source_attributed","high"),
 fact(542,"সিলনের স্বাধীনতা", "সিলন ১৯৪৮ সালে ব্রিটেনের কাছ থেকে স্বাধীনতা লাভ করে।","verified","high",[refs.ceylon]),fact(542,"শ্রীলঙ্কার প্রথম নারী প্রধানমন্ত্রী", "সিরিমাভো আর. ডি. বন্দরনায়েকে ১৯৬০ সালে বিশ্বের প্রথম নারী প্রধানমন্ত্রী হন।","verified","high",[refs.sirimavo]),fact(542,"শ্রীলঙ্কার প্রথম প্রধানমন্ত্রী (source statement)","উৎসে ডন স্টিফেন সেনানায়েকেকে শ্রীলঙ্কার জনক ও প্রথম প্রধানমন্ত্রী বলা হয়েছে।","source_attributed","medium"),fact(542,"ক্যান্ডি (source statement)","ক্যান্ডিকে শ্রীলঙ্কার সাংস্কৃতিক রাজধানী বলা হয়েছে।","source_attributed","high"),fact(542,"Elephant Pass (source statement)","Elephant Pass শ্রীলঙ্কার কৌশলগত গুরুত্বপূর্ণ স্থান বলে উৎসে বলা হয়েছে।","source_attributed","medium"),fact(542,"শ্রীলঙ্কার গৃহযুদ্ধ (source statement)","উৎসে শ্রীলঙ্কায় গৃহযুদ্ধের শুরু ১৯৮৩ বলা হয়েছে।","source_attributed","medium"),
 fact(543,"মালদ্বীপের ভূগোল (source statement)","মালদ্বীপ ভারত মহাসাগরের একটি দ্বীপ রাষ্ট্র এবং ১,২০০-এর বেশি ছোট দ্বীপ নিয়ে গঠিত বলে উৎসে বলা হয়েছে।","source_attributed","medium"),fact(543,"মালদ্বীপের আন্ডারওয়াটার মন্ত্রিসভা", "মোহাম্মদ নাশিদ জলবায়ু-ঝুঁকি বিষয়ে সচেতনতা বাড়াতে পানির নিচে মন্ত্রিসভা বৈঠক করেন।","verified","high",[refs.maldives]),fact(543,"মালদ্বীপের আয়তন (source statement)","উৎসে মালদ্বীপের আয়তন ২৯৮ বর্গ কিলোমিটার লেখা হয়েছে।","source_attributed","medium"),fact(543,"মালদ্বীপের প্রতিরক্ষা বাহিনী (source statement)","উৎসে Maldives National Defence Force-কে মালদ্বীপের নিরাপত্তা ও সার্বভৌমত্ব রক্ষাকারী বাহিনী বলা হয়েছে।","source_attributed","medium"),fact(543,"মালদ্বীপের বাংলাদেশ দূতাবাস (source statement)","উৎসে মালদ্বীপ ২০০৮ সালে বাংলাদেশে দূতাবাস চালু করে বলে বলা হয়েছে।","source_attributed","high")
];
const notes=[
 note(539,"আফগানিস্তান — উৎস সারাংশ", "উৎসে ১৯১৯ স্বাধীনতা, ১৯৭৩ রাজতন্ত্রের অবসান, জহির শাহ, ১৯৭৯ সোভিয়েত দখল, ১৯৮৯ প্রত্যাহার এবং কয়েকটি শহরের তালিকা রয়েছে।\nসতর্কতা | প্রথম অনুচ্ছেদের 'প্রজাতন্ত্র'–পরবর্তী ক্রিয়াপদ এবং কয়েকটি proper name (বাজার/সুখা কণা/তোরেভারা) ঝাপসা; সেগুলো স্বাধীন fact হিসেবে আমদানি করা হয়নি।", "medium"),
 note(540,"ভুটান — উৎস সারাংশ", "উৎসে Tiger’s Nest, বজ্র ড্রাগনের উপনাম, ঙুলট্রাম মুদ্রা, ২০০৮ নির্বাচন ও GNH বিবৃতি রয়েছে।\nসতর্কতা | কার্বন-নেগেটিভ MCQ Q1-এর মুদ্রিত key 'গ, ঘ'; single-correct contract মেনে সেটি MCQ হিসেবে বাদ দেওয়া হয়েছে। রাজনৈতিক দল-সংক্রান্ত বিবৃতি time-sensitive source material।", "medium"),
 note(541,"নেপাল — উৎস রাজনৈতিক সময়রেখা", "উৎসে ১৯৯৬ থেকে মাওবাদী আন্দোলন, ২০০৬ শান্তি চুক্তি/পার্লামেন্ট পুনরুদ্ধার, ২০০৭ আইন এবং ২০০৮ রাজতন্ত্র অবসান বর্ণিত।\nসতর্কতা | অফিসধারী ও সাংবিধানিক ভাষা source-era এবং time-sensitive; বানান-অস্পষ্ট proper noun গুলো নীরবে ঠিক করা হয়নি।", "medium"),
 note(542,"শ্রীলঙ্কা — উৎস সারাংশ", "উৎসে Ceylon নাম, ১৯৪৮ স্বাধীনতা, Sirimavo Bandaranaike, ১৯৭২ নাম পরিবর্তন, Elephant Pass, Palk Strait, ১৯৮৩ গৃহযুদ্ধ এবং কয়েকটি সংস্কৃতি/ধর্মীয় স্থান দেওয়া হয়েছে।\nসতর্কতা | ঝাপসা geographical ও religious reference lines উৎস-ট্রান্সক্রিপ্টে রয়ে গেছে; কেবল পাঠযোগ্য অংশ structuring করা হয়েছে।", "medium"),
 note(543,"মালদ্বীপ — উৎস সারাংশ ও সংশোধনী", "উৎসে ১,২০০-এর বেশি দ্বীপ, ২০০৯ underwater cabinet meeting, Maldives National University, Maumoon Abdul Gayoom ও Mohamed Nasheed প্যানেল, MNDF, এবং বাংলাদেশে ২০০৮ দূতাবাসের কথা রয়েছে।\nসংশোধনী-প্যানেল | দৃশ্যমান অংশে পুরনো বইয়ের 'বাংলাদেশে দূতাবাস নেই' বক্তব্য ভুল বলা হয়েছে এবং ২০০৮ চালুর উল্লেখ আছে। শেষ অংশ আংশিক কাটা/ঝাপসা; পুনর্গঠন করা হয়নি।", "low")
];
const mcqs=[
 mcq(539,"01","কতটি দেশের সাথে আফগানিস্তানের সীমান্ত আছে?",["৪টি","৫টি","৭টি","৬টি"],"ঘ","DU ঘ ১২-১৩","low"),mcq(539,"02","আফগানিস্তানের শেষ বাদশাহ ছিলেন-",["দাউদ খাঁ","জহির শাহ","নাদির শাহ","নজীবুল্লাহ"],"খ","31 BCS"),mcq(539,"03","আফগানিস্তানের কোন জাতিগত সদস্যরা সংখ্যাগরিষ্ঠ?",["তাজিক","উজবেক","কুর্দি","পশতুন"],"ঘ","জাতীয় আন্তর্জাতিক সম্পর্ক ০৯-১০"),
 mcq(540,"02","এশিয়ার 'বজ্রপালের ভূমি' কোন?",["নেপাল","ভুটান","থাইল্যান্ড","মায়ানমার"],"খ","DU ১৭-১৮","medium"),mcq(540,"03","ভুটানের জাতীয় খেলা-",["ফুটবল","ক্রিকেট","আর্চারি","টেনিস"],"গ","DU ০৮-০৯"),mcq(540,"04","ভুটানের জাতীয় ফুল কী?",["নীল লতাপি","লাল গোলাপ","পদ্ম","লিলি"],"ক","DU ৯৩-৯৪"),mcq(540,"05","কোন দেশ প্রথম জনসমষ্টিকে ধূমপান নিরোধ করে?",["ত্রিনিদাদ","ভুটান","সুইডেন","কানাডা"],"খ","DU ৯৪-৯৫","medium"),mcq(540,"06","ভুটানে জনগণ কবে ভোটাধিকার প্রয়োগ করেন?",["মে ২০০৮","জুন ২০০৬","এপ্রিল ২০০৭","জানুয়ারি ২০০৮"],"ক","DU ০৭-০৮","low"),
 mcq(541,"01","নেপালের সর্বশেষ রাজা-",["ধীরেন্দ্র","জ্ঞানেন্দ্র","বীরেন্দ্র","মহেন্দ্র"],"খ","DU ১০-১১, 35 BCS"),mcq(541,"02","বিশ্বের সর্বকনিষ্ঠ গণতান্ত্রিক রাষ্ট্র-",["ভূটান","নেপাল","পূর্ব তিমুর","তিব্বত"],"খ","DU ০৮-০৯"),mcq(541,"03","নেপালের রাজতন্ত্রের বিলুপ্ত ঘটে কোন সালে?",["২০০৫","২০০৬","২০০৭","২০০৮"],"ঘ","রাবি দর্শন ০৮-০৯"),mcq(541,"04","২০০৭ সালে নেপালে কত বছরের পুরাতন রাজতন্ত্র বিলোপ ঘটে?",["২৫৫ বছর","২৪০ বছর","২৪৬ বছর","২৩৮ বছর"],"খ","মা. সহ. শিক্ষক ০৮"),mcq(541,"05","নেপালে রাজতন্ত্র বিলুপ্ত হয়ে সংসদীয় গণতন্ত্র প্রতিষ্ঠিত হয় কোন বছরে?",["১৯৯০","২০০৮","২০০৭","১৯৯৯"],"খ","জাহিদ সরকার ও রাজনীতি ০৯-১০"),
 mcq(542,"01","'Elephant Pass' অবস্থিত?",["থাইল্যান্ড","দ. আফ্রিকা","শ্রীলঙ্কা","মালয়েশিয়া"],"গ","45 BCS"),mcq(542,"02","১৯৬০ সালে কোন দেশ বিশ্বের প্রথম মহিলা প্রধানমন্ত্রী নির্বাচিত করে?",["ভারত","ইস্রাইল","আয়ারল্যান্ড","শ্রীলঙ্কা"],"ঘ","DU ৯৬-৯৭; ১৩-১৪","medium"),mcq(542,"03","শ্রীলঙ্কার সরকার ও তামিল বিরোধীদের মধ্যে সংঘাতে মধ্যস্থতা করে-",["সুইডেন","ফ্রান্স","জার্মানি","নরওয়ে"],"ঘ","DU ৯৫-০৬; ০২-০৩; ০৩-০৪","medium")
];
const tags=[["south-asia","South Asia","domain","Source-derived South Asian country reference."],["afghanistan","Afghanistan","domain","Afghanistan source material."],["bhutan","Bhutan","domain","Bhutan source material."],["nepal","Nepal","domain","Nepal source material."],["sri-lanka","Sri Lanka","domain","Sri Lanka source material."],["maldives","Maldives","domain","Maldives source material."],["reference-table","Reference source","content_type","Structured source reference or correction note."],["past-exam-mcq","Past-exam MCQ","content_type","MCQ with a printed examination label and answer key."],["answer-key","Answer key","content_type","Correct option from the printed answer key."],["source-attributed","Source-attributed","quality","Source-preserved material without direct corroboration in this batch."],["externally-verified","Externally verified","quality","Claim directly corroborated by cited evidence."],["time-sensitive","Time-sensitive reference","quality","Political, territorial, public-office, diplomatic, demographic, or policy reference."],["low-confidence","Low-confidence source reading","quality","Source scan is incomplete or uncertain."],["dhaka-university","University of Dhaka","exam_source","University of Dhaka printed exam label."],["bcs","BCS","exam_source","Bangladesh Civil Service printed exam label."],["other-recruitment","Other examination","exam_source","Other university or recruitment label."]];
const exam=s=>s.includes("DU")?["University of Dhaka","University of Dhaka","admission","dhaka-university"]:s.includes("BCS")?["Bangladesh Civil Service",null,"competitive","bcs"]:["Other university and recruitment examination",null,"competitive","other-recruitment"];
const quality=r=>r.status==="verified"?"externally-verified":r.status==="conflicting"?"conflicting":"source-attributed";
const rid=(kind,key)=>`(SELECT id FROM public.${kind==="fact"?"gk_facts":kind==="note"?"gk_notes":"gk_mcqs"} WHERE canonical_hash=${q(key)} LIMIT 1)`;

export async function buildBatch(){const pages=await Promise.all(files.map(f=>fs.readFile(f,"utf8").then(JSON.parse)));const chapters=[[65,"দক্ষিণ এশিয়ার দেশসমূহ","south-asia-country-profiles","Source-preserved Afghanistan, Bhutan, Nepal, Sri Lanka, and Maldives material.",539]];const topics=[["south-asia-country-profiles","আফগানিস্তান","afghanistan-reference",539,1],["south-asia-country-profiles","ভুটান","bhutan-reference",540,2],["south-asia-country-profiles","নেপাল","nepal-reference",541,3],["south-asia-country-profiles","শ্রীলঙ্কা","sri-lanka-reference",542,4],["south-asia-country-profiles","মালদ্বীপ","maldives-reference",543,5]];const checks=[...facts.map(x=>({kind:"fact",claim:x.fact_text,...x})),...notes.map(x=>({kind:"note",claim:x.content,...x})),...mcqs.map(x=>({kind:"mcq",claim:`${x.question} — printed answer: ${x.correct}`,...x}))];const audit={batch_pages:BATCH_PAGES,pipeline_version:PIPELINE_VERSION,source_pages:pages.map(p=>({page:p.source_page,review_status:p.review.review_status,image_sha256:p.source_image_sha256,overall_confidence:p.review.overall_confidence})),generated_facts:facts.length,generated_notes:notes.length,generated_mcqs:mcqs.length,generated_options:mcqs.length*4,generated_flashcards:facts.length+notes.length+mcqs.length,verification_counts:{verified:checks.filter(x=>x.status==="verified").length,conflicting:0,source_attributed:checks.filter(x=>x.status==="source_attributed").length},source_anomalies:["Physical PDF pages 539–543 retain printed footers 482–486.","Page 540 was recovered by a targeted retry after a transient 502 gateway failure; its recovered artifact was merged then visually reviewed.","Bhutan page 540 MCQ Q1 is withheld because its printed answer key gives two alternatives (গ, ঘ).","Blurred Afghanistan, Sri Lanka, and Maldives spans are retained in source transcripts and not reconstructed as independent facts.","All political, constitutional, diplomatic, security, and office-holder claims remain status-marked source material unless directly corroborated."],quality_gates:["Exactly physical pages 539–543 are imported.","All 25 ordered visual-review tiles were reviewed.","Every imported MCQ has four reviewed source options and one printed correct key.","Upserts are idempotent by canonical hash and stable derived-record keys."]};
const chapterSql=`INSERT INTO public.chapters (book_id,chapter_number,title,slug,description,source_page,display_order) SELECT b.id,x.n::integer,x.title,x.slug,x.description,x.page::integer,x.n::integer FROM (VALUES ${values(chapters)}) x(n,title,slug,description,page) JOIN public.books b ON b.title=${q(BOOK_TITLE)} WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.book_id=b.id AND c.slug=x.slug);`;
const topicSql=`INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved material with explicit verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
const printed={539:482,540:483,541:484,542:485,543:486};const pageSql=pages.map(p=>{const c=ctx(p.source_page),meta={source_image_sha256:p.source_image_sha256,extraction_model:p.model,review_status:p.review.review_status,corrections:p.review.corrections,unresolved_spans:p.review.unresolved_spans,physical_source_page:p.source_page,printed_book_page:printed[p.source_page],recovery:p.source_page===540?"Recovered after primary-run transient 502 and merged into primary workspace.":null,visual_review_report:"/home/ubuntu/dontonyo/reports/batch-0539-0543_visual_review.md",external_verification_report:"/home/ubuntu/dontonyo/reports/batch-0539-0543_external_verification.md"};return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${p.source_page},${q([539,540,541,542].includes(p.source_page)?"mcq":"educational")}::page_kind,${q(p.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(p.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(p.model)},'Quality-gated extraction with ordered tile review, recovery provenance, and explicit verification statuses.',${json(meta)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${p.source_page});`;}).join("\n");
const factSql=`WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.fact_text,x.status,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,CASE d.status WHEN 'verified' THEN 'Direct external corroboration is recorded in the batch verification ledger.' ELSE 'Source-attributed material is retained with image-grounded review and no silent factual update.' END,d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
const noteSql=`WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(x=>[x.source_page,x.chapter,x.topic,x.title,x.content,x.confidence,x.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
const mcqSql=mcqs.map(x=>{const [name,institution,type,norm]=exam(x.source),keys=["ক","খ","গ","ঘ"],opts=x.options.map((o,i)=>`INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[i])},${q(o)},${i+1},${keys[i]===x.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[i])});`).join("\n");return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(type)},${q(`Normalized from printed source label on page ${x.source_page}.`)},${q(norm)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(norm)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(x.question)},${q(x.correct)},'Printed answer key retained as source-attributed material; all options and the examination label were visually validated.',${x.source_page},'বিগত বছরের প্রশ্ন',${q(x.number)},3,${q(x.confidence)}::confidence_level,${q(x.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(x.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(x.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${opts} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(norm)} LIMIT 1),NULL,${q(x.source)},${q(x.source)},${x.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(x.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(x.source)} AND s.source_page=${x.source_page});`;}).join("\n");
const tagSql=`INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(x=>`(${x.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(x=>["south-asia",x.topic.replace("-reference",""),quality(x),"time-sensitive",...(x.confidence==="low"?["low-confidence"]:[])].map(t=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'fact',f.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0539-0543-quality-pipeline' FROM public.content_tags t JOIN public.gk_facts f ON f.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(t)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${notes.map(x=>["south-asia",x.topic.replace("-reference",""),"reference-table","source-attributed","time-sensitive"].map(t=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'note',n.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0539-0543-quality-pipeline' FROM public.content_tags t JOIN public.gk_notes n ON n.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(t)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}\n${mcqs.map(x=>["south-asia",x.topic.replace("-reference",""),"past-exam-mcq","answer-key",exam(x.source)[3],"source-attributed",...(x.confidence==="low"?["low-confidence"]:[])].map(t=>`INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,'mcq',m.id,${x.source_page},${q(x.confidence)}::confidence_level,'batch-0539-0543-quality-pipeline' FROM public.content_tags t JOIN public.gk_mcqs m ON m.canonical_hash=${q(x.canonical_hash)} WHERE t.slug=${q(t)} ON CONFLICT DO NOTHING;`).join("\n")).join("\n")}`;
const verificationSql=checks.map(x=>`INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${x.source_page},${q(x.kind)},${rid(x.kind,x.canonical_hash)},${q(x.claim)},NULL,${q(x.status)},${q(x.confidence)}::confidence_level,${json(x.sources)},${q(x.status==="verified"?"Direct external corroboration is listed in the batch verification ledger.":"Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(x.kind)} AND v.entity_id=${rid(x.kind,x.canonical_hash)} AND v.claim_text=${q(x.claim)});`).join("\n");
const derivedSql=`INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0539-0543:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 539 AND 543 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0539-0543:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0539-0543:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 539 AND 543 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0539-0543:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0539-0543:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page BETWEEN 539 AND 542 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0539-0543:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked South Asia GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 539 AND 543 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 539 AND 543 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page BETWEEN 539 AND 542 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
const sql=`-- Generated by prepare_validated_batch_0539_0543.mjs. Source pages 539–543 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(p=>p.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${chapterSql}\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;return{sql,audit};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const{sql,audit}=await buildBatch();await fs.mkdir(outputDir,{recursive:true});await fs.writeFile(path.join(outputDir,"validated_import.sql"),sql);await fs.writeFile(path.join(outputDir,"batch_audit.json"),JSON.stringify(audit,null,2));await fs.writeFile(path.join(outputDir,"execute_sql_request.json"),JSON.stringify({project_id:"rennotctgrxvbpghbimx",query:sql}));console.log(JSON.stringify({outputDir,...audit},null,2));}
