import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workDir = "/home/ubuntu/dontonyo-work/batch-0569-0573";
const outputDir = path.join(root, "supabase", "batch-0569-0573");
export const BATCH_PAGES = [569, 570, 571, 572, 573];
export const PIPELINE_VERSION = "vision-quality-gated-batch-0569-0573-v1";
const BOOK_TITLE = "Jubayer's GK";
const q = value => `'${String(value ?? "").replaceAll("'", "''")}'`;
const json = value => `${q(JSON.stringify(value))}::jsonb`;
const hash = value => crypto.createHash("sha256").update(value, "utf8").digest("hex");
const values = rows => rows.map(row => `(${row.map(q).join(",")})`).join(",\n");
const files = BATCH_PAGES.map(page => path.join(workDir, "pages", `page_${String(page).padStart(4, "0")}.json`));

const refs = {
  china1949: "https://history.state.gov/milestones/1977-1980/china-policy",
  pingPong: "https://diplomacy.state.gov/ping-pong-diplomacy-historic-1971-u-s-table-tennis-trip-to-china/",
  resolution2758: "https://digitallibrary.un.org/record/192054?ln=en",
  relations1979: "https://history.state.gov/historicaldocuments/frus1977-80v01/d104",
  bri: "https://openknowledge.worldbank.org/entities/publication/16252360-1cf1-546e-9978-9e57b5f32cec",
  nobel: "https://www.nobelprize.org/prizes/peace/1989/summary/",
  macao: "https://www.icm.gov.mo/handovermuseum/en/exhibition/",
  hongKong: "https://www.britannica.com/event/handover-of-Hong-Kong",
  wall: "https://whc.unesco.org/en/list/438/",
  confucius: "https://www.britannica.com/biography/Confucius",
  culturalRevolution: "https://www.britannica.com/event/Cultural-Revolution",
  sun: "https://www.britannica.com/biography/Sun-Yat-sen",
};

const ctx = page => {
  const topics = {
    569: ["china-civil-war-xinjiang-diplomacy-reference", "চীন — গৃহযুদ্ধ, জিনজিয়াং ও কূটনীতি"],
    570: ["china-tiananmen-tibet-macau-reference", "চীন — তিয়েনআনমেন, তিব্বত ও ম্যাকাও"],
    571: ["china-hong-kong-taiwan-reference", "চীন — হংকং ও তাইওয়ান উৎস-রেফারেন্স"],
    572: ["china-great-wall-biographies-reference", "চীন — মহানপ্রাচীর ও ব্যক্তিত্ব"],
    573: ["china-past-questions-569-573", "চীন — বিগত বছরের প্রশ্ন"],
  };
  const [topic, topicTitle] = topics[page];
  return { chapter: "china", chapterTitle: "চীন", topic, topicTitle, domain: "china" };
};
const fact = (page, title, text, status = "source_attributed", confidence = "medium", sources = [], timeSensitive = false) => ({ source_page: page, title, fact_text: text, status, confidence, sources, timeSensitive, ...ctx(page), canonical_hash: hash(`fact|${page}|${title}|${text}`) });
const note = (page, title, content, confidence = "high", timeSensitive = true) => ({ source_page: page, title, content, confidence, timeSensitive, status: "source_attributed", sources: [], ...ctx(page), canonical_hash: hash(`note|${page}|${title}|${content}`) });
const mcq = (number, question, options, correct, source, confidence = "high", sources = [], timeSensitive = false) => ({ source_page: 573, number, question, options, correct, source, confidence, sources, timeSensitive, status: "source_attributed", ...ctx(573), canonical_hash: hash(`mcq|573|${number}|${question}`) });

const facts = [
  fact(569, "চীনা গৃহযুদ্ধ ও গণচীন (১৯৪৯)", "U.S. Office of the Historian অনুযায়ী ১৯৪৯ সালে Chinese Communist Party forces Chinese Civil War-এ Republic of China সরকারকে পরাজিত করে এবং People's Republic of China প্রতিষ্ঠা করে।", "verified", "high", [refs.china1949], true),
  fact(569, "Ping-Pong Diplomacy (১৯৭১)", "U.S. Department of State অনুযায়ী ১৯৭১ সালের এপ্রিল মাসে U.S. table-tennis team China সফর করে; এই সফর পরবর্তী U.S.–China official diplomatic relations প্রতিষ্ঠার ভিত্তি গঠনে সহায়তা করে।", "verified", "high", [refs.pingPong], true),
  fact(569, "U.S.–PRC formal diplomatic relations (১৯৭৯)", "U.S.–PRC joint communiqué অনুযায়ী United States ও People's Republic of China ১ জানুয়ারি ১৯৭৯ থেকে diplomatic relations প্রতিষ্ঠায় সম্মত হয়।", "verified", "high", [refs.relations1979], true),
  fact(569, "BRI proposal and connectivity (২০১৩)", "World Bank-এর BRI analysis অনুযায়ী China ২০১৩ সালে Belt and Road Initiative প্রস্তাব করে; উদ্যোগটির উদ্দেশ্য অবকাঠামো বিনিয়োগ ও regional cooperation-এর মাধ্যমে connectivity উন্নত করা।", "verified", "high", [refs.bri], true),
  fact(570, "১৪তম দালাই লামার Nobel Peace Prize (১৯৮৯)", "Nobel Prize অনুযায়ী The 14th Dalai Lama (Tenzin Gyatso) ১৯৮৯ সালের Nobel Peace Prize লাভ করেন।", "verified", "high", [refs.nobel], true),
  fact(570, "ম্যাকাও হস্তান্তর (২০ ডিসেম্বর ১৯৯৯)", "Macao Cultural Affairs Bureau-এর handover record অনুযায়ী Chinese ও Portuguese সরকার ২০ ডিসেম্বর ১৯৯৯ Macao-র sovereignty transfer সম্পন্ন করে।", "verified", "high", [refs.macao], true),
  fact(571, "Hong Kong handover (১ জুলাই ১৯৯৭)", "Britannica অনুযায়ী ১ জুলাই ১৯৯৭ Hong Kong British rule থেকে Chinese sovereignty-তে handover হয়।", "verified", "high", [refs.hongKong], true),
  fact(571, "Hong Kong treaty and lease context", "Britannica অনুযায়ী First Opium War-এর পর ১৮৪২ সালের Treaty of Nanjing-এ Britain Hong Kong Island পায়; ১৮৯৮ সালে New Territories ৯৯ বছরের জন্য lease হয়।", "verified", "high", [refs.hongKong], true),
  fact(572, "চীনের মহানপ্রাচীর — Ming ও উত্তর প্রতিরক্ষা", "UNESCO অনুযায়ী Great Wall-এর নির্মাণ Ming dynasty পর্যন্ত চলতে থাকে; এটি উত্তর দিকের invasion প্রতিরোধে defensive system হিসেবে গড়ে ওঠে এবং সম্পূর্ণ route ২০,০০০ কিলোমিটারের বেশি।", "verified", "high", [refs.wall], false),
  fact(572, "কনফুসিয়াস — দার্শনিক ও Confucianism", "Britannica অনুযায়ী Confucius ছিলেন Chinese philosopher; তাঁর ethical, moral ও social standards Confucianism-এর ভিত্তি গড়ে তোলে।", "verified", "high", [refs.confucius], false),
  fact(572, "Cultural Revolution (১৯৬৬)", "Britannica অনুযায়ী Chinese Communist Party Chairman Mao Zedong ১৯৬৬ সালে Cultural Revolution শুরু করেন।", "verified", "high", [refs.culturalRevolution], true),
  fact(572, "Sun Yat-sen — Republic of China ও modern China", "Britannica অনুযায়ী Sun Yat-sen Republic of China-এর first provisional president ছিলেন এবং তিনি father of modern China হিসেবে পরিচিত।", "verified", "high", [refs.sun], true),
];

const notes = [
  note(569, "চীন — জিনজিয়াং, Taiwan ও UN-সংক্রান্ত উৎস-রেফারেন্স", "উৎসে Chinese Civil War, Xinjiang, Uyghur Muslim community, Rebiya Kadeer, `East Turkestan`, Ping-Pong Diplomacy, UN representation, Taiwan এবং BRI/OBOR-এর উল্লেখ আছে।\nসতর্কতা | ethnic, religious, territorial-label, advocacy, UN-representation ও cross-strait wording source-attributed। উৎসের ১৯৭১ `socialism established` এবং `permanent membership regained` ভাষা স্বাধীন fact হিসেবে নেওয়া হয়নি।"),
  note(570, "চীন — তিয়েনআনমেন, তিব্বত ও ম্যাকাও উৎস-রেফারেন্স", "উৎসে ১৯৮৯ Tiananmen Square movement, Tibet, Dalai Lama, ১৯৫০/১৯৫৯ chronology এবং Macau/Portugal-এর উল্লেখ আছে।\nসতর্কতা | political, security, territorial, religious, exile-government, crowd-size এবং current-status ভাষা source-attributed। কেবল Nobel 1989 ও Macau transfer date আলাদা corroborated fact হিসেবে রাখা হয়েছে।"),
  note(571, "চীন — Hong Kong ও Taiwan উৎস-রেফারেন্স", "উৎসে Treaty of Nanjing, ১৮৯৮ lease, ১৯৯৭ handover, one country/two systems, Taiwan, Formosa, ১৮৯৫/১৯৪৯/১৯৭১ chronology ও Taiwan officeholder-এর উল্লেখ আছে।\nসতর্কতা | governance, sovereignty, recognition, cross-strait, map এবং current-status wording source-attributed; এগুলো কোনো neutral territorial assertion হিসেবে রূপান্তর করা হয়নি।"),
  note(572, "চীন — মহানপ্রাচীর ও রাজনৈতিক/জীবনী উৎস-রেফারেন্স", "উৎসে Great Wall, Confucius, Mao, Sun Yat-sen এবং Xi Jinping-এর উল্লেখ আছে।\nসতর্কতা | scan-এর ৮,৮৫০ km `current` figure complete Great Wall route-এর সঙ্গে একীভূত করা হয়নি; Mao-এর `প্রথম প্রেসিডেন্ট` লাইন historically unsafe; Xi office ও term-language time-sensitive source material।"),
  note(573, "চীন — বিগত প্রশ্নের উৎস ও withholding boundary", "উৎসে University of Dhaka এবং BCS-labelled MCQ আছে।\nসতর্কতা | Q04, Q05, Q08, Q10, Q11 ও Q13 ambiguous, politically time-sensitive, option/stem-corrupted, বা unreliable-key হওয়ায় withheld। Q09 ও Q15 explanation-এ religious/ethnic wording source-attributed থাকবে।"),
];

const mcqs = [
  mcq("01", "কোন দেশ ‘ওয়ান বেল্ট ওয়ান রোড ইনিশিয়েটিভ’ গ্রহণ করেছে?", ["ভারত", "চীন", "মায়ানমার", "রাশিয়া"], "খ", "DU ঘ, ২৪–২৫", "medium", [refs.bri], true),
  mcq("02", "কোন দেশ ‘বেল্ট অ্যান্ড রোড ইনিশিয়েটিভ’ প্রকল্প চালু করেছে?", ["ভারত", "চীন", "রাশিয়া", "দক্ষিণ কোরিয়া"], "খ", "DU ঘ, ২০–২১", "high", [refs.bri], true),
  mcq("03", "কনফুসিয়াস ছিলেন—", ["দার্শনিক", "নেতা", "সম্রাট", "বিজ্ঞানী"], "ক", "DU ঘ, ১৭–১৮", "high", [refs.confucius]),
  mcq("06", "হংকং কোন সালে গণচীনের অধিভুক্ত হয়?", ["১৯৯৬", "১৯৯৭", "১৯৯৮", "১৯৯৯"], "খ", "DU ঘ, ৯৫–৯৬", "medium", [refs.hongKong], true),
  mcq("07", "সাংহাই ফাইভের প্রধান উদ্দেশ্য কী?", ["অস্ত্র নিয়ন্ত্রণ", "সড়ক নির্মাণ", "প্রযুক্তি হস্তান্তর", "সীমান্ত বিরোধ নিরসন"], "ঘ", "DU ঘ, ০১–০২", "medium", [], true),
  mcq("09", "তিব্বতের ধর্মীয় নেতাকে বলা হয়—", ["ইমাম", "পোপ", "দালাই লামা", "রাবিক"], "গ", "DU ঘ, ০৫–০৬", "medium", [refs.nobel], true),
  mcq("12", "চীনের উদ্যোগে চালু করা ‘বেল্ট অ্যান্ড রোড ইনিশিয়েটিভ’ (BRI)-এর প্রধান লক্ষ্য কী?", ["একটি নতুন আঞ্চলিক অর্থনৈতিক সূচি প্রণয়ন করা", "নৌপথে বিশ্বব্যাপী অর্থনৈতিক সংযোগ", "বিশ্বব্যাপী অর্থনৈতিক উন্নয়ন কার্যক্রম", "বাণিজ্য এবং অবকাঠামো নির্মাণের মাধ্যমে অর্থনৈতিক নেটওয়ার্ক তৈরি করা"], "ঘ", "50 BCS", "medium", [refs.bri], true),
  mcq("14", "‘বেল্ট অ্যান্ড রোড’ কার্যক্রম শুরু হয়—", ["২০০০ সালে", "২০০১ সালে", "২০১৩ সালে", "২০১৬ সালে"], "গ", "45 BCS", "high", [refs.bri], true),
  mcq("15", "চীনের জিনজিয়াং (Xinjiang) প্রদেশের মুসলিম গোষ্ঠীর নাম—", ["তুর্কমেন", "উইঘুর", "তাজিক", "কাজাখ"], "খ", "43 BCS", "high", [], true),
  mcq("16", "ম্যাকাও চীন সাগরে অবস্থিত একটি দ্বীপ যা একটি ইউরোপীয় দেশের কলোনী ছিল। এই ইউরোপীয় দেশটি কী?", ["নেদারল্যান্ডস", "লেবানন", "পর্তুগাল", "ফ্রান্স"], "গ", "20 BCS", "medium", [refs.macao], true),
];

const tags = [
  ["asia", "Asia", "domain", "Source-derived Asia reference."], ["east-asia", "East Asia", "domain", "Source-derived East Asia reference."], ["china", "China", "domain", "China source material."],
  ["reference-note", "Structured source note", "content_type", "Structured source reference with explicit caveats."], ["past-exam-mcq", "Past-exam MCQ", "content_type", "MCQ with a printed source key."], ["answer-key", "Answer key", "content_type", "Correct option from the printed key."],
  ["source-attributed", "Source-attributed", "quality", "Source-preserved material without direct corroboration in this batch."], ["externally-verified", "Externally verified", "quality", "Directly corroborated by cited evidence."], ["time-sensitive", "Time-sensitive reference", "quality", "Political, institutional, territorial, religious, diplomatic, military, or security source material."],
  ["dhaka-university", "University of Dhaka", "exam_source", "University of Dhaka printed examination label."], ["bcs", "Bangladesh Civil Service", "exam_source", "Bangladesh Civil Service printed examination label."],
];
const exam = source => source.includes("DU") ? ["University of Dhaka", "University of Dhaka", "admission", "dhaka-university"] : ["Bangladesh Civil Service", null, "competitive", "bcs"];
const entityRef = (kind, h) => `(SELECT id FROM public.${kind === "fact" ? "gk_facts" : kind === "note" ? "gk_notes" : "gk_mcqs"} WHERE canonical_hash=${q(h)} LIMIT 1)`;

export async function buildBatch() {
  const pages = await Promise.all(files.map(file => fs.readFile(file, "utf8").then(JSON.parse)));
  const topics = BATCH_PAGES.map((page, index) => ["china", ctx(page).topicTitle, ctx(page).topic, page, index + 20]);
  const checks = [...facts.map(row => ({ kind: "fact", claim: row.fact_text, ...row })), ...notes.map(row => ({ kind: "note", claim: row.content, ...row })), ...mcqs.map(row => ({ kind: "mcq", claim: `${row.question} — printed answer: ${row.correct}`, ...row }))];
  const audit = {
    batch_pages: BATCH_PAGES, pipeline_version: PIPELINE_VERSION,
    source_pages: pages.map(page => ({ page: page.source_page, review_status: page.review.review_status, image_sha256: page.source_image_sha256, overall_confidence: page.review.overall_confidence })),
    generated_facts: facts.length, generated_notes: notes.length, generated_mcqs: mcqs.length, generated_options: mcqs.length * 4, generated_flashcards: facts.length + notes.length + mcqs.length,
    verification_counts: { verified: checks.filter(row => row.status === "verified").length, conflicting: 0, source_attributed: checks.filter(row => row.status === "source_attributed").length },
    source_anomalies: ["All five pages were rendered at 300 DPI, transcribed with gpt-5-mini, and reviewed through all 35 ordered overlap-safe tiles.", "Page 569 says socialism was established in 1971 and compresses UN representation; neither is imported as a neutral fact.", "Page 570 contains political/security Tibet and Tiananmen material that remains caveated; page 571 preserves cross-strait wording without status normalization.", "Page 572 has a footer-number mismatch in OCR; physical source page 572 and visual footer 515 control the import.", "Page 573 Q04, Q05, Q08, Q10, Q11, and Q13 are withheld for ambiguity, low confidence, unsafe political premise, or unreliable key."],
    quality_gates: ["Exactly physical source pages 569–573 are imported.", "Every imported MCQ has four visually reviewed options and one printed key.", "No corrupted, ambiguous, time-bound governance, or historically unsafe MCQ is imported.", "Content tags use only approved categories; countries and regions are category domain.", "Upserts use canonical hashes and stable derived-record keys."],
  };
  const topicSql = `INSERT INTO public.topics (chapter_id,title,slug,description,source_page,display_order) SELECT c.id,x.title,x.slug,'Source-preserved content with explicit review and verification status.',x.page::integer,x.ord::integer FROM (VALUES ${values(topics)}) x(chapter_slug,title,slug,page,ord) JOIN public.chapters c ON c.slug=x.chapter_slug AND c.book_id=(SELECT id FROM public.books WHERE title=${q(BOOK_TITLE)} LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id=c.id AND t.slug=x.slug);`;
  const printed = { 569: 512, 570: 513, 571: 514, 572: 515, 573: 516 };
  const pageSql = pages.map(page => { const c = ctx(page.source_page); const metadata = { source_image_sha256: page.source_image_sha256, extraction_model: page.model, review_status: page.review.review_status, corrections: page.review.corrections, unresolved_spans: page.review.unresolved_spans, physical_source_page: page.source_page, printed_book_page: printed[page.source_page], visual_review_report: `${workDir}/visual_review_569_573.md`, external_verification_report: `${workDir}/external_verification.md`, classification_report: `${workDir}/classification_decisions.md` }; return `INSERT INTO public.source_pages (import_run_id,book_id,source_page,page_kind,raw_transcription,chapter_heading,topic_heading,confidence,extraction_method,model_name,notes,review_metadata) SELECT (SELECT id FROM public.import_runs WHERE pipeline_version=${q(PIPELINE_VERSION)} ORDER BY started_at DESC LIMIT 1),b.id,${page.source_page},${q(page.source_page === 573 ? "mcq" : "educational")}::page_kind,${q(page.review.verified_transcript)},${q(c.chapterTitle)},${q(c.topicTitle)},${q(page.review.overall_confidence)}::confidence_level,'vision_ocr_with_image_grounded_review',${q(page.model)},'Quality-gated extraction with ordered source-tile review, withholding rules, and explicit verification status.',${json(metadata)} FROM public.books b WHERE b.title=${q(BOOK_TITLE)} AND NOT EXISTS (SELECT 1 FROM public.source_pages s WHERE s.book_id=b.id AND s.source_page=${page.source_page});`; }).join("\n");
  const factSql = `WITH d(page,chapter_slug,topic_slug,title,body,status,confidence,hash) AS (VALUES ${values(facts.map(row => [row.source_page, row.chapter, row.topic, row.title, row.fact_text, row.status, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_facts (book_id,chapter_id,topic_id,title,fact_text,explanation,source_page,source_section,source_excerpt,importance,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,'Direct corroboration is recorded in the batch verification ledger.',d.page::integer,d.title,d.body,3,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET fact_text=EXCLUDED.fact_text,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence;`;
  const noteSql = `WITH d(page,chapter_slug,topic_slug,title,body,confidence,hash) AS (VALUES ${values(notes.map(row => [row.source_page, row.chapter, row.topic, row.title, row.content, row.confidence, row.canonical_hash]))}) INSERT INTO public.gk_notes (book_id,chapter_id,topic_id,title,content,source_page,source_section,display_order,confidence,canonical_hash) SELECT b.id,c.id,t.id,d.title,d.body,d.page::integer,d.title,d.page::integer,d.confidence::confidence_level,d.hash FROM d JOIN public.books b ON b.title=${q(BOOK_TITLE)} JOIN public.chapters c ON c.book_id=b.id AND c.slug=d.chapter_slug JOIN public.topics t ON t.chapter_id=c.id AND t.slug=d.topic_slug ON CONFLICT (canonical_hash) DO UPDATE SET content=EXCLUDED.content,confidence=EXCLUDED.confidence;`;
  const mcqSql = mcqs.map(row => { const [name, institution, examType, normalizedName] = exam(row.source); const keys = ["ক", "খ", "গ", "ঘ"]; const options = row.options.map((option, index) => `INSERT INTO public.gk_mcq_options (mcq_id,option_key,option_text,display_order,is_correct) SELECT m.id,${q(keys[index])},${q(option)},${index + 1},${keys[index] === row.correct} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_options o WHERE o.mcq_id=m.id AND o.option_key=${q(keys[index])});`).join("\n"); return `INSERT INTO public.exam_sources (name,institution,exam_type,description,normalized_name) SELECT ${q(name)},${q(institution)},${q(examType)},${q(`Normalized from printed source label on page ${row.source_page}.`)},${q(normalizedName)} WHERE NOT EXISTS (SELECT 1 FROM public.exam_sources WHERE normalized_name=${q(normalizedName)}); INSERT INTO public.gk_mcqs (book_id,chapter_id,topic_id,question,correct_option,explanation,source_page,source_section,source_question_number,difficulty,confidence,canonical_hash) SELECT b.id,c.id,t.id,${q(row.question)},${q(row.correct)},${q("Printed answer key retained after visual review; any political, territorial, religious, ethnic, institutional, or diplomatic context is source-attributed and linked in the batch verification ledger.")},${row.source_page},'বিগত বছরের প্রশ্ন',${q(row.number)},3,${q(row.confidence)}::confidence_level,${q(row.canonical_hash)} FROM public.books b JOIN public.chapters c ON c.book_id=b.id AND c.slug=${q(row.chapter)} JOIN public.topics t ON t.chapter_id=c.id AND t.slug=${q(row.topic)} WHERE b.title=${q(BOOK_TITLE)} ON CONFLICT (canonical_hash) DO UPDATE SET correct_option=EXCLUDED.correct_option,explanation=EXCLUDED.explanation,confidence=EXCLUDED.confidence; ${options} INSERT INTO public.gk_mcq_sources (mcq_id,exam_source_id,year,session,source_text,source_page) SELECT m.id,(SELECT id FROM public.exam_sources WHERE normalized_name=${q(normalizedName)} LIMIT 1),NULL,${q(row.source)},${q(row.source)},${row.source_page} FROM public.gk_mcqs m WHERE m.canonical_hash=${q(row.canonical_hash)} AND NOT EXISTS (SELECT 1 FROM public.gk_mcq_sources s WHERE s.mcq_id=m.id AND s.source_text=${q(row.source)} AND s.source_page=${row.source_page});`; }).join("\n");
  const assignment = (kind, row, tagsForRow) => tagsForRow.map(tag => `INSERT INTO public.content_tag_assignments (tag_id,entity_type,entity_id,source_page,confidence,assigned_by) SELECT t.id,${q(kind)},${entityRef(kind, row.canonical_hash)},${row.source_page},${q(row.confidence)}::confidence_level,'batch-0569-0573-quality-pipeline' FROM public.content_tags t WHERE t.slug=${q(tag)} ON CONFLICT DO NOTHING;`).join("\n");
  const tagSql = `INSERT INTO public.content_tags (slug,label,category,description) VALUES ${tags.map(row => `(${row.map(q).join(",")})`).join(",")} ON CONFLICT (slug) DO UPDATE SET label=EXCLUDED.label,category=EXCLUDED.category,description=EXCLUDED.description;\n${facts.map(row => assignment("fact", row, ["asia", "east-asia", "china", "externally-verified", ...(row.timeSensitive ? ["time-sensitive"] : [])])).join("\n")}\n${notes.map(row => assignment("note", row, ["asia", "east-asia", "china", "reference-note", "source-attributed", "time-sensitive"])).join("\n")}\n${mcqs.map(row => assignment("mcq", row, ["asia", "east-asia", "china", "past-exam-mcq", "answer-key", exam(row.source)[3], "source-attributed", ...(row.timeSensitive ? ["time-sensitive"] : [])])).join("\n")}`;
  const verificationSql = checks.map(row => `INSERT INTO public.fact_verifications (source_page,entity_type,entity_id,claim_text,normalized_claim,verification_status,confidence,verification_sources,audit_note) SELECT ${row.source_page},${q(row.kind)},${entityRef(row.kind, row.canonical_hash)},${q(row.claim)},NULL,${q(row.status)},${q(row.confidence)}::confidence_level,${json(row.sources)},${q(row.status === "verified" ? "Direct corroboration is listed in the batch verification ledger." : "Source-attributed record retained with ordered image-grounded validation and explicit source linkage.")} WHERE NOT EXISTS (SELECT 1 FROM public.fact_verifications v WHERE v.entity_type=${q(row.kind)} AND v.entity_id=${entityRef(row.kind, row.canonical_hash)} AND v.claim_text=${q(row.claim)});`).join("\n");
  const derivedSql = `INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),f.book_id,f.chapter_id,f.topic_id,f.title,f.fact_text,'fact',f.id,'batch0569-0573:fact:'||f.id::text FROM public.gk_facts f WHERE f.source_page BETWEEN 569 AND 573 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0569-0573:fact:'||f.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),n.book_id,n.chapter_id,n.topic_id,n.title,n.content,'note',n.id,'batch0569-0573:note:'||n.id::text FROM public.gk_notes n WHERE n.source_page BETWEEN 569 AND 573 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0569-0573:note:'||n.id::text); INSERT INTO public.flashcards (subject_id,book_id,chapter_id,topic_id,front_text,back_text,source_type,source_id,source_key) SELECT (SELECT id FROM public.subjects ORDER BY created_at ASC LIMIT 1),m.book_id,m.chapter_id,m.topic_id,m.question,'সঠিক উত্তর: '||o.option_key||'. '||o.option_text,'mcq',m.id,'batch0569-0573:mcq:'||m.id::text FROM public.gk_mcqs m JOIN public.gk_mcq_options o ON o.mcq_id=m.id AND o.is_correct WHERE m.source_page=573 AND NOT EXISTS (SELECT 1 FROM public.flashcards c WHERE c.source_key='batch0569-0573:mcq:'||m.id::text); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'fact',f.id,f.title,f.fact_text,'Status-marked GK fact | source page '||f.source_page::text FROM public.gk_facts f WHERE f.source_page BETWEEN 569 AND 573 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='fact' AND d.entity_id=f.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'note',n.id,n.title,n.content,'Structured source reference | source page '||n.source_page::text FROM public.gk_notes n WHERE n.source_page BETWEEN 569 AND 573 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='note' AND d.entity_id=n.id); INSERT INTO public.search_documents (entity_type,entity_id,title,body,english_metadata) SELECT 'mcq',m.id,NULL,m.question,'Past-exam MCQ | source page '||m.source_page::text||' | question '||m.source_question_number FROM public.gk_mcqs m WHERE m.source_page=573 AND NOT EXISTS (SELECT 1 FROM public.search_documents d WHERE d.entity_type='mcq' AND d.entity_id=m.id);`;
  const sql = `-- Generated by prepare_validated_batch_0569_0573.mjs. Source pages 569–573 only.\nBEGIN;\nINSERT INTO public.import_runs (source_filename,source_sha256,pipeline_version,status,completed_at,audit) VALUES ('Jubayer''sgk.pdf',${q(hash(pages.map(page => page.source_image_sha256).join("|")))},${q(PIPELINE_VERSION)},'completed',now(),${json(audit)});\n${topicSql}\n${pageSql}\n${factSql}\n${noteSql}\n${mcqSql}\n${tagSql}\n${verificationSql}\n${derivedSql}\nCOMMIT;`;
  return { sql, audit };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { sql, audit } = await buildBatch();
  const counts = { batch_pages: BATCH_PAGES, review_tiles: 35, eligible_mcqs: mcqs.length, eligible_mcq_options: mcqs.length * 4, withheld_mcqs: 6, fact_candidates: facts.length, note_candidates: notes.length, verification_statuses: audit.verification_counts };
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, "validated_import.sql"), sql);
  await fs.writeFile(path.join(outputDir, "batch_audit.json"), JSON.stringify(audit, null, 2));
  await fs.writeFile(path.join(outputDir, "execute_sql_request.json"), JSON.stringify({ project_id: "rennotctgrxvbpghbimx", query: sql }));
  await fs.writeFile(path.join(workDir, "import_input_counts.json"), JSON.stringify(counts, null, 2));
  console.log(JSON.stringify({ outputDir, ...audit, counts }, null, 2));
}
